### ISSUE TITLE
[Symfony] Do not use Session deprecated features

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#10345]
### Improvement description

`\Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag` has been deprecated. 
We need to provide our own implementation. 

See: https://symfony.com/doc/current/session.html#basic-usage

**Comment by langert** [comment]
Because of the deprecated info, adapting the example of the docs, I simply struggle trying to register a non namespaced AttributeBag in my 10.1 bundle. 
"Cannot register a bag when the session is already started.". 

I get this Exception when I try to set any value to the bag. 

`$this->session->getBag('my_name')->set('myparam', 'value#)` 

Where/when do I have to register the AttributeBag to be before haveing pimcore/symfony started the session? Do I need to use the pimcore SessionConfiguratorInterface or can I just use it like this:

`$this->session = $requestStack->getSession();
$bag = new AttributeBag('my_name');
$this->session->registerBag($bag);
`

**Comment by solverat** [comment]
@langert besides that your struggle is unrelated to this ticket: you need to register your bag via `pimcore.session.configurator` tag.

```yaml
App\Session\SessionConfigurator:
  tags:
      - { name: pimcore.session.configurator } 
 ```

```php
<?php

namespace App\Session;

use Pimcore\Session\SessionConfiguratorInterface;
use Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag;
use Symfony\Component\HttpFoundation\Session\SessionInterface;

class SessionConfigurator implements SessionConfiguratorInterface
{
    public function configure(SessionInterface $session)
    {
        $bag = new NamespacedAttributeBag('_your_bag');
        $bag->setName('your_bag');
        $session->registerBag($bag);
    }
}
```

But I would suggest using the `$request->getSession()` method instead.

**Comment by dvesh3** [comment]
We are not using namespaces for session storage items in the core, so I would suggest we simply replace the `NamespacedAttributeBag` usages with `AttributeBag` instead of re-implementing it in the core.
