### ISSUE TITLE
[Improvement]: Leverage the new Symfony Runtime component

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#10344]
### Improvement description

See: 

https://symfony.com/doc/current/components/runtime.html
https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/5.3/public/index.php

**Comment by dkarlovi** [comment]
Ideally, Pimcore should **not** provide its own custom runtime to solve architectural problems, even though I'd expect it will be the first direction here.

The reason is: you'll want to do that to **actually swap out runtimes for the intended purpose**, for example using [Bref](https://github.com/php-runtime/bref) to deploy Pimcore as AWS Lambda maybe? Having a Pimcore runtime + and then needing to integrate it somehow with Bref (or Swoole or other) runtime implementation will be a huge obstacle.

**Comment by mattamon** [comment]
Using Symfony Runtime on demo and demo-enterprise now
