### ISSUE TITLE
[Feature]:Login/logout history log.

### ISSUE THREAD

**Issue by abhisheksingh-pimcore** [pimcore/pimcore#10422]
### Feature description

Logon/logout history log should be the default feature. I have not found anywhere the login log details in Pimcore.

**Comment by NiklasBr** [comment]
Can you achieve this with the `usagelog.log` [file](https://pimcore.com/docs/pimcore/current/Development_Documentation/Development_Tools_and_Details/Logging.html#page_usagelog-log "Link to docs")? It should contain lines like: 

```log
2021-08-25T16:30:04+0200 : 0|Pimcore\Bundle\AdminBundle\Controller\Admin\LoginController::loginAction|pimcore_admin_login|[]|{"perspective":""}
```

**Comment by abhishekceon** [comment]
@NiklasBr  We can't achieve login log history for the specific users through this userlog.log. In this log there are lots of things, parsing this file for getting log history for the specific user, I don't think is a good idea.

We should have this feature inbuild through tables so that any individual can see their own login history after login and the admin can see anyone's login history for any specific time duration or day.

**Comment by brusch** [comment]
Thanks a lot for sharing your ideas. However, since this is quite a special interest use-case, we're not gonna work on that anytime soon. Please feel free to continue the discussion here. 
Thanks for your understanding.

@abhishekceon would be a perfect candidate for an optional bundle - should be quite easy to implement as the necessary events are already there.
