### ISSUE TITLE
[Bug]: Reverse Object Relation not working for object bricks

### ISSUE THREAD

**Issue by mick340** [pimcore/pimcore#10593]
### Expected behavior

When using object bricks with a many to many relationship (we call it product group) inside a dataobject i expect to use a reverse object relation in  another data object (product) to show all product groups where the product is linked to.

### Actual behavior

When adding a reverse relation to the dataobject (product) it wont give me a option to select the correct owner field.

### Steps to reproduce

1. Create a object brick with a Many-to-Many object relation. I will call my object brick kwantum, it has a many-to-many relationship with products

![Screenshot 2021-10-14 at 09 25 00](https://user-images.githubusercontent.com/8590308/137272180-c63f732a-b0be-40a5-9cde-2e889f141b4c.png)

2. Create a datobject (i will call it product group) wich will use the object brick

![Screenshot 2021-10-14 at 09 25 35](https://user-images.githubusercontent.com/8590308/137272327-5390ba39-f91b-40fa-93e3-f4c46af4aea1.png)

![Screenshot 2021-10-14 at 09 26 09](https://user-images.githubusercontent.com/8590308/137272367-601ca7fb-07e6-4a5c-92cb-4697a28059db.png)

As you can see, all products are linked to the product group

![Screenshot 2021-10-14 at 09 26 36](https://user-images.githubusercontent.com/8590308/137272708-08d070eb-10aa-4a27-b35b-148e5043e25d.png)

3. Create a dataobject (product, wich has the relationship with the kwantum object brick), add a reverse object relation and try to use the prdocut group data object (where the object brick is linked to)

![Screenshot 2021-10-14 at 09 28 14](https://user-images.githubusercontent.com/8590308/137272523-b6d4af99-64e8-4cce-97f0-79fcaaec1051.png)

![Screenshot 2021-10-14 at 09 28 23](https://user-images.githubusercontent.com/8590308/137272539-a04c86ef-0c93-4f98-8f55-1ed1d211de72.png)

As you can see there is no option to select the object brick to show all linked product groups.

**Comment by ghost** [comment]
FYI: I've also wanted to do this. I could get the Owner field to show up in the list by marking the actual field (kwantum.products) as "Visible in search". This will make it show in that "Owner field" dropdown as "kwantum~products". Problem is, it doesn't seem to actually work. I thought it did, but I just realized it doesn't. Works fine with fields that belong to the Owner class, but technically the bricks are a separate object that extend that main object..
I'm still on 6.9, the situation might be different in Pimcore X. I hope it is, because i'd like to have the functionality when I'm done with the upgrade :unamused: .
Nope. just tried it on the Live pimcore demo.. still the same situation, you can make the field show with the "Visible in search", but it doesn't actually find the relations :unamused:

**Comment by CodeBrauer** [comment]
Just ran into the same problem. Had to create the field in the Data Object itself now, which means extra work. Unfortunately, not quite as simple.

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
