### ISSUE TITLE
Less compilation is no more cached - Using Less_Cache from oyejorge/less.php

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#1065]
I don't know if it is intended, but i prefer to report the commented line:
https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/Tool/Less.php#L175
It means it will be compiled each time if i am not wrong.

Maybe we could drop lessc compilation to just keep oyejorge/less.php package to handle less compilation ?
It will be more easy for caching as it already implement an effective caching system which check for imported file in the css too:
https://github.com/oyejorge/less.php#caching

**Comment by solverat** [comment]
I think the implemented LESS compilation is deprecated and will be removed in future versions (not just because SASS is the better option ;) ) - use grunt or gulp to do the job. 

to implement a less package is also not the best idea - too much dependencies and possible error sources. But that's just my opinion.

**Comment by brusch** [comment]
Yes, LESS Support in Pimcore is deprecated and will be removed. 
It's definitely better to migrate to Grunt or Gulp. 

Regarding the cache: yes, that's intentional, please see: 
https://github.com/pimcore/pimcore/commit/731efe06816eac5947b4b2807d2e9e742b4000dc
https://github.com/pimcore/pimcore/commit/3599e8cb0e3abe6469100c12f864e9b34df6afef
