### ISSUE TITLE
Allow more characters in asset keys

### ISSUE THREAD

**Issue by Cruiser13** [pimcore/pimcore#1070]
# Feature Request 
With #898 we got the possibility to use assets with capitals and spaces.
German umlaute are not possible at the moment although Pimcore should handle UTF-8 everywhere properly.
A file with the filename **Test mit ö und straßße.txt** will become **Test mit oe und strasssse.txt** this way.

It'd be great to allow more characters in the asset keys because we could sync more files using the WebDav connection (we're using Pimcore in our intranet as DAM). At the moment the synchronisation will fail:
The client has two files after sync, one with ö and ß and another one with oe and ss and will try to upload the file with ö and ß again to the Pimcore server (which leads to a new version of the file being added).

**Comment by brusch** [comment]
Actually the limitation comes from the maximum length of indices in MySQL. 
That's why we decided to use ASCII instead of UTF8 for the filenames/pathes, see also: 
https://github.com/pimcore/pimcore/blob/4a576fd30a9a967c5eb69751a5e7f8543882c564/pimcore/modules/install/mysql/install.sql#L31-L31

With this trick we can have pathes up to a length of 765 instead of just 255, which is way too short in our opinion. If you have a solution that works with both with utf8 and path length >= 765 let me know :)

**Comment by Cruiser13** [comment]
I see. Thanks for the explanation!
