### ISSUE TITLE
[Bug]: custom reports not createable/modifyable with "app_debug=false"

### ISSUE THREAD

**Issue by woellundwoell** [pimcore/pimcore#10813]
### Expected behavior

* custom reports are createable/modifyable with app_debug=false

### Actual behavior

* custom reports are not createable/modifyable with app_debug=false (only with app_debug=true)

### Steps to reproduce

* set app_debug=false
* check custom report section: add button is greyed out and save button for existing c.report is greyed out (also in demo system)

I traced this issue to https://github.com/pimcore/pimcore/blob/bf3b7bcf6230ea36a6f79549e94f83ac7877fef9/lib/Config/LocationAwareConfigRepository.php#L183
Is there a reason to not edit/create custom reports with app_debug=false?

**Comment by brusch** [comment]
That's intentional.
Configs are written to Symfony Config files ( `yaml`), which are only getting revalidated in debug mode. So if you're changing configs in production you won't see any update, because the config isn't getting updated. 

If you'd like to allow changes in production, switch to the alternate `settings-store` config storage. 
You can do so by adding the following to your `.env` or just set the env variable accordingly: 

```
PIMCORE_WRITE_TARGET_CUSTOM_REPORTS=settings-store
```

See also: https://pimcore.com/docs/pimcore/current/Development_Documentation/Deployment/Configuration_Environments.html#page_Configuration-Storage-Locations-Fallbacks

**Comment by dvesh3** [comment]
@brusch I think docs should be updated. https://github.com/pimcore/pimcore/commit/9c40205ab2e8e2272b84f39284b9726e21f72dac

**Comment by brusch** [comment]
@dvesh3 thanks for updating!
