### ISSUE TITLE
Ability to disable admin translations

### ISSUE THREAD

**Issue by josh-palan** [pimcore/pimcore#1094]
## Feature description 
  Translations are causing my objects to load extremely slowly. I have multiple drop downs with more than a thousand possible values, each of which has generated a key within the admin translations. When loading an object, each of these options has to be ran through the list of all keys. It would be great to be able to prevent certain keys from being added to the admin translations, prevent certain fields from being translated, or disable admin translations completely.

**Comment by brusch** [comment]
It seems that no one else is experiencing similar issues. 
A possible way would be to create your own custom data-type that extends from the core select type, but doesn't use admin translations. 
An alternative would be to provide an option on the select data-type to not translate the values - we'd accept a PR for that.

**Comment by cuca24** [comment]
@brusch 
This is indeed a problem that we have with multiple clients. 

I did a js profiling and it turns out that the calls for translations are expensive according to profiling

![Image](https://github.com/user-attachments/assets/dd55ff23-cb32-4928-9d9b-b02d2e0f20d6)

When redefined in inspect element function t (which is used for translations) into this var t = function (key) {return key}; opening tabs works instantly.

This is a stacktrace to function t

![Image](https://github.com/user-attachments/assets/745f8b2e-59ca-4654-b749-9ac6ed07d700)

This function getLayoutEdit is actually select.js function (pimcore's class as select data type) and uses translations for option text.

![Image](https://github.com/user-attachments/assets/98fbd2e1-d7a8-4c60-bfda-a653cf0e77f8)

PS: I have somewhat performance PC. For other people it takes much longer for example 5 - 10 seconds or even more.

I assume that this will not get fix on admin classic ui bundle. but at least if you could take into consideration implementation on studio ui.
