### ISSUE TITLE
[Bug]: TranslatorInterface created by Container is not supported anymore

### ISSUE THREAD

**Issue by alexanderkroneis** [pimcore/pimcore#10952]
### Expected behavior

Show a list of documents on the left side of the navigation.

### Actual behavior

Modal opens with following error message

```
The "Symfony\Contracts\Translation\TranslatorInterface" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

Server threw exception - could not perform action. Please reload the admin interface and try again.
```

### Steps to reproduce

- Access your local installation on Pimcore v10.1.5
- Login with valid credentials
- See the error message

**Comment by alexanderkroneis** [comment]
Meanwhile I figured out it's coming from this line:

```
if ($site instanceof Site) {
->  $translator = \Pimcore::getContainer()->get(TranslatorInterface::class);
    $this->elementQtipConfig['text'] .= '<br>' . $translator->trans('site_id', [], 'admin') . ': ' . $site->getId();
}
```

**Comment by dvesh3** [comment]
@alexgaal sorry, it works for me:

![image](https://user-images.githubusercontent.com/5137917/144587748-a4b6813c-5206-412b-a0b6-3ab57e4d5db2.png)

**Comment by dvesh3** [comment]
Closing as there's no response. Please feel free to come back with reproducible case.

**Comment by kevinulrich** [comment]
This happens to me as soon as I convert anything directly under root to a site. Same line as OP has pointed out. Ridiculous, I'm not sure why we're still getting our container from a singleton with `->get()` instead of just using DI for this. Even if this Bug wasn't relevant that's just bad practise.

For anyone looking for a solution, it's a temporary fix to simply alias the Interface to Pimcore Translator. I didn't check this too deeply:

```
# config/services.yaml

Symfony\Contracts\Translation\TranslatorInterface: '@Pimcore\Translation\Translator'
```

You will also need to make that service us public by either setting it as default or especially targeting that Translator service.

**Comment by dvesh3** [comment]
please see, if you are facing the issue https://github.com/pimcore/pimcore/pull/12041#discussion_r867312266

**Comment by micru** [comment]
Frankly, the use of `\Pimcore::getContainer()` is such bad practice that it simply should not be used and should be completely removed from the core of Pimcore. Perhaps apart from special cases, such as CalculatedValue fields when the service is loaded from a configuration specified by the user via the Admin UI.

Direct access to the container creates unnecessary dependency, leads to poor (unit) testability etc and makes the use of DI itself almost questionable again, because it works completely against the principle.
It is not without reason that services in Symfony are private by default and thus cannot be pulled directly from the container.

**Comment by fashxp** [comment]
any contributions to improve that are highly welcome 😊

**Comment by micru** [comment]
I think it would be a good start if it is not used in new code at first.

A relatively recent, randomly selected example. 
https://github.com/pimcore/pimcore/blob/10.x/lib/Console/Traits/Parallelization.php#L138
interestingly, there already exists a method `getContainer` just a few lines of code above. 
In traits, services would then certainly have to be injected via setter, but it would be possible without any difficulty.

Another, also randomly selected example (different repo, but Pimcore):
https://github.com/pimcore/data-hub/blob/1.4/src/GraphQL/Mutation/MutationType.php#L260

Here the used factory is even already injected via the constructor and then pulled directly out of the container again anyway :see_no_evil:

**Comment by fashxp** [comment]
wanna contribute some fixes for that?

**Comment by micru** [comment]
Sure, why not! But give me a couple of days :)
