### ISSUE TITLE
[Symfony] Do not use deprecated Session service injections

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#11042]
### Improvement description

Please see https://github.com/pimcore/pimcore/pull/11041

https://symfony.com/blog/new-in-symfony-5-3-session-service-deprecation

**Comment by solverat** [comment]
Heavy task since the session management in pimcore is… difficult. Things like `$this->csrfToken = Session::getReadOnly()->get('csrfToken')` needs to be considered also.

We currently have a lot of issues regarding session management (mostly a Symfony 5.4 thing. Since then, weird session issues pop up everywhere in the symfony community).

For example, since 5.4 we're no longer able to log in into pimcore backend via acceptance tests (which is a simple "I go to /admin, and I prefill form and I click submit").  This will now lead to the ominous pimcore CSRF protection exception _"do not do evil things..."._

**Comment by solverat** [comment]
Ok, and again, I spent too much time on this. In my case, the issue gets triggered by PIMCOREs `test.yaml` where it's using the `session.storage.mock_file` in `storage_id` which is deprecated.

I changed that in my test case to `session.storage.native` for now.

*** 

Just for reference,  `session.storage.mock_file` should get replaced by this (i guess) by this (after the session service has been removed, otherwise this won't work either)

```yaml
framework:
    session:
        storage_factory_id: session.storage.factory.mock_file
 ```
