### ISSUE TITLE
[Bug]: Select search broken in data objects

### ISSUE THREAD

**Issue by valentin-** [pimcore/pimcore#11076]
### Expected behavior

Show suggestions when typing

![image](https://user-images.githubusercontent.com/90033/147073858-1df6b74b-12f3-4e9c-a47e-4f748ae1d7b8.png)

### Actual behavior

There are no suggestions for selects/multiselects.

### Steps to reproduce

It's reproducible in the demo:

https://demo.pimcore.com/admin/login/deeplink?object_1018_object

**Comment by paulverdu** [comment]
I'm having the same issue. However, when changing a multiselect field setting to 'render type' 'tag' the autocomplete search does work..

**Comment by MarcW09** [comment]
Same issue here on Pimcore Version 10.2.8. Also working for mutliselect fields with 'render type' 'tag'.

**Comment by MarcW09** [comment]
I found out, that the bug came with this change: [678c6f41d473672bccdd828ca8a3394e6210fe68](https://github.com/pimcore/pimcore/pull/10871/commits/8a1d71ae4b604d168e5ab2668cd50e9b3585d1e2)

The change removed the code line "displayField: 'key',". When adding the code line again, the select field search works fine. I will make a PR for that.

**Comment by mcop1** [comment]
fixed by #11312
