### ISSUE TITLE
[Bug]: Exception thrown in "Search Assets" window

### ISSUE THREAD

**Issue by vollborn** [pimcore/pimcore#11281]
### Expected behavior

If no search is provided initially and the table is sorted, all assets should be displayed in correct order.

![grafik](https://user-images.githubusercontent.com/67763683/151210668-6234c724-55d7-4b1e-8944-06367944ac63.png)

### Actual behavior

If no search is provided initially and the table is sorted, an exception is thrown.

![grafik](https://user-images.githubusercontent.com/67763683/151211265-340bb916-2de0-4f79-abd0-9a5e11cf033f.png)

Exception:
```
Pimcore\Bundle\AdminBundle\Controller\Searchadmin\SearchController::filterQueryParam(): Argument #1 ($query) must be of type string, null given, called in /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Searchadmin/SearchController.php on line 74

Server threw exception - could not perform action. Please reload the admin interface and try again.
```

### Steps to reproduce

1. Head over to [https://demo.pimcore.fun/admin/?perspective=CMS](https://demo.pimcore.fun/admin/?perspective=CMS)
2. Create a blank page
3. Add an image element
![grafik](https://user-images.githubusercontent.com/67763683/151211857-1544aff6-3a03-4dca-8de2-9e8d252ba1c7.png)
4. Right click the element > Search
![grafik](https://user-images.githubusercontent.com/67763683/151212453-73055fef-49bc-463c-9a21-a86b2419c2c1.png)
5. Click directly on a table header, e.g. "Path", to sort the content. Do not type anything in the search field beforehand.
![grafik](https://user-images.githubusercontent.com/67763683/151212603-5b11bd07-5dc4-4929-9ece-0d6ec455d57a.png)

**Comment by BabovicT** [comment]
This is ExtJS core bug. Because headers use plugin 'gridfilters' there is no way to fix that in js directly. It also affects every search where there is table like that. It works after you search for anything(results not needed).
There are 2 potential solutions tho. 
1. Add logic to controller to check are every parameters send. Missing in this situation(query, type, subtype, context).
2. Add to js to initiate search on search window open. There is no impact to preformance because documents and objects have little data to load, assets do have preview but it is lazy loaded so even assets search windows loads instantly.
@brusch @dvesh3  what dou you think is there need for any of there 2 solutions and if yes for which one?

**Comment by blankse** [comment]
I created a PR for this: https://github.com/pimcore/pimcore/pull/11303
