### ISSUE TITLE
[Improvement]: Use `RuntimeCacheTrait` whenever possible instead of dealing with `Cache\Runtime` directly

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#11339]
### Improvement description

`RuntimeCacheTrait` was introduced by #11254 

There are multiple places in the code where `Pimcore\Cache\Runtime` is used directly in models, this should be changed to the new trait.

**Comment by aashan10** [comment]
@brusch, @fashxp I have a few questions regarding the introduction of `RuntimeCacheTrait`

1. The name says `RuntimeCacheTrait` but it is also using the Data Cache as @dvesh3 pointed out.
2. If that is the intended behavior, the parameters are being ignored for `\Pimcore\Cache::save` method and default parameters are being passed on `RuntimeCacheTrait::setCache`.
3. If that is not the intended behavior and the `RuntimeCacheTrait` should only focus in the objects cached during the runtime, does it make sense to use a trait?
4. What exactly is the benefit of using a trait besides the `$cacheEnabled` which skips runtime cache and loads/retrieves data from the Data Cache, which is also skeptical because I haven't found a case where Runtime cache is skipped and Data cache is being used. On the contrary, some cases exist where Runtime cache is being used but not Data cache.

**Comment by brusch** [comment]
@aashan10 you're right - good catch, that's currently not consistent. 
The original aim was to make dublicate/similar code snippets as this less complex and easier to read: 
https://github.com/pimcore/pimcore/pull/11254/files#diff-573cb570af68f403714ac3cb4ed1c4257e01cd71a4f8104d14f3afc89a0e8a10L80

To be honest, I think we should deprecate `RuntimeCacheTrait` (and all it's methods where we should trigger a deprecation message) and use just the plain caching stuff instead, same as we do here: https://github.com/pimcore/pimcore/blob/2b9fd473ddacccbdaf52c238e17d3d98df213271/models/Document.php#L242

Additionally we should introduce a `$force` flag to the `getById` methods on classes that currently use `RuntimeCacheTrait`. 

WDYT?

**Comment by aashan10** [comment]
@brusch sure, I'll close the PR #12348 and create a new pull request with the deprecation warnings on `RuntimeCacheTrait`, add the `$force` flag and modify the places where `RuntimeCacheTrait` is being used.
