### ISSUE TITLE
[Bug]: Twig "pimcore_url()" throws Exception for unpublished pages if used in included snippet

### ISSUE THREAD

**Issue by akno77** [pimcore/pimcore#11660]
### Expected behavior

"pimcore_url()" works if I have a snippet which is included in a template via a property.

### Actual behavior

Exception: `Pimcore\Routing\DynamicRouteProvider::getRouteByName(): Return value must be of type Symfony\Component\Routing\Route, null returned`

### Steps to reproduce

1. Snippet Template with Code like `{% set activePage =  pimcore_url() %}`
2. Add a snippet with this template
3. Assign the created snippet doc to an page property like `metanavigation_snippet`
4. Include this snippet via page property like `{{ pimcore_inc(document.getProperty('metanavigation_snippet')) }}`
5. If the page, where the snippet is included, is published => works fine, pimcore_url() returns the URL of the initial request
6. If the page is unpublished => Exception

**Comment by RuudvdvNB** [comment]
This also happens when using Router to generate the URL in PHP so it's not only an issue in Twig. The following generate works fine when a document is published, but when a document is unpublished it returns the same error.

```
$router->generate('document_' . $id, [], $absolute)
```

I tried following the generate method, looks like it happens this happens in `\Pimcore\Routing\Dynamic\DocumentRouteHandler::handleDirectRouteDocument`. There is a validation to see if the Document is published, this results in a `null` value in `\Pimcore\Routing\Dynamic\DocumentRouteHandler::buildRouteForDocument`.
