### ISSUE TITLE
[Bug]: Translations tab update button not visible in second line

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#11678]
### Expected behavior

Translation "update" functionality is always available in table editor.

### Actual behavior

"Update" button is gone (overlapped by headerbar) in second line in Translations tab with active filter.

### Steps to reproduce

In Pimcore Demo

1. Filter by "2-door b"
2. Try to update second result
3. No update button available, record can't be saved via mouse click just by Keyboard ENTER.

![image](https://user-images.githubusercontent.com/9052094/158578323-7155319b-c827-431f-9cf0-c9476deead12.png)

**Comment by kingjia90** [comment]
This bug is classified as `EXTJS-19471` on ExtJS ticketing system and it was fixed in the [7.1.0](https://docs.sencha.com/extjs/7.1.0/guides/whats_new/release_notes.html#whats_new-_-release_notes_-_classic) (while Pimcore still uses `7.0.0.159` at the moment).
I've tried locally with `7.1.0.46` but does NOT work (as also mentioned and confirmed [here](https://forum.sencha.com/forum/showthread.php?472966-RowEditing-Buttons-not-visible)). 
It works for on the latest `7.5.1` though, so i guess we have to upgrade the version bundled with Pimcore and it will be fixed everywhere.

In the meantime, the  [quick fix](
https://forum.sencha.com/forum/showthread.php?305665-RowEditing-Buttons-not-visible&p=1317756&viewfull=1#post1317756) here from @dpfaffenbauer 🙌  is still valid.

**Comment by dvesh3** [comment]
Fixed by #11841
