### ISSUE TITLE
[Improvement] Improve docs for thumbnail prefixes

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#11691]
### Improvement description

make usage and requirements of `thumbnail_deferred` more clear

see https://pimcore.com/docs/pimcore/current/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/File_Storage_Setup.html

**Comment by khusseini** [comment]
Just fyi, we spent the whole day wondering why our application is super slow on pages with deferred thumbnails which all were pointing to 404 exceptions. We copied the value from the documentation only to realize late in the day that the culprit was setting `thumbnail_deferred` to `/deferred_thumbnail`. Maybe a note that the default setting is `/` could prevent others from doing the same mistake.

**Comment by brusch** [comment]
@khusseini thanks for your feedback, can you maybe create a PR with an improved documentation? That would be great, thanks!

**Comment by khusseini** [comment]
I could add a note that one has to know what they are doing changing the `thumbnail_deferred` value, however I have no clue about the internals of that setting.
