### ISSUE TITLE
[Bug] Search doesn't show results under certain cirumstances

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#11822]
### Expected behavior

search finds all matching elements

### Actual behavior

search doesn't find all elements, see also https://github.com/pimcore/pimcore/issues/6771#issuecomment-674850816

### Steps to reproduce

- create dataset with many (> limit size of find action, default = 25) similar elements, e.g. all elements containing some string `manyelement` 
- add additional element with specific string e.g. `manyelement X`
- create user and make sure, that this user only sees `manyelement X`, but not the other elements
- search for `manyelement` 
 --> user doesn't find any element, also not `manyelement X`

**Comment by fashxp** [comment]
corresponding tests see https://github.com/pimcore/pimcore/blob/e6c2c445cb56ec93e24e03f1c079efb4b7a699b2/tests/Model/Permissions/ModelPermissionsTest.php#L609

**Comment by kingjia90** [comment]
coming from #11714, the search uses a completely different approach than what you see in the `treeGetChildsById`, it doesn't use the same sql condition for the listing permission, but uses this [getForbiddenCondition](
https://github.com/pimcore/pimcore/blob/da43b3f5fb18b59bdadfa49a77b43eb69d7ebf5e/bundles/AdminBundle/Controller/Searchadmin/SearchController.php#L350). They sometimes match because ultimately both use `isAllowed()`, but it also depends on the following `$hits`:

https://github.com/pimcore/pimcore/blob/da43b3f5fb18b59bdadfa49a77b43eb69d7ebf5e/bundles/AdminBundle/Controller/Searchadmin/SearchController.php#L302-L307

the rule of user level permission precedence over the role level seems missing as well:

https://github.com/pimcore/pimcore/blob/da43b3f5fb18b59bdadfa49a77b43eb69d7ebf5e/models/Element/Service.php#L719-L743
