### ISSUE TITLE
[Improvement]: JavaScript: Conflict between "onPostUpdate" event and closing of an object.

### ISSUE THREAD

**Issue by timwiechers** [pimcore/pimcore#11823]
### Expected behavior

When I use the "postSaveObject" event to reload an object after saving it (because for example data was changed server-side after saving, see "Steps to reproduce"), I have the information if the object should be closed after saving, so I can decide if the reload is necessary.

### Actual behavior

I don't see a way to determine if the object will be closed and therefore cannot decide wether to reload the object or not. 
So after clicking on the "Save, publish and close" button, the reload always opens it again.

### Steps to reproduce

1. Create a simple plugin, that reloads an object after it was updated:
```
    pimcore.registerNS('pimcore.test.admin.plugin');

    pimcore.test.admin.plugin = Class.create(pimcore.plugin.admin, {
        getClassName: function () {
            return 'pimcore.test.admin.plugin';
        },

        initialize: function () {
            pimcore.plugin.broker.registerPlugin(this);
        },

        postSaveObject: function (object) {
            object.reload();
        },
    });

    let PimcoreTestAdminPlugin = new pimcore.test.admin.plugin();
```
2. Click "Save, publish and close"-Button.
3. Object gets reopened.

**Comment by kingjia90** [comment]
the `save, publish and close` it's just a save with a callback to the .close(), therefore there are nothing in particular to differenciate it from the "usual" manual save and close, it is just one fewer click.
https://github.com/pimcore/pimcore/blob/d124b16a837567ed9b7ff010fdeff6e82e9bfaf3/bundles/AdminBundle/Resources/public/js/pimcore/object/object.js#L663-L672

Since the `postSaveObject` is fired in the save and before the `close`, it could be tricky to make it work.

**Comment by kingjia90** [comment]
@timwiechers i've made a PR, so you will be able to do as expected by changing this
```
 postSaveObject: function (object) {
     if (!object.willClose){
          object.reload();
     }
 }
```
This PR also opens to other combinations like a post save event listener that "cancels" the closing action, by turning `object.willClose = false;'.

**Comment by timwiechers** [comment]
@kingjia90 Thanks a lot 👍
