### ISSUE TITLE
[Feature]: VIPS image adapter

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#12052]
### Feature description

Implement the image adapter using https://github.com/libvips/php-vips

In our test (a non-Pimcore app), we migrated from ImageMagick to VIPS and gotten around 50% speed improvement, with IIRC 30% memory reduction on average.

**Comment by brusch** [comment]
@dkarlovi Actually we had already the same idea and we also did an PoC a couple of years ago, see #969  and https://github.com/pimcore/pimcore/blob/1ce4e02a516439bc9ab3e7ca24b551b458631034/pimcore/lib/Pimcore/Image/Adapter/Vips.php

To be honest, I can't remember why we finally skipped the initiative, but since this is already quite some time ago, I'd give it another try. 

Can you provide a PR for that? 
Actually I'd also consider #2914 here as well, maybe as a separate PR before? Shouldn't be too much effort imho. WDYT?

**Comment by dkarlovi** [comment]
@brusch I think there's quite a bit of progress in the library since 2016.

Looking at your reference to Imagine VIPS implementation, maybe a better approach would be actually to implement an "Imagine Adapter" which could then in turn handle VIPS? It would be a chain of adapters, but allowing for more flexibility.

**Comment by brusch** [comment]
@dkarlovi 
ad php-vips: I'd assume so 😊
implementation: sounds good! Maybe we start with a PoC/draft PR first, there we can discuss details, but so far it sounds like a promising solution to me. 
Maybe this chain shouldn't just consider the available libraries, but also the source and target image format, e.g. even GD is in most cases much faster than Imagick ...

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
