### ISSUE TITLE
Drop Support for Mysqli

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#1236]

**Comment by bbak** [comment]
Are named Parameters such a huge gain, compared to unnamed ones? As PDO is a emulation layer, it has [its drawbacks](http://jpauli.github.io/2014/07/21/php-and-mysql-communication-mysqlnd.html) especially when emulation layer for prepared statements is active (which is the default).

If I had a vote, I'd vote against it.

**Comment by brusch** [comment]
@bbak Thank you very much for sharing your opinion! In some situations, especially when dynamically building conditions it is definitely a huge gain. 

But the emulation layer is a good point, ... :)

**Comment by brusch** [comment]
reverted, see: https://github.com/pimcore/pimcore/commit/bfebc3685e2a611fd545182134b9d30c29d84447

Pimcore continues to support both adapters for now. 
Pimcore 5 is going to use Doctrine DBAL anyway, which supports named parameters for both PDO and Mysqli.

**Comment by solverat** [comment]
+1 for doctrine! :)

**Comment by bbak** [comment]
A bit offtopic ... but, if you're moving to Doctrine anyway, I propose you have a look at a [NestedSet Implementation for Doctrine](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/limitations-and-known-issues.html#nested-set). While NestedSet (also called preorder tree traversal) may be slow in inserting a node in a (huge ! ) tree, it's lightning fast in reading it - basically it's possible to generate the whole tree-structure with one SQL Query - no recursion like in the adjacency List approach or "LIKE" Queries as in materialized path.

We managed trees (using "native" SQL) with several 10k Nodes without any notable slowdown in read speed and inserting nodes was also ok, since there are just some integers to update.
