### ISSUE TITLE
Remove support for old bundle structure

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#12471]
### Improvement description

Follow up to #12356

**Comment by fashxp** [comment]
really? then we would remove the possibility for bundles to support pimcore 10 and 11 in parallel?

**Comment by jdreesen** [comment]
> then we would remove the possibility for bundles to support pimcore 10 and 11 in parallel?

No, because Pimcore v10 will support both, when #12356 gets merged. So they could support Pimcore `^10.5 || ^11.0` by updating to the new structure.

But I wouldn't remove support for the old bundle structure, as it's a rather hard break. Symfony supports both structures, too. Also, as far as I know, the old structure is not deprecated in Symfony, it's only not "best practice" anymore.

**Comment by aryaantony92** [comment]
We decided to keep the support for both the bundle structures (old and modern).
