### ISSUE TITLE
[Task] Move Ecommerce to repository pimcore/ecommerce-bundle

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#12526]
### Improvement description

Move `Ecommerce` to repository `pimcore/ecommerce-bundle`

**Comment by kingjia90** [comment]
Current plan is to first move stuff under the subfolder EcommerceFramework and then on its own repository:

- [x] Move documentation, check if there's any relative urls to Core documentation that will break
- [x] Move tests under bundle folder and add codeception
- [x] Move translations out of the Core, in own directory and json

Once in own repository:
- [ ] Copy all ci related files/scripts eg.`.php-cs-fixer.dist.php`
- [ ] Extract phpstan neon rules related to EcommerceFramework
- [ ] Sync Github stuff like issue template and labels

Feel free to change this comment and add any feedback, as this may be useful for other bundles extraction as well.

**Comment by dvesh3** [comment]
Re-opening as the bundle needs to move into its own repository.

**Comment by ElenAd451** [comment]
As I know, e-commerce is getting pretty popular, and that's why I'm planning to develop my own online store. I've already discovered [https://amasty.com/sap-integration-service.html](https://amasty.com/sap-integration-service.html), and this website has all the necessary extensions, so I believe it won't take me long to develop an attractive and user-friendly store.
