### ISSUE TITLE
[Improvement]: Create reflections helper for testing

### ISSUE THREAD

**Issue by robertSt7** [pimcore/pimcore#12671]
### Improvement description

Create reflections helper for testing private and protected methods and variables
e.g. https://itecnote.com/tecnote/php-best-practices-to-test-protected-methods-with-phpunit/

Create follow up issues for every bundle to refactor tests

**Comment by jdreesen** [comment]
You could use something like [NSA](https://github.com/Nyholm/NSA).

**Comment by herbertroth** [comment]
Testing private and protected methods is generally discouraged because it breaks encapsulation, making tests tightly coupled to specific implementations rather than focusing on behavior. Private methods tend to evolve frequently as the implementation of the class changes over time. They might get split, combined, or even removed. If you have tests for these methods, you’ll have to rewrite or discard them each time they change, which can lead to a lot of unnecessary maintenance work.
