### ISSUE TITLE
[Bug]: Update from 10.4 to 10.5 breaks code if thumbnail does not contain a config

### ISSUE THREAD

**Issue by passioneight** [pimcore/pimcore#12752]
### Expected behavior

Creating a thumbnail without configuration does not lead to an error.

### Actual behavior

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/57256630/180767166-5d3bd746-5c58-4299-86e1-58de76b2aaf3.png">

### Steps to reproduce

1. Create thumbnail without configuration
2. Render thumbnail

Related code:

https://github.com/blankse/pimcore/blob/e72eb19f3332c6a1e2cfbfe236b14dfb5018fe0e/models/Asset/Thumbnail/ImageThumbnailTrait.php#L221

Proposed fix:
```php
if ($thumbnail && array_key_exists('width', $thumbnail) && array_key_exists('height', $thumbnail)) {
    // ...
}
```

**Comment by dvesh3** [comment]
Fixed by #12753

**Comment by kathangeorg** [comment]
I'm not completely sure if this bug is fixed for all conditions or if this is maybe an unrelated problem.

E.g. if I run `bin/console pimcore:search-backend-reindex` I still get an error if no configuration is present (`$this->getConfig()` equals null)

    In ImageThumbnailTrait.php line 193:

    [Error]
    Call to a member function getName() on null

    Exception trace:
    at /app/vendor/pimcore/pimcore/models/Asset/Thumbnail/ImageThumbnailTrait.php:193
    Pimcore\Model\Asset\Image\Thumbnail->readDimensionsFromFile() at 
    /app/vendor/pimcore/pimcore/models/Asset/Thumbnail/ImageThumbnailTrait.php:228
    Pimcore\Model\Asset\Image\Thumbnail->getDimensions() at 
    /app/vendor/pimcore/pimcore/models/Asset/Thumbnail/ImageThumbnailTrait.php:141
    Pimcore\Model\Asset\Image\Thumbnail->getWidth() at 
    /app/vendor/pimcore/pimcore/models/Asset/Image/Thumbnail.php:317
    Pimcore\Model\Asset\Image\Thumbnail->getImageTag() at 
    [...]

because  `$this->getConfig()->getName()` in `$this->readDimensionsFromFile()` does not check if config equals null. `$this->readDimensionsFromFile()` is e.g. called without checking `$this->getConfig()` in line [239](https://github.com/pimcore/pimcore/blob/557b7ebc88de1218918f2cdd1f25a92211b69dad/models/Asset/Thumbnail/ImageThumbnailTrait.php).

Proposed fix:

    $this->getAsset()->getDao()->addToThumbnailCache(
          $(($config = $this->getConfig()) === null ? '' : $config->getName()),
          [...]

**Comment by blankse** [comment]
@kathangeorg I created a PR https://github.com/pimcore/pimcore/pull/12766
Can you test it?
