### ISSUE TITLE
Feature Request: add an upgrade/downgrade method to the plugin interface

### ISSUE THREAD

**Issue by salexfo** [pimcore/pimcore#1303]
## Feature description

It would have been great if we could've upgraded a plugin via the same "extensions" interface we use now to enable/disable it and install/uninstall it.

**Comment by solverat** [comment]
i think that is not gonna happen (soon). You could use some of those migration plugins:

https://github.com/gatherdigitaluk/pimcore-migrations
https://github.com/studioemma/pimcore-plugin-migrations

**Comment by salexfo** [comment]
@solverat thanks.Anyone else?

**Comment by dpfaffenbauer** [comment]
Something similar existed years ago, before pimcore used composer for plugins.

I would fancy a simple and standardized way to update plugins. CoreShop implemented a similar update routine as Pimcore has. But it already requires some code to generate new builds. I think it is very hard for Pimcore to provide an easy standardized way using composer and do migrations. 

An easy way is: check if your requirements are fulfilled, if not -> return false in isInstalled method. On install do your migrations and/or create tables or whatever.

**Comment by salexfo** [comment]
@dpfaffenbauer thanks. What complexity does using composer cause?

**Comment by dpfaffenbauer** [comment]
Migrations ;)

Pimcore's Update mechanism currently works like this: It updates itself from build to build and does migrations if needed. (CoreShop does the same)

If you use composer to get all the changed code, you don't have all this build-stages and migrations could cause problems because there are missing code files.

For example: You wanna update from Build 1 to 5. In Build 3 File Document.php gets deleted but Build 2 needs it. In Pimcore's algorithm, no Problem:

Update to Build 2. Do Migration with Document.php
Update to Build 3: Remove Document.php
Update to Build 4: Nothing (just code changes)
Update to Build 5: Nothing (just code changes)

No, lets do the same with composer updates:

Update: Composer fetches all the needed files for Build 5.
Composer runs some kind of script to do migrations from 1 to 5:

**Update to Build 2: Failure, file Document.php not found!**

**Comment by salexfo** [comment]
@dpfaffenbauer thanks. Got it.

**Comment by brusch** [comment]
Closed in favor of #1539
