### ISSUE TITLE
[Improvement][DataObjects]: Consistent way of storing null/empty textfields to the database

### ISSUE THREAD

**Issue by mcop1** [pimcore/pimcore#13089]
### Improvement description

Empty textfields are stored as `NULL` in the database, when an object gets created. But after editing, saving and removing the value again it will be stored as `''`.

For example: 
1.) Create a new "car"
2.) Use this code to get all cars without description

`$carList = DataObject\Car::getByDescription('', "de");` 

This will result in the following sql:
```
SELECT xxx  FROM object_localized_CAR_de WHERE (`description` = ''  AND  object_localized_CAR_de.o_type IN ('variant','object')) AND object_localized_CAR_de.o_published = 1
```

3.) Check if the newly created car is in the result list
4.) It won´t be, because the description field is set to NULL in the database

5.) Add some text to the description field, save and remove the text again
6.) Description filed in the database then gets set to `''` 
7.) Try the example code from above again, the car should be in the result set now

Noticed during implementation of https://github.com/pimcore/pimcore/pull/13061

**Comment by jremmurd** [comment]
Related to https://github.com/pimcore/pimcore/issues/4369

**Comment by AndrewKMoses** [comment]
We are having issues with this also in the case of using Unique on an attribute. We want to be able to have no value (null) for the attribute on some objects and in those cases we can not update the object after creating it if there are multiple objects with no value for the attribute (because null turns into '' on update).

We had to turn disable the unique check.

**Comment by dkarlovi** [comment]
This seems like a thing which should be solved at client level maybe? The fix in #13760 seems like a direction, but it means it's guessing at what the intent was: API was invoked with an empty string, we know that means `NULL`. Seems messy because what if at some point the empty string needs to be kept as-is?

The client should get to decide when to store with `NULL` and when with an empty string. It should be fixed client-side.

**Comment by mcop1** [comment]
I tried to change the `getDataFromResource` method (because here we can return null according to the return type) to:

`return empty($data) ? null : $data;` 
in
https://github.com/pimcore/pimcore/blob/815ec901d89af3f57f458012993357f269c39eef/models/DataObject/ClassDefinition/Data/Input.php#L126 

Besides that sometimes you may want to save the empty string (like mentioned in the comment above), there is another problem here: 

https://github.com/pimcore/pimcore/blob/4d93f1f93eb8a5544ea4ae8c4345d5fec181b0f3/lib/Model/AbstractModel.php#L187

The `isset` check was introduced with the native types pr, because we can´t set `null` to setter method that don´t allow a null value to be set. 

We could change the setter for inputs in the generated data object classes to something like: 

```
public function setNormalInput(?string $NormalInput): static
{
	$this->NormalInput = empty($NormalInput) ? null : $NormalInput;

	return $this;
}
```
Additionally to that we could add a checkbox in the data object class editor for inputs: `Treat empty strings as null` and generate the setter code based on this option (not shown in the code above).

**Comment by fashxp** [comment]
I would go for @dkarlovi's approach: 
- setting `null` via PHP API setter should set `null`, setting empty string should set empty string to DB
- empty data from admin UI we interpret as `null` (because it is also `null` when data object is created), and for archiving that `getDataFromEditmode` is the right place

we also should add some tests for that
