### ISSUE TITLE
[Improvement]: access the admin API using a JWT instead of the session

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/pimcore#13271]
### Improvement description

Currently, the admin API uses the active session to authenticate the user. This works, but comes with quite some issues:

1. it's stateful, you need a session active for each request
2. since the requests are concurrent, this means session needs locking, it can block requests
3. you also need CSRF tokens to ensure the requests being done were actually meant to be done by the user, [these also produce issues](https://github.com/pimcore/pimcore/issues?q=is%3Aissue+is%3Aopen+csrf)
4. it doesn't take advantage of major improvements in API-specific tech we have since this was a standard

All of this works, but is quite complex and unnecessary: the API endpoints could have a separate firewall which is stateless and JWT based, it would remove all above named issues, simplifying the codebase and regular operations quite a bit in the process.

1. the admin login and current SPA page stay mostly the same
2. we move API controllers to say `/admin/api` and assign a separate firewall to them, JWT based
3. we add a new endpoint which does use the current session+CSRF based solution, it issues a JWT

All the other interactions with the admin API are JWT based. If we allow to decorate the JWT issuer service, we can allow the developer to issue a [Mercure](https://mercure.rocks/)-compatible JWT, meaning the same JWT can the be used by the Pimcore admin to access the web API and the [realtime API](https://github.com/pimcore/pimcore/issues/8537) (done either by the developer or by Pimcore in the future).

**Comment by fashxp** [comment]
Relevant for new API / UI

**Comment by alexz707** [comment]
Hi there,
thank you for the well-thought-out suggestion! You've brought up some valid points about the complexities that come with a stateful session-based approach for the admin API, especially around issues like session locking and CSRF tokens. 

Moving towards a stateless JWT-based solution, as you propose, definitely has its appeal in terms of simplifying the codebase and removing session-related concerns.

However, I wanted to share that in the future, the current admin UI Classic Bundle will be phased out and replaced by our new Studio. While Studio also comes with its own API, we’ve had extensive discussions internally about authentication methods, including JWT. In the end, we opted to continue with a session-based approach instead of JWT for a few key reasons (not limited to):

- Security concerns: JWTs can't be revoked immediately once issued, which means that if a token is hijacked, there's a potential security risk until it expires.

- Complexity: Managing tokens, especially with refresh tokens, adds additional layers of complexity. While JWTs aim for statelessness, using refresh tokens introduces a form of statefulness that we wanted to avoid.

- Parallel usage: One of our goals was to ensure smooth parallel use of both Studio and the Admin UI, and a JWT-based system would have introduced challenges in making that possible.

In the end, the session-based approach came with fewer challenges and felt like the most stable and secure option for our use case. That being said, we always appreciate feedback and are continually revisiting these decisions as technologies and needs evolve.

Thank you again for your input!
Best regards,
 Alex

**Comment by jdreesen** [comment]
One thing I find very annoying is the connection between the admin session and the frontend session, which may lead to e.g. also being logged out from the admin when you log out in the frontend.

I would therefore very much welcome a separation of these concerns.

> Security concerns: JWTs can't be revoked immediately once issued, which means that if a token is hijacked, there's a potential security risk until it expires.

Of course, they can be revoked, see e.g. https://auth0.com/blog/denylist-json-web-token-api-keys/

--- 

For the record: Symfony just added [stateless CSRF protection](https://github.com/symfony/symfony/pull/58095) in `7.2`.

**Comment by dkarlovi** [comment]
IMO keeping the session based auth is a mistake. As @jdreesen points out, your points are not entirely accurate: JWTs can be invalidated by denylisting them.

Your pros for session-based approach don't address the cons in OP, such as session locking which is significantly impacting concurrent API use and very likely to cause issues as Studio grows in features. Also, having dealt with CSRF issues in Pimcore across basically all projects, that too would be a thing of the past.

I strongly believe you should take this new information and reconsider this decision.

**Comment by dkarlovi** [comment]
@alexz707 @fashxp mention for visibility.

**Comment by alexz707** [comment]
Hi!

Thanks for your feedback.

I just want to clarify that my points were just part of our overall decision.

One thing I’d like to mention is that session blocking can actually be managed by using different session handlers, such as Redis or Memcache. These options could effectively mitigate some of the session concerns without adding too much complexity.

Also, if you’re thinking about introducing a blocklist with JWTs, keep in mind that each token check will require a database lookup, which is quite similar to managing sessions in terms of load.

Regarding CSRF protection, we should be good to go with the same-site strict mode, so there’s one less thing to worry about on that front.

Lastly, we are currently evaluating how to separate the admin and frontend sessions, so splitting them up is definitely something we’re working on.

Best,
Alex

**Comment by dkarlovi** [comment]
@alexz707 @fashxp 

> One thing I’d like to mention is that session blocking can actually be managed by using different session handlers, such as Redis or Memcache. These options could effectively mitigate some of the session concerns without adding too much complexity.

From the description, you might be misunderstanding what is meant by session locking: namely, sessions **must** be locked between requests to avoid double write (losing information). Locking is already implemented in Symfony's PDO session handler and both [Memcached and Redis will likely get session locking](https://github.com/symfony/symfony/pull/48588) (which is missing by mistake, note [I'm the contributor of the current Redis session handler to Symfony](https://github.com/symfony/symfony/blob/9b0ca992923f71f5b6e3571d0fdac736902d3d79/src/Symfony/Component/HttpFoundation/Session/Storage/Handler/RedisSessionHandler.php#L21)). The native Redis/Memcached session handlers built into PHP itself already do locking.

To simplify, this means you'll get this:

1. request 1, slow, session locked
2. request 2, fast, tries to lock session, must wait
3. request 1 completes, unlocks session
4. request 2 can now complete, even though it's faster than request 1 and should have been able to run concurrently

> keep in mind that each token check will require a database lookup, which is quite similar to managing sessions in terms of load

That's incorrect and also different: database reads don't lock.

**Comment by alexz707** [comment]
Hi @dkarlovi,

thanks for your explanation.
While JWT has clear benefits for stateless and scalable environments, Pimcore’s current architecture favors session-based authentication to ensure security and immediate session invalidation without complex token management

But we’ll keep JWT’s potential in mind and will reevaluate our strategy as the requirements and use cases evolve.

Best,
Alex
