### ISSUE TITLE
Improvements of newsletter campaigns

### ISSUE THREAD

**Issue by dominikschnieper** [pimcore/pimcore#1332]
## Feature description
We need some improvements of the newsletter document type and i want to ask if i should provide a pullrequest for those. Are there any other ideas for enhancements i can do at the same time?

My improvements are:
- Newsletter should provide a list with recipients to check before sending
- better filtering, depending on recipient-class for instance language dropdown
- href for base path to group object-based recipients
- status to provide different view if newsletter is already sent
- opened date for emails in the "sent emails" table (may be as a global option for all emails)

Thanks for your response

**Comment by fashxp** [comment]
Hi, 
thank you very much for your input. See our comments below: 

- Newsletter should provide a list with recipients to check before sending
> To do this in a generic way is quite difficult since this list could become really large. I would recommend to implement a Custom Address Source Adapter (see [docs at the bottom](https://www.pimcore.org/docs/latest/Documents/Document_Types/Newsletter_Documents.html) and there you can provide a address preview optimized for your use case. 
- better filtering, depending on recipient-class for instance language dropdown
> same here - implement a Custom Address Source Adapter optimized for you needs. 
- href for base path to group object-based recipients
> I'm not sure if I understand you correctly - but wouldn't that also be possible with a Custom Address Source Adapter? :) 
- status to provide different view if newsletter is already sent
> What would that status be and when would it be set? What if, one newsletter is send multiple times to different target groups? So would we need multiple statues? Could we use the notes&events for that information - always add an entry when the newsletter is sent?
- opened date for emails in the "sent emails" table (may be as a global option for all emails)
> what is the opened date?

**Comment by dominikschnieper** [comment]
Hi and thanks for your answer.

Thats correct, we can implement the first 3 improvements with the Custom Address Source Adapter!

Your points about the state are correct, in my opinion a newsletter can only be sent once. If you want to send the same to another group you would copy the newsletter and sent it to those. That would be more clear for statistics and history. But i can set a property with the state and implement the rest in my Address Source Adapter, so if state-property is "sent" the button for sending it again gets disabled in javascript.

We have implemented an "invisible" image with an url e.g. mydomain.ch/newsletter/campaign-3/hashcode-of-emailaddress where we mark the campaign/emailaddress combination as read. So we can check if people are reading the mails (or at least have an idea of it as this is not a hard fact). I can also implement this in a plugin which i already did but it might me interesting for all emails.

**Comment by fashxp** [comment]
Hi, 
thank you very much for your input, we really appreciate it!

Concerning the sending-state - as we want the Pimcore functionality as generic as possible, I think its best to solve that with a plugin (and maybe share it with the community ;-) ). If you need additional events, let us know. 

Analytics of newsletters is a very delicate thing. As you already mentioned, this is not a 'hard fact', but users will see it as such and we are going to have endless discussions about the quality of newsletter tracking - and this will be a real endless story since every email client deals differently with images and so on. 
This is not core competence of Pimcore and therefore we don't want to open this topic up in the core. 
If analytics and delivery quality is important, we recommend to use external services for sending anyway (e.g. mandrill from mail chimp). These services also provide analytics functionality which can be accessed via their API. That information could be retrieved and displayed within Pimcore with another plugin.

**Comment by andres-asm** [comment]
@dominikschnieper I know it's been years, but did you write a plugin to track email opens?

**Comment by dominikschnieper** [comment]
Hi @fr500 nothing to share easily unfortunately.
