### ISSUE TITLE
[Bug]: "Data Object Pool" portal pages not working

### ISSUE THREAD

**Issue by cami0092** [pimcore/pimcore#13320]
### Expected behavior

When I click on "Add page" and "Portal Engine - Data Object Data Pool" I expect to see the configuration page for my data object pool.

### Actual behavior

When I click on "Add page" and "Portal Engine - Data Object Data Pool" I get an error page without further explanation.

### Steps to reproduce

Inside the portal documents right click on "en" then "Add page" and choose "Portal Engine - Data Object Data Pool". Give it a name and try to open it.

<img width="1080" alt="Bildschirmfoto 2022-10-06 um 10 04 54" src="https://user-images.githubusercontent.com/55980768/194255739-688c0cfc-9e93-47dc-887f-2d3718a8d684.png">
<img width="1080" alt="Bildschirmfoto 2022-10-06 um 10 04 46" src="https://user-images.githubusercontent.com/55980768/194255755-a291faee-b858-4a31-b6d0-a2a77b02f13d.png">

**Comment by fashxp** [comment]
This issue is already discussed [here](https://github.com/pimcore/pimcore/discussions/13262) and in the portal-engine repository and will be fixed in 2.4.2 which will be released next wednesday. 

@cami0092  if you don't have already access to the portal-engine repository, please contact [enterprise-support@pimcore.com](mailto:enterprise-support@pimcore.com)
