### ISSUE TITLE
[Bug]: Custom Layout "use as default layout" options not working as expected

### ISSUE THREAD

**Issue by stormwind84** [pimcore/pimcore#13451]
### Expected behavior

Creating a new custom layout and set is as default should open that layout when creating an object. (Pimcore 10.5.8 - live demo)

Possible solution & discussion [here.](https://github.com/pimcore/pimcore/discussions/13448)

### Actual behavior

The master layout is always the default.

### Steps to reproduce

CLASSES > CUSTOM LAYOUT DEFINITION 

Create/edit a custom layout, set is as default; Creating an object will always load the "master" layout.

![immagine](https://user-images.githubusercontent.com/18167362/197785371-4eb67e84-12d4-4000-a2a7-0a3c3a117ede.png)

![immagine](https://user-images.githubusercontent.com/18167362/197789028-00b42422-257f-43a9-ad6e-fe728161026d.png)

**Comment by mattamon** [comment]
So I checked the code and it seems a little overcomplicated. The layout implementations could use a little refactoring.
The main problem is the master layout and the permissions.
The error is caused by this line `$currentLayoutId = $request->get('layoutId', 0)`

If you are an admin user, the master layout will always be a valid layout. 
If you want the admin user to see the default layout you specified, we need to remove the 0 as default param. 

If you are not an admin user, and you do restrict the user, that he can't see the master layout, but do not specify any other layout, the master layout will be used. 
So the question is, what would be expected in such a case? I don't think is a good idea, if you just use the master layout as fallback if the user should not actually have this permission right?

**Comment by stormwind84** [comment]
Hello Mattamon, in our case we just need to set as default a simplified layout of the master (the master is OK to be seen from regular users), but you're right, the solution should effectively cover all scenarios.
