### ISSUE TITLE
[Bug]: no htaccess-file in public-folder

### ISSUE THREAD

**Issue by mediafant** [pimcore/pimcore#13908]
### Expected behavior

Hallo there,

after fresh pimcore-install of 10.5.13 admin didn't work because there is no htaccess-file in public-folder

Cu Andreas

### Actual behavior

that there is htaccess-file

### Steps to reproduce

fresh pimcore install 10.5.13

**Comment by jdreesen** [comment]
How did you install it? 

The `.htaccess` file is not in the [skeleton](https://github.com/pimcore/skeleton/tree/10.2) anymore, because it uses nginx as its web server.

If you want to use Apache instead, you have to copy the file [from the docs](https://pimcore.com/docs/pimcore/current/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Apache_Configuration.html).

**Comment by mediafant** [comment]
Hi,

yes, i copied htaccess from last procect and it works, but I thought it
was an oversight that this file doesn't exist

Andreas

Am Montag, dem 26.12.2022 um 07:21 -0800 schrieb Jacob Dreesen:
> How did you install it?
> The .htaccess file is not in the skeleton anymore, because it uses
> nginx as its web server.
> If you want to use Apache instead, you have to copy the file from the
> docs.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>

-- 
Andreas Wulf
www.mediafant.de
Tel: +49 761 7058605
