### ISSUE TITLE
[Static Routes] load controller from service

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#1405]
_From @dpfaffenbauer on April 4, 2017 16:7_

Is it possible to load controllers as service with Static Routes? If no, is there a plan to do it?

_Copied from original issue: pimcore/pimcore-5-issues#94_

**Comment by brusch** [comment]
@dpfaffenbauer What exactly are you trying to do? Thanks for clarification.

**Comment by dpfaffenbauer** [comment]
Well, I would like to do this (http://symfony.com/doc/current/controller/service.html) with Static Routes. Otherwise I would end up creating custom routing.yml files, but I really love GUIs :D

Btw: Wouldn't it be possible that static routes create a routing.yml file (instead of database entries) and let symfony do all the routing magic?

But as far as it looks right now, I don't think this is supported.

**Comment by brusch** [comment]
This is currently not possible, but should be possible to implement, we put this on our todo list. 
Using a custom `routing.yml` was also our first thought, but unfortunately the standard routes do not cover all possibilities of static routes, especially regarding topics such as optional parts followed by required placeholders, advanced regexes, ... 

But anyway, static routes are not saved in the database, but in `var/config/staticroutes.php` or `app/config/pimcore/staticroutes.php´.

**Comment by dpfaffenbauer** [comment]
Sounds good :)

Oh yeah, did forget about this. They've been stored once in DB, didn't they?

**Comment by brusch** [comment]
Yes, they used to be in the DB ;)
