### ISSUE TITLE
[Bug]: Default values for columns in advanced relations doesn't work

### ISSUE THREAD

**Issue by robertSt7** [pimcore/pimcore#14153]
### Expected behavior

Default values are displayed

### Actual behavior

No default values are displayed

### Steps to reproduce

- Create an advanced relation with default values for columns
- Open it and add  some relations

**Comment by torqdev** [comment]
Hey @robertSt7,

We did this bug fix a while ago, but were told it was an improvement rather than a bug fix. Here are the 2 PR's and original issue:
[Original Issue](https://github.com/pimcore/pimcore/issues/10524)
[10.5](https://github.com/pimcore/pimcore/pull/14178)
[11.x](https://github.com/pimcore/pimcore/pull/14016)

We just opened the fix based off 10.5. Please let us know if you would like us to close the 11.x pull request.

**Comment by robertSt7** [comment]
Hi @torqdev this bug fix only fix it for the bool column. When I try it with Text oder Number the cell is empty

**Comment by robertSt7** [comment]
@torqdev I requested a change to the PR https://github.com/pimcore/pimcore/pull/14178 and then it works for me. Could you please take a look at this? Thanks

Then we can close the PR for 11.x

**Comment by robertSt7** [comment]
fixed by https://github.com/pimcore/pimcore/pull/14178
