### ISSUE TITLE
[Bug]: Calling absolute document URL of Sites should not be possible

### ISSUE THREAD

**Issue by lukmzig** [pimcore/pimcore#14315]
### Expected behavior

It should not be possible to call absolute document URL, only calling site URLs

e.g https://demo.pimcore.com/Classic%20Cars%20Portal should redirect to 404 page or site home page. Calling document directly via absolute URL can cause problems as these requests are not in the site scope. 

### Actual behavior

It is possible to call absolute document URL e.g https://demo.pimcore.com/Classic%20Cars%20Portal which in this case leads to an error and can cause problems for other Sites as well. 

### Steps to reproduce

Call https://demo.pimcore.com/Classic%20Cars%20Portal

**Comment by brusch** [comment]
Actually this wasn't solved yet because of performance reasons. 
We'd need to check on every document request, whether the matching document is located within a site or not, which causes an additional and expensive query on the database.

So practical this would mean calling `\Pimcore\Tool\Frontend::getSiteForDocument()`  here: 
https://github.com/pimcore/pimcore/blob/64aa010225e52196bdb3feddb2b96577f3bbe88a/lib/Routing/Dynamic/DocumentRouteHandler.php#L106

Maybe implementing an additional cache along to the runtime cache in `\Pimcore\Tool\Frontend::getSiteForDocument()` where we cache an array of siteId => path or so could improve performance and would make it possible without having a huge performance impact. 

With that approach we'd just need to iterate over the cached array, which would be cheap in terms of computing power.

**Comment by brusch** [comment]
Additionally I'd put the whole logic into a new method called `\Pimcore\Tool\Frontend::getSiteIdForDocument()` which can then be used by `\Pimcore\Tool\Frontend::getSiteForDocument()` as well, but we don't need to obtain the Site object then, we can just return the ID that we have already in our cached array.
