### ISSUE TITLE
Use symfony/rate-limiter for login/password reset

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#14409]
### Improvement description

The old custom BruteforceProtectionHandler was removed by #13367 but it seems symfony/rate-limiter wasn't implemented as the replacement. 

Additionally only the password reset should be protected by the rate-limiter.

**Comment by jdreesen** [comment]
Why only password reset? Shouldn't we also limit the login attempts?

**Comment by dvesh3** [comment]
Login attempts are already limited with Login Throttling from Symfony. please see https://github.com/pimcore/demo/blob/11.x/config/packages/security.yaml#L31-L33

**Comment by kingjia90** [comment]
Closing as it is fixed in a conflict merging follow-up https://github.com/pimcore/pimcore/commit/b9aa97ad9c1b7576feb17947de9022cd46a977b8#diff-6093a930b60f02fd7a3eaf9cb52077083967ce2e85e7046ea2efca5865a1fa91
Test would be valid, see also https://github.com/pimcore/pimcore/pull/14528

There some changes that got removed in https://github.com/pimcore/pimcore/commit/93180208ac4c8de8b8e4cf0203d9ca20251a01e5 while instead it should have removed the `bruteforceProtectionHandler` part of the BC layer. 

Please considering this removal as part of https://github.com/pimcore/pimcore/pull/13367 but "without the right timeline"
