### ISSUE TITLE
[Bug]: Bad example for restricting public asset access in the docs

### ISSUE THREAD

**Issue by jdreesen** [pimcore/pimcore#14458]
### Expected behavior

The example for restricting public asset access doesn't use code from Symfony that [*should not* be used at runtime, as it's **slow**](https://github.com/fabpot/symfony/blob/5.4/src/Symfony/Component/Routing/RouterInterface.php#L29-L30).

### Actual behavior

The docs for [restricting public asset access](https://pimcore.com/docs/pimcore/current/Development_Documentation/Assets/Restricting_Public_Asset_Access.html) use [`Symfony\Component\Routing\RouterInterface::getRouteCollection()`](https://github.com/fabpot/symfony/blob/5.4/src/Symfony/Component/Routing/RouterInterface.php#L29-L30) inside a controller (at runtime).

### Steps to reproduce

I don't fully understand [what's going on there](https://github.com/pimcore/pimcore/blob/10.5/doc/Development_Documentation/04_Assets/07_Restricting_Public_Asset_Access.md?plain=1#L166-L170), but I don't think we should propose this, when Symfony explicitly warns that it's **slow**.

**Comment by kingjia90** [comment]
It seems it gets the \Routing\Route with the following name
https://github.com/pimcore/pimcore/blob/b337612ff0adcae8d48d7d185a21bd6bd72c9741/bundles/CoreBundle/Resources/config/routing.yml#L17-L25
and creates a new RouteCollection with only that route in it, because the UrlMatcher first parameter requires a RouteCollection.

Probably to avoid the need of creating a new Route with hardcoded `requirements` (see the routing.yml above) which are then used to extract the  [$parameters](https://github.com/pimcore/pimcore/blob/b337612ff0adcae8d48d7d185a21bd6bd72c9741/doc/Development_Documentation/04_Assets/07_Restricting_Public_Asset_Access.md?plain=1#LL174) that get forwarded.

Maybe could use this static method instead https://github.com/pimcore/pimcore/pull/14155/files?w=1#diff-fd51b37126eb63374242a3788ce8cb52ae243560ab4e55e9a296ac0582a59e65R614-R638, but unfortunately is still hardcoded and for 11.x. However, if there's a way that the route is cached, then would be nice to change the other PR as well.

**Comment by mattamon** [comment]
@jdreesen #14155 changed the docs at least for 11.x like @kingjia90 mentioned.
Should we close this issue, since there won't be an easy fix for 10.x?

**Comment by jdreesen** [comment]
Yes, that's fine for me.

**Comment by mattamon** [comment]
Thank you! Fixed for 11.x in #14155

**Comment by jdreesen** [comment]
Thank you for the quick fix! :)
