### ISSUE TITLE
Feature request: Element keys - translate special characters

### ISSUE THREAD

**Issue by dweichselbaum** [pimcore/pimcore#1451]
# Feature Request
Add translation table into Pimcore\Model\Element\Service::getValidKey()  in order to get correct translation of special characters. 

## Feature description 
Example: When creating a new document, the letter "ö" in the field "key" will be translated to "o", which is wrong. It should be "oe". This has great influence on SEO, as the wrong "o" will be in the URL as well (eg the brand Schöffl would be /schoffl which is wrong. It would be nice if the system would automatically translate it to /schoeffl instead

**Comment by brusch** [comment]
### Short Answer
This feature is already there. 

### Long Answer 
Transliteration is a quite complex topic which is already implemented quite extensivley in Pimcore, supporting every major alphabet as well as almost every relevant language by utilizing millons of mappings (https://github.com/pimcore/pimcore/tree/2338e6f7d61b36bdbaa98d3623fe621880c94544/pimcore/lib/Pimcore/Tool/Transliteration/Data). 

By definition transliteration is depending on the source language, that means that: 
English: `üäö` => `uaö`
German: `üäö` => `ueaeoe`
Danish: `üäö` => `uao`

In Pimcore the source language is taken from the current logged in user, which can be configured in the users settings: 
![image](https://cloud.githubusercontent.com/assets/142037/25475152/1c270df6-2b36-11e7-8f78-586e2d4b01ee.png)

So in your particular case, you were using a user with the language setting *English*, by using *German* you'd see the expected behavior.
