### ISSUE TITLE
[Improvement]: Unify date/time formats in UI

### ISSUE THREAD

**Issue by mattamon** [pimcore/pimcore#14658]
### Current situation

Atm we are using different date/time formats across the UI, mixing between 12h/24h formats e.g.

ApplicationLogger time format is language specific - tooltips are not. Trying to enter 12h format in e.g., german UI won't work even though the tooltip says so. Tooltip also is English only atm.

Scheduler in documents using only 24h format - tooltip says differently.

### Improvement description
Make date/time formats consistent across the whole UI

- https://github.com/pimcore/pimcore/issues/12436

**Comment by mattamon** [comment]
Timezone improvement #12436

**Comment by robertSt7** [comment]
also see https://github.com/pimcore/admin-ui-classic-bundle/pull/466

**Comment by kingjia90** [comment]
Resolving the reported cases by https://github.com/pimcore/admin-ui-classic-bundle/pull/534 and https://github.com/pimcore/pimcore/pull/17067 as bugfix.

Working on a global refactoring improvement to allow a user setting to define the locale and change all the formats to it, so that eg. an american user can easily switch everything to `m/d/Y` and `0-12` AM/PM, the current issue would be the reference for this on making everything consistent and customizable on user basis

**Comment by kingjia90** [comment]
Update: we would display using the Intl.DateTimeFormat and keep the UI fields as ISO for the moment


~Blocked~: I've tried to use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat by passing the coutry iso code (eg. `en-US`) from an user profile settings's dropdown and would work but it's one-way-ish, there are no tools to extract the format (if is d-m-y, m-d-y, d.m.y or so) to be used eg. in https://github.com/pimcore/pimcore/pull/17067, so might need something like a library 🤔 

~What about MomentJS ? then could access to the date format by [this](https://momentjs.com/docs/#/i18n/locale-data/ 
https://stackoverflow.com/a/53211160 ) method~ better not adding extra libraries

**Comment by kingjia90** [comment]
Resolved by https://github.com/pimcore/pimcore/pull/17137 and https://github.com/pimcore/admin-ui-classic-bundle/pull/554
