### ISSUE TITLE
[Bug]: Reprocess failed page count can cause potential endlessloop

### ISSUE THREAD

**Issue by mattamon** [pimcore/pimcore#14686]
### Expected behavior

If processing page count fails, it should not be processed a second time

### Actual behavior

Failed documents now also get processed again, causing a potential endless loop

Regression  of https://github.com/pimcore/pimcore/pull/14349/files#diff-00881ca8531e9aa6a80427bb435b7fdf2e2e098b0db16b45700c77f4791b1f90R100

### Steps to reproduce

Try to generate PDF with a failed page count

**Comment by dvesh3** [comment]
How about we introduce a failed transport like explained [here](https://symfony.com/doc/current/messenger.html#saving-retrying-failed-messages) ? and then you would have to use `messenger:consume pimcore_failed` for failed messages after fixing the dependency.

**Comment by fashxp** [comment]
But then you still don't have the information available on application side to prevent generating new messages again and again.
Somehow we need to mark an asset as failed and don't restart calculation for it anymore...

**Comment by dvesh3** [comment]
I'm thinking of throwing [UnrecoverableMessageHandlingException](https://symfony.com/doc/current/messenger.html#avoiding-retrying) from AssetUpdateTasksHanlder when asset `document_page_count` has failed status so that it goes into failed transport. With failed transport, you have the control to fix the underlying issue and run the failed transport to process these messages again. 

We'll revert this [line](https://github.com/pimcore/pimcore/pull/14349/files#diff-00881ca8531e9aa6a80427bb435b7fdf2e2e098b0db16b45700c77f4791b1f90R100) as well, which is leading to endless loop.

**Comment by brusch** [comment]
I think we still need to save the status somehow on the asset ... similar what we do with the video conversion status (custom settings). WDYT?

**Comment by mattamon** [comment]
@brusch `document_page_count` is a custom setting and will be set to failed here:
https://github.com/pimcore/pimcore/blob/10.5/models/Asset/Document.php#L70

**Comment by mattamon** [comment]
Fixed by #14740

**Comment by cancan101** [comment]
How was the endless loop happening? I assume that once the message processes it won't process again. Why the need for the explicit error?

**Comment by fashxp** [comment]
I'm not sure anymore. 
I think the messages are triggered from the application somewhere. So it was not the case, that one and the same message got processed multiple times, but that new messages were triggered as long as the page count was not set - but it got never set because the calculation failed.

**Comment by cancan101** [comment]
> but it got never set because the calculation failed.

right, but why did we need to raise an exception from the message handler? I believe that would cause the Symfony queue system to retry (a fixed number of times) rather than ignoring the failure and not retrying
