### ISSUE TITLE
[Bug]: Exception in version preview after convert relation to advanced

### ISSUE THREAD

**Issue by so-unity** [pimcore/pimcore#14707]
### Expected behavior

Version preview is visible.

### Actual behavior

Exception:

`An exception has been thrown during the rendering of a template ("Call to undefined method getObject in class Pimcore\Model\DataObject\Item").`

`in vendor/pimcore/pimcore/bundles/AdminBundle/templates/admin/data_object/data_object/preview_version.html.twig&line=170#line170 (line 170)`

### Steps to reproduce

1. Create classes `Example` and `Item`
2. In class `Example` add field of type `Many-To-Many Object Relation` and name it `items`
3. Create object `item1`
4. Create object `example1` and add `item1` to relation field `items`
5. Save object `example1` - new version has been created and looks ok
---
6. Convert field `items` to `Advanced Many-To-Many Object Relation`
---
7. Version that previously looked fine, now is throwing exception when trying to preview

**Comment by martineiber** [comment]
Hey @so-unity ,

In which version of Pimcore does this error occur?

**Comment by so-unity** [comment]
> In which version of Pimcore does this error occur?

10.5.16

**Comment by kingjia90** [comment]
I've fixed the error message by https://github.com/pimcore/pimcore/pull/17322 
If i didn't miss anything, the versions are always compared against the [latest](https://github.com/pimcore/admin-ui-classic-bundle/blob/45762dfd0498234b0be12ecdcfbad21673536ca7/templates/admin/data_object/data_object/preview_version.html.twig#L11) field definition of the given class and therefore it could led to incompatibilities when switching from one type to another as described above.
In other words, the historical data would be now just displayed as empty because we don't know anymore what is the exact type (and related settings) was at the time.

Unless we save every "past" field definitions of a given class and associate it with every version or save it serialized within the version itself (which could increase its size though), there are no ways to recover that past info, other than manually replicate the definition setting it was on save back in the time.

In the given example converting from `many to many object` to `advanced many to many object` sound so close and "similar", but they are quite different under the hood.  Similar issues/errors would appear by converting any existing field into any other type, as string,date, etc...
