### ISSUE TITLE
[Bug]: Many-To-Many relations without possibility to add many object classes to relation

### ISSUE THREAD

**Issue by MaxSien** [pimcore/pimcore#14723]
### Expected behavior

Possibility to add many object classes in Advanced Many-To-Many Relation

### Actual behavior

No possibility to add many object relations in advanced Many-To-Many relation in object classes

### Steps to reproduce

1. Add Advanced Many-To-Many in any object class
2. Try to add more than one object class in 'Allowed Class' field

**Comment by martineiber** [comment]
Hey @sienkii 

In which version exactly does this error occur?

**Comment by MaxSien** [comment]
Hey @martineiber 

I've checked the bug on versions 10.3.2 and higher

**Comment by robertSt7** [comment]
@MaxSien Hi, unfortunately I am not able to reproduce the Bug. Could you please try it on our [public demo](https://demo.pimcore.fun/admin/login?perspective=) and export and provide the class definition. Thanks

**Comment by MaxSien** [comment]
Sure, I'll do it later today

**Comment by MaxSien** [comment]
Hi @robertSt7, i'm sorry for such a late response, but i had some health issues. 

https://drive.google.com/drive/folders/1OWXGfYWWbtw_ZvN1U36TXgyoko5X0mY5?usp=sharing
(i had to upload it into cloud since comments do not support json files)

**Comment by robertSt7** [comment]
@MaxSien Hi, thanks now I got it. But you are just allowed to select one class in the Advanced Many-To-Many Object Relation, because otherwise there would be entries in Visible Fields that are not from every selected class. If you want to select more classes please use Many-To-Many Object Relation. 
I am currently investigating the bug in the Many-To-Many Object Relation.
