### ISSUE TITLE
[PIMCORE5] Disabling deleted bundle from extension manager throws exception

### ISSUE THREAD

**Issue by maff** [pimcore/pimcore#1479]
* Create a Pimcore bundle in `src/`
* Enable the bundle
* Delete the bundle directory
* Try to reload the extension manager and/or disable the bundle

The EM tries to load data from the active bundle, but throws an exception as the bundle class is not found. Treat non-existing bundles as not active, no matter what's configured in the config file.

**Comment by anupam1501** [comment]
Hello @maff 
I am also facing the same issue. The problem is that the EM is loading the bundle list from */var/config/extensions.php* file. 
When we delete a bundle manually or disable it from EM. It doesn't disable the bundle entry as "FALSE" in the "extensions.php" file and this throws missing bundle exception. 
We need to either manually  or automatically remove or disable it in "extensions.php" file(if we are allowed to do so) in order to prevent exception.
Let me know if there is any other way to prevent exception.

**Comment by maff** [comment]
@anupam1501 Enabling/disabling should work fine as long as the bundle class is available, but fails when the bundle does not exist anymore (e.g. when deleted). We will change this to a way that the EM does not rely on a bundle class on disable.
