### ISSUE TITLE
Check if `SystemConfig::getConfigDataByKey()` is really necessary

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#15035]
### Improvement description

This function adds `writeable` attribute to the config, but it seems that this isn't used anywhere. 
If it gets really used, we should think of calling this directly on the repo where this info is needed. 

https://github.com/pimcore/pimcore/blob/cf8dee882824803cab7c5510584ca906486b8051/lib/Helper/SystemConfig.php#L33

**Comment by lukmzig** [comment]
This is currently used in the controller for both system settings and admin system settings (controller was exported to the admin UI classic bundle)
https://github.com/pimcore/admin-ui-classic-bundle/blob/1.x/src/Controller/Admin/SettingsController.php#L407
https://github.com/pimcore/admin-ui-classic-bundle/blob/1.x/src/Controller/Admin/SettingsController.php#L382 (here we pass the whole array so parsing is done then in JS)

Since its used the same way in both configs we decided to use it in the helper and not in the configs directly
