### ISSUE TITLE
[Bug]: Website Settings value get html encoded

### ISSUE THREAD

**Issue by hethehe** [pimcore/pimcore#15101]
### Pimcore version

10.5.21

### Steps to reproduce

Create a website setting and add an value with special symbols (e.g. a json string: {"key": "value"})

### Expected / actual behavior

Actual behavior: 
The value get html encoded and the json string is invalid:
`{"key": "value"} get replaced/encoded with {&quot;key&quot;: &quot;value&quot;}`

**Comment by brusch** [comment]
Caused by #14957 
see: https://github.com/pimcore/pimcore/blob/dc2fd082d2e235dfd3692fe002066238a78b7216/models/WebsiteSetting.php#L187 

@Corepex we can't do escaping on server side, it needs to be done this way: 
https://github.com/pimcore/pimcore/blob/bc7d4771194da9b1ae6258375985e065c62fbc14/bundles/SeoBundle/public/js/seopanel.js#L80

So basically escaping them while rendering. 

so we need to revert #14957 

Please also check if we did this somewhere else as well, I'm afraid this is the case .... 
same here: 
https://github.com/pimcore/pimcore/blob/7d2c25879e9e3cd70dbc440923cc4e82737ea086/bundles/StaticRoutesBundle/src/Model/Staticroute.php#L255

So I'm afraid pretty much everywhere where we use `SecurityHelper::convertHtmlSpecialChars()`. 
Most of the stuff is using the ExtJS grid in the frontend, so using `renderer: Ext.util.Format.htmlEncode` should fix it.

**Comment by brusch** [comment]
this needs to be fixed here as well: https://github.com/pimcore/admin-ui-classic-bundle

**Comment by blankse** [comment]
Milestone should be 10.5.22

**Comment by Corepex** [comment]
> Milestone should be 10.5.22

Correct thx. Changed the milestone to 10.5.22.
