### ISSUE TITLE
[Bug][Pimcore 11] User cannot update own password

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#15180]
### Pimcore version

11

### Steps to reproduce

- Create user
- Login as that user 
- Try to update password 

either it says 

![image](https://github.com/pimcore/pimcore/assets/8792145/e5b89a6c-a4e4-4337-bcbb-bcde5b5a0649)

or it says

![image](https://github.com/pimcore/pimcore/assets/8792145/6120a5f0-c0b4-49aa-b9b6-6332e7d4ccdb)

**Comment by martineiber** [comment]
I have tested this on 11.x-dev and on 11.x-RC1 and it worked on both for me. 

The only thing I have noticed, when the new password is too weak (less then 10 chars) or the Retype of the password dose not match it says `Password wasn't changed because it isn't secure enough` and also `Saved successfully` This should be changed to an better Error message, and an better frontend validation. 

But if all credentials match, the change of the password worked and I could login with the new password.

**Comment by fashxp** [comment]
Ok, but what if I don't know my old password, because I logged in via password-forgotten link or via invitation link? 
Then I cannot change my password. 

Besides that, the error message for the case that the old password didn't match should be more precise.

**Comment by fashxp** [comment]
ok, there is the thing: 

in Pimcore 10 when coming via password forgotten link, the user profile page for changing password looks like this: 
![image](https://github.com/pimcore/pimcore/assets/8792145/74fb151b-b4ec-4b9a-b354-c8180453c876)

so no need to enter old password.
