### ISSUE TITLE
[Bug]: MUST recompile PHP with a larger value of FD_SETSIZE

### ISSUE THREAD

**Issue by felixflor-twocream** [pimcore/pimcore#15274]
### Pimcore version

10.x

### Steps to reproduce

Since Update to Pimcore 10 we've got some errors, that the ULIMIT is reached for open files. So we increase the ULIMIT and after that we got another error, what is the problem itself. 

Message:
```
E_WARNING: stream_select(): You MUST recompile PHP with a larger value of FD_SETSIZE. 
It is set to 1024, but you have descriptors numbered at least as high as 5528. 
--enable-fd-setsize=6144 is recommended, but you may want to set it 
to equal the maximum number of open files supported by your system, in 
order to avoid seeing this error again at a later date.
```

We got a lot of this messages with different proposals sizes. 

The problem occurs as soon as thumbnails are generated with the command (pimcore:thumbnails:image) and they are a huge amount of Image Assets (e.g. 9099 Image Assets (27 Thumbnail Definitions = 245673 generated Thumbnails).

The Problem is, that in symfony write method the "stream_select" is used with an 0 as fourth Parameter. 
```
// vendor/symfony/process/Pipes/AbstractPipes.php
protected function write(): ?array
}
     ...
     // Row 124
     if (false === @stream_select($r, $w, $e, 0, 0)) {
         return null;
     }
     ...
}
```

In PHP Documentation [stream_select](https://www.php.net/manual/en/function.stream-select.php) is using this dangerous if you used it a loop. 

```
... it is NOT a good idea to use a 0 timeout value in a loop as it will cause 
your script to consume too much CPU time.
```

**Comment by jdreesen** [comment]
So this should be reported to Smyfony then, right?

**Comment by felixflor-twocream** [comment]
@jdreesen Don't know. Symfony don't use it in a loop. Pimcore does it. Maybe we have to use it other way or Symfony should be make it changeable by parameters. What do you think?

**Comment by jdreesen** [comment]
I see. I thought Symfony already uses it in a loop.

**Comment by dvesh3** [comment]
@felixflor-twocream could you please confirm if you are using `processes` option on `pimcore:thumbnails:image` command? It might be a parallelization topic to debug.

**Comment by felixflor-twocream** [comment]
@dvesh3 we got the error also when we use messenger:consume. Here the Server-Arguments: ["PATH/bin/console", "messenger:consume", "pimcore_core", "pimcore_maintenance", "pimcore_image_optimize", "pimcore_index_queues", "pimcore_data_import", "--time-limit=300", "-q"]

**Comment by robertSt7** [comment]
@felixflor-twocream The loop, which calls the `write` function from symfony is in `Webmozarts\Console\Parallelization\ProcessLauncher->run()`, so I think we can't fix this in Pimcore. What is your opinion on this?

**Comment by jdreesen** [comment]
Then let's fix it in https://github.com/webmozarts/console-parallelization/, I'd say.

**Comment by felixflor-twocream** [comment]
@jdreesen We've checked it an yes, it is an Symfony Bug. So we close this Issue! Thanks for your help 🙏😊

**Comment by jdreesen** [comment]
Could you please post any related issues/PRs from symonfy / webmozart here?

**Comment by skoch-twocream** [comment]
Hi all, I just want to share my status with you quickly. We were also able to identify that the issue is with fopen inside "league/flysystem" and Pimcore. We are still evaluating the data in more detail and checking which places are really responsible for this.

If you access the file name it seems that the file stream is not closed with fclose (just a guess at the moment):
https://github.com/pimcore/pimcore/blob/8dfdbce7be25ffd96142d5dd268cf649b2d965aa/models/Asset/Thumbnail/ImageThumbnailTrait.php#L318
https://github.com/pimcore/pimcore/blob/8dfdbce7be25ffd96142d5dd268cf649b2d965aa/models/Asset/Thumbnail/ImageThumbnailTrait.php#L90
https://github.com/thephpleague/flysystem/blob/3.x/src/Filesystem.php#L80
https://github.com/thephpleague/flysystem/blob/3.x/src/Local/LocalFilesystemAdapter.php#L287
https://github.com/pimcore/pimcore/blob/8dfdbce7be25ffd96142d5dd268cf649b2d965aa/lib/Helper/TemporaryFileHelperTrait.php#L35

With blackfire, we see that significantly more data is opened than closed:
![image](https://github.com/pimcore/pimcore/assets/54348050/2ca6d59d-50c8-4282-867c-b6443151c756)

Small part of the fopen trace:
![image](https://github.com/pimcore/pimcore/assets/54348050/ee1e1d31-55dd-4a78-84c3-ed9f15c41094)
![image](https://github.com/pimcore/pimcore/assets/54348050/8b86aadb-9938-4a78-a1c4-1c931d450e2e)

Best regards
Sebastian

**Comment by robertSt7** [comment]
@skochTC Thanks for your contribution. Normally we won't have a discussion on closed issues. Could you please create an issue for that, where we can discuss this? Thanks

**Comment by skoch-twocream** [comment]
> @skochTC Thanks for your contribution. Normally we won't have a discussion on closed issues. Could you please create an issue for that, where we can discuss this? Thanks

That was directly related to this issue and it's annoying to be going through multiple issues for one bug in case a third person is also looking for it in a couple of weeks and searching for entry points ;-)

However, I actually also didn't notice that the ticket was already closed. Sorry!

If we find the bug in the Pimcore core and solve it, I will be happy to create a new issue and create a PR for it.
