### ISSUE TITLE
[Bug]: Removing system language does not update the DB properly

### ISSUE THREAD

**Issue by tommasoladinikumbe** [pimcore/pimcore#15283]
### Pimcore version

11.0

### Steps to reproduce

- Delete a language from System Settings
- show DB tables

### Expected / actual behavior

Expected behaviour: object_localized_#_LANGUAGE should be deleted
Actual behaviour: object_localized_#_LANGUAGE is still there

This cause problem while executing DB dumps.

**Comment by brusch** [comment]
Views are removed here: 
https://github.com/pimcore/pimcore/blob/bbcc422de55bba2a4f83e4c07cfbd6ca5f6a2b5e/lib/Maintenance/Tasks/DbCleanupBrokenViewsTask.php#L49 

This needs to be done on a regular basis anyway (maintenance) because you can change the languages also via Symfony config, e.g. on deployment, not just using the UI.

**Comment by mcop1** [comment]
Create a command that does 2 things:

1.) dry-run: Gets the system languages and check if there are any db tables/views/... that can be deleted (e.g. tables belonging to a language that doesn´t exist anymore). Print a report to the user.
2.) run: Deletes the actual tables/views/...

**Comment by robertSt7** [comment]
@tommasoladinikumbe Hi, does this https://github.com/pimcore/pimcore/pull/4612 fix your problem?

**Comment by tommasoladinikumbe** [comment]
> @tommasoladinikumbe Hi, does this #4612 fix your problem?

Hi @robertSt7, the command seems to solve the problem, it removes unused tables and views.
I only had to change the removed "fetchAll" method from Doctrine\DBAL\Connection to "fetchAllAssociative".
