### ISSUE TITLE
[Improvement]: Resolve Dependencies via Messenger

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#15426]
### Improvement description

Ideally there is a way how we can make this feature optional.

**Comment by kingjia90** [comment]
unlinking the composer.json dependencies PR, as here is referring to the Dependencies tab (Requires/Required By)

**Comment by kingjia90** [comment]
After a quick look, concluding that it could be made optional, but, beside it's read-only info utility in a tab, it is mostly relevant on element delete in the UI
https://github.com/pimcore/admin-ui-classic-bundle/blob/ba6a4c1df13b1c30e4538e3885747ac48e993163/public/js/pimcore/elementservice.js#L91
to warn about the dependent elements that would be affected by this action. 

I guess it was not done on-the-fly because it could be slow to process all the children (eg. when deleting a folder with many items and only one of  them has relevant dependencies).

**Comment by brusch** [comment]
@kingjia90 thanks for checking 👍 
To me this sounds like a huge computing effort for very low benefit 🤔 
Personally, I'd make this feature optional via config and turn it off by default - or even extract it into it's own bundle. 
WDYT?

**Comment by kingjia90** [comment]
In either cases of config or own bundle, it seems something for a major release to be turned off by default. 


Found other places it might be required and used, which are:

-the `📄 > Search & Replace Assignment`, https://github.com/pimcore/admin-ui-classic-bundle/blob/fed32936245ab3bd1baa9ac788a096baa6bf8681/src/Controller/Admin/ElementController.php#L333-L475 (not sure how much frequently it's used, never saw a PR or bug reported about this, which is too good to be true, and latest changes before the 11 native types refactor are from Pimcore 6.9 )
- in the Admin ui bundle, beside the tabs with the grid required by/requires, also in Pimcore Translation [context export](https://github.com/pimcore/admin-ui-classic-bundle/blob/9e9ce75c0f4d8ff6db591b1bf6539dac930f6d87/src/Controller/Admin/TranslationController.php#L764)
-  a clean up tool in the e-commerce of ["zombie" order items](https://github.com/pimcore/ecommerce-framework-bundle/blob/77dd0fc7f2f0e5562acc04ade90535c77123cbe9/src/OrderManager/V7/OrderManager.php#L645-L646) that are not used(required by) anywhere.

**Comment by brusch** [comment]
From a semantical point of view it should be even safe to turn it off by default, because `Pimcore\Model\Dependency` is marked as `@internal`, so we can change the behavior (e.g. throwing an exception when using it although it's disabled). 
Not having the information in the UI is imho not really a breaking change, so would be fine for a minor release. 
But yes, we need to ensure that the system itself continues to work or doesn't break any existing code. 

So it seems it's really just used for UI specific stuff and there I would be fine with having this optional, only when this feature is enabled.

**Comment by markus-moser** [comment]
* Disabling the dependencies by default in a minor version is not a good idea (too risky)
* Instead we should do it in multiple steps:
   - [x] Start with implementing the dependencies as message handlers. Executing them via sync transport by default (so nothing in the behaviour should change by default).
   - [x] If someone prefers to do it asynchronously it would be possible to change the routing of the dependencies message to a async queue.
   - [x] Add a config option to disable the dependencies Tab in the UI
   - [x] Add a way to disable the default message handler (when disabled the dependencies table will not be written anymore). Depending on the choosen approach maybe the same option like for the UI could be used. 
   - [ ] For the actual read and write processes of the dependencies we should implement a adapter approach so that by default the dependencies are stored in the dependencies table but for example could be replaced by a OpenSearch alternative (e.g. in the generic data index bundle) https://github.com/pimcore/pimcore/issues/17188

**Comment by dpfaffenbauer** [comment]
why would you wanna remove that feature?

**Comment by markus-moser** [comment]
> why would you wanna remove that feature?

It's a performance bottleneck in some systems and the feedback from a lot of people is that they do not really use it. In my opinion it is a very important feature and we should not remove it but make it more flexible.

**Comment by dpfaffenbauer** [comment]
@markus-moser agree
