### ISSUE TITLE
[Feature]: Add an option to automatically refresh Data Objects on save

### ISSUE THREAD

**Issue by Navino16** [pimcore/pimcore#15455]
### Feature description

When you have an event listener that modify your object data on save (before or after save), some values displayed in Pimcore can be out of sync with what is in the database and you have to manually reload your object to fix that.

Adding an option to allow Data Objects to be automatically reloaded after a save will fix this issue.
You can add this option on the General Settings tab of the class to avoid reloading Data Objects that doesn't need a refresh.

**Comment by passioneight** [comment]
@Navino16 I'd love to see this feature as well. Though, I'm wondering if you could elaborate on the use case(s) that require the feature to be turned off? Because, to me, it feels like the frontend should always refresh the data if it was changed server-side.

**Comment by Navino16** [comment]
@passioneight for example, when you don't have any event listener on your object or your event listener doesn't edit your object then you can be sure that the frontend is still correct.

Having the possibility to enable that feature on each Class individually can also limit performance (usless requests) issue with refreshing objects that doen't need that refresh

**Comment by passioneight** [comment]
@Navino16 I see, thanks for the clarification. If I understood correctly, you'd expect the object to be reloaded using an additional request (i.e., polling), yes? That means, there is a time gap between the update and the actual reload (as to avoid spamming the server). If the user were to save within this time window (which is usually around a few seconds), the data would still be lost - here's an example:

1. The user opens an object of type, say, `Product`.
2. Some cron job (or maybe a migration) updates the product and saves it.
3. The user saves the product without any other interaction.
4. The updated data of step 2 is lost to the user's save in step 3, because the polling happened to need a bite more time to send a request.

So, I wonder, wouldn't you prefer consistent behaviour instead of having the data lost occasionally (due to unfortunate timing) only?

Additionally, the polling requests would imply an explicit reload of the product (i.e., visible to the user). Which can lead to quite bad UX if there's a lot going on in the background (i.e., the object might reload a lot).

So, personally, I favour a solution that uses SSE (e.g., via [Mercure](https://symfony.com/doc/current/mercure.html)) or [web sockets](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API), so there is no need to reload the object _at all_. Instead, Pimcore's UI should become collaborative.

Wdyt? :-)

**Comment by Navino16** [comment]
@passioneight I was considering doing a refresh only after a user save.

But your solution is way better and way more user friendly.
One small point with your solution:
We need to implement some kind of security because if a user is currently editing the product and this "refresh" erase some modifications made by the user it will also result on data lost and bad UX

**Comment by passioneight** [comment]
@Navino16 yes, it would indeed need some kind of merge. I imagine drafts can already handle this, as they should only apply the latest changes of the user on top of the refreshed data. So, we would need to make sure the merging logic works even with the drafts turned off :-)

**Comment by solverat** [comment]
Imagine a modern backend with two-way binding! 🤯

OMG, did i just say "react"?

**Comment by NiklasBr** [comment]
Similar as #4678?

**Comment by Navino16** [comment]
Yes, closing this one then

**Comment by cancan101** [comment]
We inject this code:
```js
document.addEventListener(pimcore.events.postSaveObject, (e) => {
    if (e.detail.task === 'autoSave') {
        return;
    }

    const object = e.detail.object;

    var class_name = object.data.general.className;
    // specify the classes that you want to reload
    if (class_name == 'product' || class_name == 'item') {
        object.reload();
    }
})
```
