### ISSUE TITLE
Ease migration to Pimcore 5: Class import should create object_collection_* tables

### ISSUE THREAD

**Issue by jbq** [pimcore/pimcore#1559]
## Context

- Export classes containing field collections with `Object` > `Bulk Export` on a Pimcore v4 instance 1, downloads file `bulk_export.json`
- Choose `Object` > `Bulk Import` on another Pimcore v5 instance, choose `bulk_export.json`

## Expected behavior

I expect to be able to inject the data-only SQL dump from version 4 into version 5, of `object*` tables.
  
## Actual behavior  

Table `object_collection_*` do not exist.  I have to issue `CREATE TABLE` for every field collection.
  
Would be nice to consider this issue to ease v4 to v5 migration.

**Comment by brusch** [comment]
The 'problem' is that a field-collection isn't aware of the classes where it is actually used. But the tables are not generic across classes, so each class has it's own  table per field-collection type.
So the solution in your case would be to manually save all classes (or at least the ones using the imported field-collections) after the bulk import. 
This 'rebuild' of classes isn't triggered automatically since this can take quite a long time depending on the amount of data stored in objects (hitting PHPs and webserver timeouts). 

Just a side-note: for migrating your project from v4 to v5 it shouldn't be necessary to migrate field-collections using the json export, see also: https://www.pimcore.org/docs/5.0.0/Installation_and_Upgrade/Updating_Pimcore/Upgrade_from_4_to_5/index.html
