### ISSUE TITLE
Deadlock

### ISSUE THREAD

**Issue by dipa-damco** [pimcore/pimcore#15688]
Thx for your hints. 

As fash mentioned it turned out to be because of deadlocks which occure when multiple "messenger:consume" processes were running. Although if you are just using one process it would be much faster... 

There seems to be a lot of disussion (and allready a pull request for creating the index):
https://github.com/symfony/symfony/pull/45007
https://github.com/symfony/symfony/pull/42345

For now i guess the best solution is to set up multiple "messenger:consume" processes so the table dosn't fill up that much :-).

Regards

_Originally posted by @ctippler in https://github.com/pimcore/pimcore/issues/11486#issuecomment-1045182388_
            

Regarding this issue, we have again faced the "Deadlock" on the "messenger_messages" table ( Pimcore V10.6).
The above input got approx 1 year ago. Any update regarding the same?

**Comment by brusch** [comment]
Closing this, as this is a Symfony "issue" that cannot be addressed by Pimcore. 
I'd recommend to NOT use the Doctrine transport, but a proper message queue instead, such as RabbitMQ. Doctrine is only configured as the default in Pimcore to reduce the dependencies and to get it up an running more quickly 😉

**Comment by dipa-damco** [comment]
@brusch & @dvesh3 We are not using anything regarding the "messenger_messages" table & neither use it nor customize it. It s Pimcore 10.6 's default feature, so it should work properly... We can't blame this on "Symfony". Also, we don't need any "Queue" feature, So no need to use "RabbitMQ". 

Can we stop the use of this table?

Thanks in advance.

**Comment by deepakkumarhm7** [comment]
@brusch Can we have list what all are symphony issue Pimcore inherited. Also, can you give idea why default Pimcore creating the messenger_messages table while installing. It should not be created.

**Comment by dpfaffenbauer** [comment]
@dipa-damco Pimcore, in default, uses messenger to do async things like maintenance tasks or core tasks, so you need it. depending on the load of the system, it is sufficient enough to use the default doctrine transport or not. So, Pimcore needs a Queue. 

@deepakkumarhm7 That is not Pimcore's responsibility. Pimcore is an Open Source System that uses a lot of other Open Source Software to work. Pimcore cannot define a List of issues other dependencies create, that is simply not possible. Also, other Systems might fix or break other things, so that list can never be complete. As already said, Pimcore Core needs a queue to do async things, therefore needing the table. If you have a system with high load, use Redis or RabbitMQ and more workers.

**Comment by deepakkumarhm7** [comment]
Hi @dpfaffenbauer On your comment "@dipa-damco Pimcore, in default, uses messenger to do async things like maintenance tasks or core tasks, so you need it. depending on the load of the system, it is sufficient enough to use the default doctrine transport or not. So, Pimcore needs a Queue." 

Can you share Pimcore doc where anything a mention about this will be a great help as we are facing issue. As we want to off this because when data grow in live system it is creating issue of performance. Please help.

**Comment by dvesh3** [comment]
@deepakkumarhm7 please see https://pimcore.com/docs/pimcore/10.6/Development_Documentation/Getting_Started/Installation.html#page_5-Maintenance-Cron-Job & you can read more about Symfony Messenger configuration [here](https://symfony.com/doc/current/messenger.html#transport-configuration).

we'll update the docs soon to add notice about deadlock issue on high load with https://github.com/pimcore/pimcore/issues/15698

**Comment by dpfaffenbauer** [comment]
@deepakkumarhm7 It also says is here under installation: https://pimcore.com/docs/pimcore/10.6/Development_Documentation/Getting_Started/Installation.html#page_5-Maintenance-Cron-Job

> it's recommended to run the following command using a process control system like Supervisor
> please follow the Symfony Messenger guide for a best practice production setup: 
> https://symfony.com/doc/current/messenger.html#deploying-to-production
