### ISSUE TITLE
[ECOMMERCE] Customization extension point (objectbricks) for orders and order items

### ISSUE THREAD

**Issue by maff** [pimcore/pimcore#1569]
Many projects need custom data on orders and/or order items. Currently there is no way to add custom data without having to modify the class definition. Many projects use an objectbricks field (usually called "customized") which allows to add custom data.

**Comment by dpfaffenbauer** [comment]
CoreShop has the same problem. It already has a brick for this kind of purpose. (called extraInformation) Problems I already faced:
 - Localized Data not possible in Bricks (Not a big deal, but could face problems)
 - Not as nice to get the data of bricks then it is of direct class fields
 - Update of Core Classes: It happened sometime that the relation between class and brick gets lost, so you need to re-save related bricks on updates of classes. I think the reason is because brick Relations are done via ID not NAME. ID's are different between installations. I already had a PR to fix that for Pimcore 4, but got closed cause of Pimcore 5.

One idea I had to fix the problem once for all was: Why not make inheritable object-classes in Pimcore? So, there would be a EcommerceOrder Class, and a CustomEcommerceOrder Class, the CustomEcommerceOrder Class inherits all fields from EcommerceOrder, therefore, you can extend CustomEcommerceOrder and Updateability is no Problem anymore. Everytime EcommerceOrder gets updated, CustomEcommerceOrder inherits fields from it and gets updated as well. Very similar to inheritance mapping in doctrine. But this would be a way bigger change and should be addressed (if interested) in a separated ticket.

**Comment by maff** [comment]
I see your points and the issues you mention with bricks are all valid (we'll look into #1190 soon). The brick added in this issue is just an additional way of adding customized data to an order/orderItem. For more complex scenarios it's still recommended to add needed fields on demand (the `OnlineShopOrder*` classes just act as templates which are meant to be extended).

I agree that inheritable class definitions would solve many portability issues, but I think that's something we need to discuss and plan with great detail as it involves a lot of change.

**Comment by dpfaffenbauer** [comment]
(Y) for reviewing my old PR, should I redo it for Pimcore 5?

Inheritable Classes:
Yeah, it is a big change. A lot of things needs to be considered like data inheritance and extjs layouts. Layouts are actually the bigger problem here. But I guess its worth discussing it internally and let us know about the status.

But, as already said, would solve a lot of problems with extendability of Bundles/Plugins like CoreShop or Ecommerce Framework.
