### ISSUE TITLE
[Bug]: Upgrade Migration Pimcore\Bundle\CoreBundle\Migrations\Version20230424084415 fails on Pimcore 11 Upgrade

### ISSUE THREAD

**Issue by ITspirit** [pimcore/pimcore#15769]
### Pimcore version

11.0.6

### Steps to reproduce

Just run:

./bin/console doctrine:migrations:migrate 

I could get it to work if i add 

` $db->executeStatement('SET foreign_key_checks = 0'); `

Into the "up" function.

### Actual Behavior

[error] Migration Pimcore\Bundle\CoreBundle\Migrations\Version20230424084415 failed during Execution. Error: "An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`pimcore`.`documents_editables`, CONSTRAINT `fk_documents_editables_documents` FOREIGN KEY (`documentId`) REFERENCES `documents` (`id`) ON DELETE CASCADE)"

### Expected Behavior

 Migration Pimcore\Bundle\CoreBundle\Migrations\Version20230424084415 was executed but did not result in any SQL statements.

**Comment by kingjia90** [comment]
Can't find `Version20230307135459`, did you mean `Version20230424084415` right?

Update: i've changed the issue title accordingly

**Comment by ITspirit** [comment]
Yes. Correct.

**Comment by kingjia90** [comment]
Thank you for reporting and also for the hint on foreign key checks.

The error itself is happening because some rows in `document_editables` with type `link` might have been "orphanized", meaning that the document they belong to does not exist anymore, and since this migration tries to re-save, it may have triggered that error and checks. 
Normally,  the CASCADE DELETE does the work, but it could be that the instance you are working on may have some leftover from before the [introduction](https://github.com/pimcore/pimcore/pull/11236) on that CASCADE and is "sneakily" kept passing on with the complicity of skipping foreign key checks.
Therefore, I would recommend to locally do some checks and potentially clean-up.

**Comment by dvesh3** [comment]
Fixed by #15772. thanks @ITspirit
