### ISSUE TITLE
[Bug]: Opera GX is incorrectly reported as not supported when opening admin panel

### ISSUE THREAD

**Issue by RaederDev** [pimcore/pimcore#15781]
### Pimcore version

11

### Steps to reproduce

Open Pimcore admin panel in Opera GX

### Actual Behavior

"Your browser is not supported. Please install the latest version of one of the following browsers."

### Expected Behavior

No message is displayed, as Opera is based on Chromium v115, which is supported without any issues. If it doesn't work in Opera it will likely also not work in Chromium, Edge or Chrome itself. The fundamental problem here is UA based detection which is always problematic and should ideally be replaced with feature detection instead.

UA:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 OPR/101.0.0.0`

**Comment by brusch** [comment]
Still - Opera is a different browser although it uses the same browser engine ... official support is only for supported browsers - even though it's uncertain, it could be that the behavior is different because of some additional functionality of those browsers or whatsoever (blocking content, ...),.

**Comment by NiklasBr** [comment]
@brusch I think the "Click here to proceed" might need some kind of fixing at least, because when I change user agent in Firefox 116 the " Your browser is not supported." message cannot be bypassed at all.

![Screenshot 2023-08-21 at 14 09 52](https://github.com/pimcore/pimcore/assets/279826/ade46455-9ebd-4970-b08b-18936ee77591)

**Comment by RaederDev** [comment]
I still find it a bit strange to show warnings when the engine is essentially the same but if that is expected behaviour then I will close the Issue.

I created a small Tampermonkey script to auto-hide the screen to fix this on my end instead:
```js
// ==UserScript==
// @name         Pimcore bypass
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  bypass UA check
// @author       You
// @match        https://*/admin/login*
// @grant        none
// ==/UserScript==

(function() {
    if (window.showLogin && document.querySelector('[class*="pimcore_version_"]')) {
        window.showLogin();
    }
})();
```

@NiklasBr 
The bypass link worked fine in Opera, maybe this is an issue that affects only FF.

**Comment by NiklasBr** [comment]
That's a bit ironic, isn't it :)

**Comment by brusch** [comment]
@NiklasBr that's true 😉 Can you please create an extra ticket for that, pls? Thanks!

**Comment by NiklasBr** [comment]
@brusch think I found the issue, see linked above.
