### ISSUE TITLE
[Bug]: Data loss when processing objects in multiple processes at once

### ISSUE THREAD

**Issue by nobears** [pimcore/pimcore#15831]
### Pimcore version

Latest supported version

### Steps to reproduce

1. Create data object definitions as described in comments in `StressTestCommand.txt`
2. Create command with the code from `StressTestCommand.txt`
3. Run `stress:test`  in multiple CLI tabs at once

[StressTestCommand.txt](https://github.com/pimcore/pimcore/files/12455148/StressTestCommand.txt)

### Actual Behavior

For one of our clients Pimcore is handling more than 9 million products which are update through multiple syncs for stock and pricing. Because there are so many updates we are using Symfony Messaging in combination with RabbitMQ to handle the huge data processing. Pricing is synced nightly but sometimes processes multiple million changes in a few hours.

Most of our code used the Pimcore PHP API to fetch the product, make the necessary changes and save the object. After a while we started noticing a loss of relational data for brands and categories (for this client these where the only relations in the product).

After a lot of research and testing we found a way to reproduce this with a small testing command which can be run multiple times in the CLI at once.

It seems that the problem is triggered `\Pimcore\Model\DataObject\Concrete\Dao::update` (https://github.com/pimcore/pimcore/blob/11.x/models/DataObject/Concrete/Dao.php#L218)
```
        $dataExists = $this->db->fetchOne('SELECT `src_id` FROM `object_relations_'. $this->model->getClassId().'`
        WHERE '.$condition .' LIMIT 1');
        if ($dataExists) {
            $this->db->executeStatement('DELETE FROM object_relations_' . $this->model->getClassId() . ' WHERE ' . $condition);
        }
```

### Expected Behavior

No data loss when data objects are saved multiple times at once through the PHP API.

**Comment by nobears** [comment]
Same issue happend to @dpfaffenbauer but for him this was happening with deadlock errors. In our use-case we don't have any deadlocks happening, the data is just removed.

https://github.com/pimcore/pimcore/issues/13678

**Comment by dpfaffenbauer** [comment]
@nobears we don't have a problem with data loss, we just have a deadlock in processing millions of rows async.

**Comment by nobears** [comment]
@dpfaffenbauer My apologies, I didn't read the issue properly!

**Comment by kingjia90** [comment]
I've tried with at least 7 tabs concurrently, but unfortunately couldn't reproduce it.

- From the code you've mentioned, could be slowing down to read first and delete (row-lock?) [StackExchange](https://dba.stackexchange.com/questions/328191/improve-delete-performance-by-running-select-query-first), but seems it is there to fix deadlock issues https://github.com/pimcore/pimcore/pull/11686
https://github.com/pimcore/pimcore/blob/ee81b3b9ce3dd0748a3a65fe755299f9de0fb029/models/DataObject/Concrete/Dao.php#L218-L222
- in the attached `StressTestCommand.txt` (btw Thank you for it!), this part would be perfomance killer 
```
foreach($languages as $language) {
    $product->setDescription((Factory::create())->text(), $language);
    $product->save();
}
```
should be 
```
foreach($languages as $language) {
    $product->setDescription((Factory::create())->text(), $language);
}
$product->save();
```
otherwise it would save for each language and have multiple versions as result, please make sure that in the mentioned project is not doing this in production

**Comment by kingjia90** [comment]
@nobears any feedback on https://github.com/pimcore/pimcore/issues/15831#issuecomment-1711719599?

**Comment by kingjia90** [comment]
Closing due inactivity
