### ISSUE TITLE
[PIMCORE5] Consider requiring PHP 7.1 as minimum version

### ISSUE THREAD

**Issue by maff** [pimcore/pimcore#1616]
As support for PHP 7.0 will end in December (http://de.php.net/supported-versions.php) and Symfony 4 will require PHP 7.1 we should consider requiring PHP 7.1 as minimum version.

**Comment by xlttj** [comment]
IMHO PHP 7.1 shouldn't be a minimum requirement until Dec 2018. Then security updates will end. Always having the latest version immediately as a minimum requirement sounds way too restrictive to me.

**Comment by jorisros** [comment]
I will recommend a more conservative approach, because as we speak the minimum version of symfony 3.3 is right now 5.5.9. 
I am sure that we will end up with hosting problems, because not all distros have php7.1 as default in there package manager. And they will bring security patches until December 2018 so the minimum  version should be at least 7.0 until the end of 2018.

**Comment by dpfaffenbauer** [comment]
Usage of 7.1 is growing, but most of the systems still use 7.0 or even 5.5/5.6. According to this statistics: https://seld.be/notes/php-versions-stats-2017-1-edition

**Comment by SVDBsibe** [comment]
I don't mind personally, but I agree with @jorisros that this should not be the case till 7.1 is widely used in distro package managers.

**Comment by Yivan** [comment]
I think we should keep 7.0 as minimum requirement and not 7.1.
Like it has been said 7.1 is not available on all linux distro.
As just a case exemple is Debian, the version 9 (stretch) is just out and PHP7.0 : https://www.debian.org/News/2017/20170617.en.html
It will cut more than 30% of enterprise debian server (many have policies to use only stable repo):
https://w3techs.com/technologies/history_details/os-linux

For me it is a bad idea to require php 7.1 because it will lead to not being able to use Pimcore for enterprise project wich are more conservative/security than technology uptodate.

**Comment by bbak** [comment]
Just a side-note: [Ondřej Surý](https://github.com/oerdnj) - who is the official maintainer of the PHP Packages in Debian - releases up-to-date PHP Packages for Debian and Ubuntu via [packages.sury.org/php/](https://packages.sury.org/php/) ppa and apt repos. He also provides [nginx packages](https://packages.sury.org/nginx/). We're using them for quite a while (since dotdeb.org announced to drop PHP Support) and never ran into any issue.

**Comment by brusch** [comment]
I can confirm @bbak experiences with sury.org

**Comment by Yivan** [comment]
Maybe we can stick to php 7.0 requirement and use polyfills ? This way Pimcore could be used on php 7.0 and can use Synmfony 4.

Please see:
https://symfony.com/blog/preparing-your-applications-for-php-7-with-symfony-polyfills
https://github.com/symfony/polyfill-php71
