### ISSUE TITLE
[Bug]: Problem with TimeZone

### ISSUE THREAD

**Issue by Krapfeen** [pimcore/pimcore#16184]
### Pimcore version

10.6.9

### Steps to reproduce

*Playback Environment:* \
Windows 10
Chrome Browser Version 118.0.5993.71 (Official Build), (64 bit)
Timezone: GMT+5

*Precondition:* \
Pimcore 10.6.9
Timezone Server GMT+3
\config\config.yaml:

pimcore:
    general:
        timezone: Europe/Moscow
"pimcore/data-hub": "^1.6" v. 1.6.3

Holydays class with the Date field type

*Playback Steps:* \
1. Go to a DataObject
1. Create an object of the holydays class
1. In the Date field, specify the date, for example 20.10.2023
1. Save and publish
1. Go to the Versions tab and pay attention to the Date field (2023-10-19)
1. Execute the request:

```
{
  getHolidays(id: $id) {
    date
  }
}
``` 
Comment:
When saving the value in the Date field, the client's time zone is taken into account, not the server's, respectively, the UTC label is saved for 5 hours less. At the same time, if the server with Pimcore is located in a time zone that differs from the Pimcore user's time zone, then the API will be given a value that corresponds to the server's time zone, relative to the stored timestamp

### Actual Behavior

```json
{
  "data": {
    "getHolidays": {
      "date": "2023-10-19 22:00:00"
    }
  }
}
``` 

### Expected Behavior

```json
{
  "data": {
    "getHolidays": {
      "date": "2023-10-20 00:00:00"
    }
  }
}
```

**Comment by kingjia90** [comment]
Confirming, i've noticed something similar few days ago https://github.com/pimcore/object-merger/pull/42#issuecomment-1785074317

**Comment by markus-moser** [comment]
The problem consists of multiple parts. The main problem is that there are different use cases for date values:

1. When used as point in time (e.g. the timestamp when a online shop order was created): 
 The date values should be formatted with respect of the user's timezone.
2. When used as time indication (e.g. the date/time when a event starts in a specific locality):
 The dates should be formatted independent of the user's timezone.

Currently Pimcore only supports the 1. option for date/datetime fields within data objects or asset metadata. Additionally this implementation has some bugs:

- [x] Version preview and CSV export of the classic bundle does not format the data attributes with the user's timezone but with the configured server timezone. (fixed in https://github.com/pimcore/pimcore/pull/17117, https://github.com/pimcore/pimcore/pull/17147  + https://github.com/pimcore/admin-ui-classic-bundle/pull/548 + https://github.com/pimcore/admin-ui-classic-bundle/pull/557)
   - [x] The asset metadata class definitions bundle (EE) needs to respect this too. (fixed in https://github.com/pimcore/asset-metadata-class-definitions/pull/188)
- [x] Filtering for date/datetime values in the element grid does not work correctly. (fixed in https://github.com/pimcore/admin-ui-classic-bundle/pull/553 and https://github.com/pimcore/pimcore/pull/17135)
- [x] Version preview and CSV export of the portal engine does also not format the date values with the user`s timezone. (fixed in https://github.com/pimcore/portal-engine/pull/577)

In addition to that Pimcore should offer a option to switch between the 2 modes on datetime attribute level depending on the use case.
- [x] Add switch (point in time vs. time indication) on datetime attribute level. The new "time indication" mode should enforce the column type "datetime" as "timestamp" does not make sense in that use case:
![image](https://github.com/pimcore/pimcore/assets/4639428/408e6b7a-b69a-4a3f-b2bd-af0b93f90625)

=> Fixed in https://github.com/pimcore/pimcore/pull/17151 and https://github.com/pimcore/admin-ui-classic-bundle/pull/560. With enabled timezone support would be the "point in time" mode whereas without timezone support is the "time indication" mode.

For the datahub case mentioned in the issue description the easiest solution for now could be to set the Pimcore server timezone if you are not in an environment where different timezones matter:

```yaml
pimcore:
    general:
        timezone: Europe/Berlin
```

In the future this needs to respect also the 2 different modes/use cases. 
- For the "point in time" mode the date values should be outputted with the timezone added to the date format. This can only be done in a major release of the data hub as it would be a potential BC break. So for now this is the date formatted in the configured server timezone (UTC is the fallback timezone if no timezone is configured)
-> issue created: https://github.com/pimcore/data-hub/issues/867
- [x] For the "time indication" mode the date should stay the same for any timezone.

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/17117 and all the related PRs
