### ISSUE TITLE
[Bug]: Passwords that appear to be a hashed String cannot be used as password with recommended 'password_hash' algorithm

### ISSUE THREAD

**Issue by schmidt-travixmedia** [pimcore/pimcore#16236]
### Pimcore version

All versions

### Steps to reproduce

Create a Data Object class with a "Password" field and select 'password_hash' as algorithm. Create a new data object and enter 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1a' or 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1A' as password. Both passwords are "MD5-like" strings.

Now when Pimcore authenticates against a Data Object of such a class by using 'ObjectUserProvider', it will fail.

If you set the password to 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaz', it will work because "z" is not allowed in a hexadecimal MD5 string.

You can also easily try it with the Pimcore Demo 10.3 or higher: 
Open the Data Object with path "/Customer Management/customers/AT/1020/Fred-Flintstone".
Click tab 'Authentication' and set password to 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1a'.
Now go to Frontend and login with email 'fred.flintstone@stone.age' and password 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1a'. Login will fail.

If you set 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaz' as password, it will work.

If you have a look into the database, you will see 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1a' as plain text. In contrast when using 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaz', you will see its hashed value.

### Actual Behavior

"Hash-like" strings are not hashed again. This is documented ( https://pimcore.com/docs/platform/Pimcore/Objects/Object_Classes/Data_Types/Text_Types#password ) but in my opinion, it makes absolutely no sense.
When offering a password field with "encryption magic", why should "pre-hashed" strings be excluded from being stored here? Either all strings should be encoded automatically or none (in that case, the developer has to make sure strings are pre-encoded)

Problem: If you have a self registration process and a user would enter something like 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1a' as password, he will not be shown a failure message (except if you implement yourself a check with "password_get_info()") but when the user tries to login, it will fail.

A colleague told me, this may be a backward-compatibility issue. If this is the case, please update the documentation and tell the reader that some passwords like 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1a' cannot be used due to backward-compatibility.

### Expected Behavior

"Hash-like" passwords should work with recommended 'password_hash' algorithm.
If this is not possible due to backward-compatibility issues, please clarify it in the documentation.

**Comment by NiklasBr** [comment]
I agree, this could be improved. Problem is not limited to md5-like strings because `password_get_info()` cannot detect many other hashes, nor can it detect more modern hashes like `sha256` or `sha512` even.

https://github.com/pimcore/pimcore/blob/2bbea095fce0e03c9762342e3bb373616a79a6c2/models/DataObject/ClassDefinition/Data/Password.php#L107-L129

Can't resolve the issue by storing a prefix in the database field alongside the algo either (e.g. `sha256:ab047de1dbf34053dcb.....9ea53b072a8fdc`) as that is also technically a valid plaintext string. Less likely to be an incorrect detection, but it shares the same fundamental problem you highlight.

To resolve it I suspect a major change has to be done, unfortunately. Perhaps a bunch of the older and shorter hashes could be removed in Pimcore 12?

Thinking here: Maybe it should actually be made "stupider" by always hashing the field if it is marked as `dirty`?

**Comment by kingjia90** [comment]
Closing as fixed by #16283, followup issues are opened
