### ISSUE TITLE
[Bug]: Forgot password doesn't work

### ISSUE THREAD

**Issue by eraush** [pimcore/pimcore#16253]
### Pimcore version

11.1

### Steps to reproduce

1. Navigate to [https://demo.pimcore.fun/admin/login](https://demo.pimcore.fun/admin/login)
2. Click Forgot your password? link
3. Enter valid username
4. Click Submit button

![error forgot password](https://github.com/pimcore/pimcore/assets/131660776/c45fb65c-a699-4638-93c3-95a7801b906c)

### Actual Behavior

The error message is displayed 

### Expected Behavior

Email with recovery link should be sent

**Comment by kingjia90** [comment]
Works fine so far, the problem happens in the demo because the email and password are not set by default, especially `superuser`
https://github.com/pimcore/admin-ui-classic-bundle/blob/2290867662070419fc792ed1ad7c5a78edffaa83/src/Controller/Admin/LoginController.php#L218-L223
The error message is generic to avoid enumeration, see https://github.com/pimcore/pimcore/pull/14568#discussion_r1132375105
