### ISSUE TITLE
[Bug]: Grid Search displaying entries not matching the search term

### ISSUE THREAD

**Issue by varshaekrocx** [pimcore/pimcore#16491]
### Pimcore version

11

### Steps to reproduce

Currently, we are using pimcore  v11.1.0 had tried with bin/console pimcore:search-backend-reindex. But still the issue is same.

### Actual Behavior

![image](https://github.com/pimcore/pimcore/assets/124252930/8eeb124a-579a-4792-89e6-b6c65c16b21c)
When i am searcing for an object in grid it gives multiple results and that not relevent

### Expected Behavior

When i am searching for an object it should return particular matching result.

**Comment by kingjia90** [comment]
It's likely falsely triggered by the path having `data` or `job` in it. What is the full path of this folder?

**Comment by varshaekrocx** [comment]
![image](https://github.com/pimcore/pimcore/assets/124252930/d1413baf-9cf5-41d3-9d36-d203a1268bd7)
@kingjia90 fullpath is given in above image

**Comment by kingjia90** [comment]
Ah, then it's likely because these element have something in their `data` and `properties` that have the term "data" or "job" (table: `search_backend_data`)
See https://github.com/pimcore/admin-ui-classic-bundle/blob/98cbe1cde3d91bdefc13d2539320a20b6015f5c3/src/Helper/GridHelperService.php#L633

I'll try by quoting it eg.`"Data job"` to reduce the amount of unwanted results.

It would still display unrelated results with other "simple words" (data, job, name, footer, copyright etc..), unless we have a filtering rule (checkboxes for example) to just only search by `path` AND/OR `key`

**Comment by varshaekrocx** [comment]
Thanks @kingjia90. Adding double quotation has reduced  the unwanted results.

**Comment by varshaekrocx** [comment]
![image](https://github.com/pimcore/pimcore/assets/124252930/0b63bbb8-a794-4f39-93a5-6574e2373940)

![image](https://github.com/pimcore/pimcore/assets/124252930/6c52db25-ae9a-458c-a92c-7b50cf44ac67)

Also There is an object with name "TI" exist but while i am searching for it ,it shows nothing in search result. Is there a way to product result for "TI" object

**Comment by kingjia90** [comment]
It seems that the minimum char length of the search term is `3` and always been like that.

There's an extension that somehow tries to "fix" this but personally never tried.
https://pimcore.com/en/developers/marketplace/blackbit_digital_commerce/pimcore-better-search_e333574#:~:text=terms%20with%20less%20than%203%20characters%20get%20ignored


However i am closing the issue, these are not bugs per se', but some unexpected and maybe not properly documented stuff.

Looking forward for PRs to improve this aspects.

Thank you for your inputs
