### ISSUE TITLE
[BUG, EC]: CSRF error when trying to login to the backoffice

### ISSUE THREAD

**Issue by ghost** [pimcore/pimcore#16607]
### Pimcore version

11.x

### Steps to reproduce

When trying to login to the Backoffice (e.g. by Chrome), the CSRF detection often blocks that, deleting cookies will not help, only the private browsing mode will solve this.
This issue is reproduceable especially when calling the backend by an ip address.
Only one browser window is open and used.

### Actual Behavior

Login blocked.

### Expected Behavior

Login possible.

**Comment by kingjia90** [comment]
This one is a little tricky, i can't reproduce locally (at least with `127.0.0.1`), the fact that in incognito works, should hint that there are no problems itself (since we do not make any distinctions) and could be something client side instead. 

What about chrome extensions like auto-fill or password manager that somehow are replacing the hidden csrf token field value?
NB: On incognito mode, the extensions are not automatically activated like in the normal mode unless marked here or individually installed
![image](https://github.com/pimcore/pimcore/assets/6014195/df9e4a2a-e445-44f7-b663-1b03b2577fde)

It could be checked in the source code to see if it changes on every reload or stays the same.
![305374369-67dc4c81-98dd-4a4e-a74b-515e12936724](https://github.com/pimcore/pimcore/assets/6014195/69805a03-1d01-4365-84ad-f7dba516cf1b)

but still not sure if i am on the right track, because they mentioned
> often blocks that

and not always 🤔  


Any suggestions?

**Comment by kingjia90** [comment]
Another case that i know is that if you double-click the Login button quickly, somehow it triggers a false positive CSRF error. It could be that there is something (dunno eg.redirects from ip to domain?) that mimics the same? but i would need some more details

**Comment by nathaliemohrsynaigy** [comment]
I made sure to have the same Chrome extensions active in normal and incognito mode, this doesn't seem to be the cause.
The csrf token changes on reload in both cases aswell.

But what I just found: 
Just entereing the ip went to http and not https (it's a testing instance without valid certificate) and manually  switching to https seems to solve the problem.   
This might be due to the information stuck in my browser being bound to the http url, or maybe it is the cause, I'm not sure.   
But as the issue appeared for several people, this might be a clue.

**Comment by kingjia90** [comment]
Thank you for the feedback, 

> But what I just found: Just entereing the ip went to http and not https (it's a testing instance without valid certificate) and manually switching to https seems to solve the problem.

sound similar to https://github.com/symfony/symfony/issues/41707#issuecomment-861460769 maybe will find something helpful in the conversation thread but no idea on how we could fix it yet

Maybe try by override this 
https://github.com/pimcore/pimcore/blob/ad458f32de718ab66d18c11571fce66dbd1c0af9/bundles/CoreBundle/config/pimcore/default.yaml#L20 to [lax](https://symfonycasts.com/screencast/api-platform2-security/samesite-csrf#caveats-with-samesite)?

**Comment by kingjia90** [comment]
Also maybe this PR https://github.com/pimcore/admin-ui-classic-bundle/pull/437 could be related and be of help

**Comment by ghost** [comment]
Closed as agreed with customer.
