### ISSUE TITLE
[Bug, EC, LTS]: Sorter of classification store groups in dataobject does not work when the object is saved&published

### ISSUE THREAD

**Issue by ghost** [pimcore/pimcore#16723]
### Pimcore version

11.1.5

### Steps to reproduce

Go to demo.pimcore.fun

1. Create ClassificationStore, add groups and keys with sorters
2. Add Group to an object
3. Groups is sorted via sorter
4. Save & Publish and reload object
5. Groups are sorted via internal id

### Actual Behavior

In classification store we have collection and groups inside the collection. We need to use the sorter configuration in the group-collection relations.

The issue is when adding the groups from a specific collection inside a dataobject, the sorter works during the draft and when the object is just saved but not published. As soon as the dataobject is saved&published, the sorter is omitted, the groups are sorted by their internal id!

### Expected Behavior

Sorting works as expected.

![screen1](https://github.com/pimcore/pimcore/assets/150000890/2c9502d9-69bf-4683-a9cc-2ed299f4f7ef)
![screen2](https://github.com/pimcore/pimcore/assets/150000890/5b58f77c-3324-42fe-a56d-993b97895306)

**Comment by kingjia90** [comment]
Work in progress: identified the problem, `$items` would be empty if not any value is set to any of the input fields (like in the screenshot) and this loop would be skipped
https://github.com/pimcore/pimcore/blob/cbc427c6b615e9dd1e9cbec31e878dec37de91ac/models/DataObject/Classificationstore/Dao.php#L89
and skipping this https://github.com/pimcore/pimcore/blob/cbc427c6b615e9dd1e9cbec31e878dec37de91ac/models/DataObject/Classificationstore/Dao.php#L132 doesn't save the Group Collection value and the groups are considered individually rather than part of the Collection, or something like that. 
Probably also would be affected with inherited values.

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/pimcore/pull/16769, https://github.com/pimcore/ee-pimcore/pull/140
