### ISSUE TITLE
[Bug]: pimcore previewing videos is not working

### ISSUE THREAD

**Issue by abdelrhmanyosry** [pimcore/pimcore#16801]
### Pimcore version

11

### Steps to reproduce

upload any video formats and open the video

### Actual Behavior

the video is loading forever

![image](https://github.com/pimcore/pimcore/assets/121692656/cb348ddf-7197-4dd4-9822-a87c404d9d7b)
![image](https://github.com/pimcore/pimcore/assets/121692656/2bffcb86-1145-46fa-8325-943b6ecd7320)
![image](https://github.com/pimcore/pimcore/assets/121692656/08255081-f04c-4f4d-892b-2bf635f759af)

### Expected Behavior

it should preview the video.
![image](https://github.com/pimcore/pimcore/assets/121692656/9c79581d-51ff-400a-a373-e9863f5a00a4)

**Comment by blankse** [comment]
@abdelrhmanyosry Did you install the symfony messenger?
https://pimcore.com/docs/platform/Pimcore/Getting_Started/Installation/Webserver_Installation#5-maintenance-cron-job

**Comment by abdelrhmanyosry** [comment]
thankyou! @blankse 
it works now, could you please explain to me what was the problem?

**Comment by blankse** [comment]
@abdelrhmanyosry The videos are converted into the correct format for playback in the browser using Symfony Messenger. If this messenger is not set up or not running, no new videos will be played in the admin interface.

**Comment by abdelrhmanyosry** [comment]
@blankse so I have to run it every time I will upload new videos? or how can I handle it for the client?

**Comment by blankse** [comment]
@abdelrhmanyosry The symfony messenger should always run. You can use a Process Manager like Supervisor or systemd to keep your worker running.

Otherwise you can use a cronjob every 5 minutes and add the `-time-limit=300` option. So the messenger worker runs 5 minutes and you start it every 5 minutes.

See: https://symfony.com/doc/current/messenger.html#deploying-to-production
