### ISSUE TITLE
"pimcore_placeholder()" Twig function is broken by "twig/twig" >= v3.9.0

### ISSUE THREAD

**Issue by alesak** [pimcore/pimcore#16973]
### Pimcore version

10.6 or newer

### Steps to reproduce

try to render attached twig document
[placeholder-test.html.twig.txt](https://github.com/pimcore/pimcore/files/15058603/placeholder-test.html.twig.txt)

### Actual Behavior

When rendered with twig v3.8.0 it correctly renders three times same section but when rendered with twig v3.9.0 or newer the part which should be captured is actually rendered and the three sections which should contain captured content are empty

### Expected Behavior

same content should be rendered with both versions of "twig/twig"

**Comment by jdreesen** [comment]
That's because it uses `rybakit/twig-deferred-extension`, which hacks Twig to do its thing, and now it broke with the latest Twig update. 

So you should stay on Twig `<3.9` for now, like: #16958

**Comment by alesak** [comment]
I don't think it uses `rybakit/twig-deferred-extension` but rather similar technique using \ob_start() \ob_get_clean(); to capture the content and is now not working thanks to the "yield" output used in twig >= 3.9.0 instead print or echo....

**Comment by jdreesen** [comment]
You're right. This needs to be fixed on Pimcore's side. Maybe the new `CaptureNode` helps here.

**Comment by markus-moser** [comment]
This works again in new versions of twig (>=3.14.0). Therefore this problem is solved. Take a look at this PR: https://github.com/pimcore/pimcore/pull/17593/files

There we changed the conflict so that only broken versions are conflicted:
https://github.com/pimcore/pimcore/pull/17593/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R137

Unfortunately `pimcore_placeholder.captureStart()` and `pimcore_placeholder.captureEnd()` will not work anymore with twig 4. Therefore we needed to depcreate those methods. Take a look into this PR and the related/changed docs to see an example how to achieve the same with native twig `set` tag: https://github.com/pimcore/pimcore/pull/17444
