### ISSUE TITLE
[Bug]: Versions table, no index on versionCount

### ISSUE THREAD

**Issue by GeorgII-web** [pimcore/pimcore#17316]
### Pimcore version

any

### Steps to reproduce

Conditions:
- 15 millions rows in a `version` table.
- Many parallel processes that creates DataObjects.

On high IO level there is a significant performance degradation on `versions` table.

### Actual Behavior

At some point DB just went to full resource usage and stuck.
![image](https://github.com/pimcore/pimcore/assets/52407577/830f35e8-8e98-4435-8661-30c0083a2674)

In a Debug section only `versions` table related queries:
`SELECT MAX ( `versionCount` ) FROM `versions` WHERE `cid` = ? AND `ctype` = ? `
and
`SELECT versionCount FROM objects WHERE id = '10496463' FOR UPDATE`
![image](https://github.com/pimcore/pimcore/assets/52407577/0ff5d5dd-39e2-4069-83ed-9ebbe60598be)

### Expected Behavior

Adding index to `versionCount` column (or composite index) on `versions` table will help make it faster.

**Comment by kingjia90** [comment]
Thank you for reporting!

Although it could be considered as a bug, the fix is only doable in a minor release due to the migration, therefore I've switched it to an improvement.
Please manually run the migration seen on #17744 or apply the changes directly in your table, if necessary for your project.
