### ISSUE TITLE
[Improvement]: Implement Symfony Flex 

### ISSUE THREAD

**Issue by kingjia90** [pimcore/pimcore#17496]
### Improvement description

Aligning the core and the bundles to work seamlessly with the `symfony/flex` approach

See also https://github.com/pimcore/pimcore/issues/14355 for all the preparation details

**Comment by brusch** [comment]
Trying to summarize discussion and findings in #14355: 
1. Pimcore's current concept of pre-configuring Symfony bundles (Doctrine, Flysystem, Messenger, Mailer, 2FA, Framework, ...) is mostly incompatible with the philosophy of Flex, where each bundle adds it's own (template) configs that can be customized after install 
  a. how would this work together with having an installer - also for bundles? (somehow obsolete then)  
  b. how this would go along with Pimcore's special config loading and merging strategy for bundles ( autoloading files in `config/pimcore/`) 
2. There would be a workaround for telling Flex to not install files for other bundles by adding a `symfony.lock` file to demo/skeleton 
3. What do do with demo/skeleton, should they themself be flex packages? If so, this would be in conflict with point 2 🤔 
4. Bundle dependencies: 
> IF a recipe of bundle A adds a line to "bundle.php" (eg. [statistic explorer](https://github.com/kingjia90/recipes/blob/fa619d4059e1ff265cada08c1d242afaeaaafef7/pimcore/statistics-explorer/2.1/manifest.json#L3)) and we install a bundle X(eg. portal engine) that requires bundle A, it would ask you to run the recipe of bundle A and there is no way to tell to skip as it would taken care by the bundle X tacitly via registerDependentBundles().


At the end the main question is: 
Is Pimcore an "app" that should also run out of the box by simply running an installer, or is it itself a framework/library/bundle.

**Comment by dpfaffenbauer** [comment]
> Is Pimcore an "app" that should also run out of the box by simply running an installer, or is it itself a framework/library/bundle.

If you phrase the question like that, Pimcore is both. Pimcore has a installer and can run out of the box, but its also a framework/lib/bundle for your application. 

Re flex:

1. I think you are asking the wrong questions. Pimcore uses certain bundles already and pre-configures them. But what about other 3rd party bundles that do come with flex recipes? Why not support them?
3. Demo is a demo, and not a lib. 
4. Bundle dependency: I still remember when we introduced the DependantBundleInterface. It makes sense and it works ok. Pimcore has a Problem with Bundle Dependency Priority anyway, there are 3 ways of registering bundles (bundles.php, AppKernel, Dependant Bundle) and 2 out of 3 support defining a priority. Symfony itself doesn't have a priority per se, its just first come first serve. Flex might not really solve that since it also doesn't have a bundle priority.

**Comment by brusch** [comment]
@dpfaffenbauer I agree, I assume the main point is to give developers the possibility to install additional (Pimcore) bundles via Flex, it's not about Pimcore itself utilizing Flex for every single package. 

Therefore I'd go for the simplest solution, which is shipping a `symfony.lock` with skeleton and demos.

**Comment by brusch** [comment]
We discussed this topic again internally and we agreed that it is sufficient to allow developers optionally to use `symfony/flex`. 
Therefore the solution is to add a default `symfony.lock` to our skeleton that contains all the packages which are used by stock Pimcore. 

With that file in place it's super safe to run `composer require symfony/flex` and you can easily install additional bundles using Flex, e.g. `composer require nelmio/api-doc-bundle`. 

Regarding demos: Demos are demos, no need to include the `symfony.lock` there. 
Pimcore bundles: they can utilize flex or not, no need to migrate all the existing bundles for now, however it could make sense for new bundles or even existing bundles if it simplifies the setup process 

See also https://github.com/pimcore/skeleton/pull/204

Closing this here, as this is not a topic for `pimcore/pimcore` and there's already a PR for skeleton.
