### ISSUE TITLE
[Bug]: since [#17362] Imagick: Thumbnails (image/jpeg) getting rendered with transparent layers

### ISSUE THREAD

**Issue by siwa-ddiesenreither** [pimcore/pimcore#17589]
### Pimcore version

11.3.2

### Steps to reproduce

Use this image:
![bug-example](https://github.com/user-attachments/assets/bc2dbd4e-73ef-404a-930b-3fbcefac714a)

### Actual Behavior

Thumbnails look like:
<img width="1126" alt="Bildschirmfoto 2024-09-11 um 11 03 35" src="https://github.com/user-attachments/assets/3c5fbbc9-b283-479b-a1e3-09d560a1149d">

### Expected Behavior

Thumbnail should look like:
<img width="1132" alt="Bildschirmfoto 2024-09-11 um 11 05 08" src="https://github.com/user-attachments/assets/8fc070cc-383f-4890-bbd3-0bcdc1ff89fc">

**Comment by LosHawlos** [comment]
@siwa-ddiesenreither Please check if the image contains a clipping path because Pimcore will respect that by default. In that case you should remove the clipping path from the image or you can disable the automatic clipping as described in the documentation: https://pimcore.com/docs/platform/Pimcore/Assets/Working_with_Thumbnails/Image_Thumbnails#clipping-support

**Comment by siwa-ddiesenreither** [comment]
@LosHawlos okay. I've disabled the feature and now they are working again. Did not know that clip paths are also included in image/jpeg - thought they are only relevant in tiff, psd etc.
