### ISSUE TITLE
[Bug]: Outdated twig/twig dependency has a security vulnerability [CVE-2024-45411]

### ISSUE THREAD

**Issue by michalananapps** [pimcore/pimcore#17582]
### Pimcore version

11.3.2

### Steps to reproduce

composer update

### Actual Behavior

`roave/security-advisories` and `trivy` security checks conflicts with `"twig/twig": "<1.44.8|>=2,<2.16.1|>=3,<3.14"` due to CVE-2024-45411:  https://www.cve.org/CVERecord?id=CVE-2024-45411

pimcore requires:
```
    "twig/extra-bundle": "^3.4.0",
    "twig/string-extra": "^3.3.5",
    "twig/twig": "^3.3.9",
```

### Expected Behavior

pimcore requires:
```
    "twig/twig": "^3.14",
```

**Comment by jdreesen** [comment]
The actual problem is that there's a conflict with `"twig/twig": ">=3.9.0"`, so the security update *cannot* be installed. 

It's probably necessary to tackle #17457 sooner than expected.

More information: https://symfony.com/blog/twig-security-release-possible-sandbox-bypass

**Comment by kingjia90** [comment]
Just had a look on how it may affect Pimcore 11, does 
https://github.com/pimcore/pimcore/blob/c02ccf9e16ef1a08f592c5f42c5b3f7f14f43a21/bundles/CoreBundle/src/DependencyInjection/Configuration.php#L1979-L1982
https://github.com/pimcore/pimcore/blob/c1f305b311e0845bc3748126d02da07528574131/bundles/CoreBundle/config/pimcore/default.yaml#L333-L338
prevents from the security flaw conditions being met because the sandbox is always globally enabled?
![image](https://github.com/user-attachments/assets/a1de61e4-ac4e-46ea-9026-39f81a986b85)
?
If so, for 11 it might be just some warning/known-issue that composer `audit` may show each time, right? or am i missing something?

**Comment by kingjia90** [comment]
Oh wait, maybe we just need to find an alternative approach for this and keep it always enabled
https://github.com/pimcore/pimcore/blob/68f198d32add713f2e4025b5dcb6414754133145/lib/Templating/TwigDefaultDelegatingEngine.php#L98-L103
https://github.com/pimcore/pimcore/blob/7c50b9c530bcb106e192d7dfd3c34bb5eeaaf038/lib/Mail.php#L608-L610

**Comment by michalananapps** [comment]
> Oh wait, maybe we just need to find an alternative approach for this and keep it always enabled

This will not resolve the issue with twig/twig versions < 3.14 being flagged as a potential security risk. The problems occur during security audits of applications using Pimcore (which uses an outdated version of Twig).

**Comment by jdreesen** [comment]
@kingjia90 have you tried to see if newer versions of Twig 3 work with Pimcore? As I said in #17457, there have been some bug fixes in Twig regarding the echo → yield transition, because theoretically there *shouldn't* be any breaking changes in Twig 3 (unless you've “abused” some stuff, like the “deferred” extension does).

**Comment by kingjia90** [comment]
That is a possibility that needs to be taken in consideration, thank you for the suggestion.

My main concern is that i am not sure how quickly we can release 12, and we still need a "compromise" non bc-breaking fix for 11 and LTS purposes.

I was thinking more like to focus to make it secure and "ignore" the audit by virtually consider it as a false positive, like something that is fixed/known on paper but we have to live with the red alerts

**Comment by jdreesen** [comment]
I was hoping that the latest fixes in Twig 3.x would allow it to be updated in Pimcore 11 and switch to Twig 4.x in Pimcore 12 instead.

**Comment by michalananapps** [comment]
Conflict with Twig >= 3.9.0 was added on Apr 23 because rybakit/twig-deferred-extension is incompatible with it.

https://github.com/pimcore/pimcore/pull/16976
https://github.com/pimcore/pimcore/pull/16958


On July 15th, the dependency on rybakit/twig-deferred-extension was removed, but the conflict with 'twig/twig': '>=3.9.0' remained.
https://github.com/pimcore/pimcore/pull/16966

In my opinion, the conflict should have been removed as well. The standard Twig extensions should work in the 3.x branch.

**Comment by jdreesen** [comment]
It's not just `rybakit/twig-deferred-extension`. There were also problems in Pimcore. For example, #16973 and #17444. We need to check if these still exist with the latest Twig 3.x versions.

**Comment by michalananapps** [comment]
@jdreesen I've added some tests in #17593

**Comment by fashxp** [comment]
thanks guys, sadly it is not only about pimcore_placeholder, but also about pimcore_cache, pimcore_headscript, pimcore_headstyle and pimcore blocks.

we will have a look at it, maybe some else can support

**Comment by fashxp** [comment]
see also https://github.com/pimcore/pimcore/pull/17593#issuecomment-2358729015
