### ISSUE TITLE
[Improvement]: Add checks for setting `QuantityValue` values and units

### ISSUE THREAD

**Issue by mcop1** [pimcore/pimcore#17627]
### Improvement description

Look into `QuantityValue` and `QuantityValue\Unit`. Address following: 

1.) When using string as identifier, the identifier doesnt get validated, it is possible to pass whatever you want
2.) When using `Unit::getByAbbrevation` there is no validation too
3.) Check for other possible validations in preparation for adding a fk constraint

**Comment by kingjia90** [comment]
Potentially resolved by https://github.com/pimcore/pimcore/pull/17860


Just leaving some notes to address the bullet list

1) The `Quantitity\Value\Unit` is unaltered, it seems mostly fine (beside note below in point 2), because it's related to the units in `quantityvalue_units`

2) The getByAbbreviation doesn't seem needing to be validated, this return null when not found should be enough https://github.com/pimcore/pimcore/blob/8af1316f0c7380e244691ab607665a5fe5fa0f01/models/DataObject/QuantityValue/Unit.php#L59 but i've found a potential bug, there is no unique index for the abbreviation column, then when [fetching](https://github.com/pimcore/pimcore/blob/3ffaeac8d9f07f877ea4f469015be1774de447b9/models/DataObject/QuantityValue/Unit/Dao.php#L51) it in the DAO it could not getting the intended unit, if there are multiple units with the same abbreviation (which seems )
![Image](https://github.com/user-attachments/assets/7fe538fb-0148-4a4c-a8c9-411b8108c1a2)


3) The fk would likely have a cascade delete, so "preventing" (by throwing exception) from using/setting not existing Unit should be enough, right?

**Comment by mcop1** [comment]
1. The problem here was that you can pass any string to the constructor of `QuantityValue` and it will be saved to the database, even if it is not a valid unit. Small example:

```
$car = Concrete::getById(1169);
if(!($car instanceof Car)) {
    return $this->json(['error' => 'DataObject not found']);
}        
$attr = $car->getAttributes();
$bw = $attr?->getBodywork();
$bw?->setCargoCapacity(new QuantityValue(100, 'dne')); //dne = does not exist
$car->save();

```

Result: 
UI wise it looks like the value wasnt set
![Image](https://github.com/user-attachments/assets/c5b95176-79a9-4f53-894d-00db05bc7ad9)

But if you look at the db:
![Image](https://github.com/user-attachments/assets/6f5944c4-248e-46b3-9c9f-f2e042ce9547)

2. Agreed, returning null should be enough. Again here would be something like `getAbbreviation` (throws exception) `TryGetAbbreviation` doesnt throw an exception nice. But that´s more a general nice-to-have thing, definitely not part of this issue.

3. Should be fine if we solve 1.)

**Comment by kingjia90** [comment]
Thank you for the clarification, super, then i think the PR is just fine to go

After PR, the given example would return as
![Image](https://github.com/user-attachments/assets/75ff907f-aabf-4519-8f86-94316fced4d3)
