### ISSUE TITLE
[Bug]: NumericRange data type cannot load after save due to type error

### ISSUE THREAD

**Issue by tmannherz** [pimcore/pimcore#17700]
### Pimcore version

v2024.3

### Steps to reproduce

A type error is thrown when a numeric range field is saved on a data object.

This was all reproduced on the demo site, https://demo.pimcore.fun/admin/
1. Add a `Numeric Range` data type to a field collection and specify decimal precision:
![image](https://github.com/user-attachments/assets/906bcf5a-5444-4c70-915f-f8f5bc113012)
1. Add the field collection to an existing data object: 
![image](https://github.com/user-attachments/assets/af76c713-4034-45d8-919c-3abcf5e7cdec)
1. Open a data object, add the field collection and set a range: 
![image](https://github.com/user-attachments/assets/a6699dbd-9958-45a7-82e0-6398272c2019)
1. Save the data object and reload. A type error will be thrown: 
    ```
    Timestamp: Tue Oct 08 2024 09:33:43 GMT-0400 (Eastern Daylight Time)
    Status: 500 | Internal Server Error
    URL: /admin/object/get
    Message: Pimcore\Model\DataObject\Data\NumericRange::__construct(): Argument #1 ($minimum) must be of type int|float|null, string given, called in /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/NumericRange.php on line 243
    ```

### Actual Behavior

Here's a full stack trace from a site that's in debug mode:
```
Message: Pimcore\Model\DataObject\Data\NumericRange::__construct(): Argument #1 ($minimum) must be of type int|float|null, string given, called in /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/NumericRange.php on line 243
Trace: 
in /var/www/html/vendor/pimcore/pimcore/models/DataObject/Data/NumericRange.php:30
#0 /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/NumericRange.php(243): Pimcore\Model\DataObject\Data\NumericRange->__construct('10.00', '15.00')
#1 /var/www/html/vendor/pimcore/pimcore/models/DataObject/Fieldcollection/Dao.php(116): Pimcore\Model\DataObject\ClassDefinition\Data\NumericRange->getDataFromResource(Array, Object(Pimcore\Model\DataObject\Event), Array)
#2 [internal function]: Pimcore\Model\DataObject\Fieldcollection\Dao->load(Object(Pimcore\Model\DataObject\Event))
#3 /var/www/html/vendor/pimcore/pimcore/lib/Model/AbstractModel.php(220): call_user_func_array(Array, Array)
#4 /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Fieldcollections.php(277): Pimcore\Model\AbstractModel->__call('load', Array)
#5 /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Fieldcollections.php(418): Pimcore\Model\DataObject\ClassDefinition\Data\Fieldcollections->load(Object(Pimcore\Model\DataObject\Event))
#6 /var/www/html/var/classes/DataObject/Event.php(1529): Pimcore\Model\DataObject\ClassDefinition\Data\Fieldcollections->preGetData(Object(Pimcore\Model\DataObject\Event))
#7 /var/www/html/vendor/pimcore/admin-ui-classic-bundle/src/Controller/Admin/DataObject/DataObjectController.php(1339): Pimcore\Model\DataObject\Event->getIntlShippingRates()
#8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(181): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->saveAction(Object(Symfony\Component\HttpFoundation\Request))
#9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#10 /var/www/html/vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /var/www/html/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#12 /var/www/html/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
#13 /var/www/html/public/index.php(18): require_once('/var/www/html/v...')
#14 {main}
```

The constructor of `Pimcore\Model\DataObject\Data\NumericRange` doesn't allow strings, which the decimal types are interpreted as.

```php
    public function __construct(float|int|null $minimum, float|int|null $maximum)
    {
        $this->minimum = $minimum;
        $this->maximum = $maximum;

        $this->markMeDirty();
    }
```

### Expected Behavior

Setting a valid range on a numeric range data type should allow for save and reload.

Something like this in the constructor of `Pimcore\Model\DataObject\Data\NumericRange` seems to fix it:

```php
    public function __construct(float|int|null|string $minimum, float|int|null|string $maximum)
    {
        if (is_string($minimum) && !is_numeric($minimum)) {
            throw new \InvalidArgumentException('Minimum value must be numeric');
        } else {
            $minimum = (float)$minimum;
        }
        if (is_string($maximum) && !is_numeric($maximum)) {
            throw new \InvalidArgumentException('Maximum value must be numeric');
        } else {
            $maximum = (float)$maximum;
        }
        $this->minimum = $minimum;
        $this->maximum = $maximum;

        $this->markMeDirty();
    }
```

**Comment by Brainshaker95** [comment]
This seems like the correct fix to me.  
Does `QuantityValueRange` have the same issue? I have never used it but looks very similar at first glance.
I will happily provide that as a PR if the maintainers give their go.

**Comment by mattamon** [comment]
@Brainshaker95 sorry that I have to disagree on this solution. 
Throwing exceptions and if/else constructs in the constructor seems very off for me. 
This would only fix symptoms that should not be there in the first place. 

Let's fix it where the problem actually occurs while fetching the data.
https://github.com/pimcore/pimcore/blob/11.x/models/DataObject/ClassDefinition/Data/NumericRange.php#L240

```php
public function getDataFromResource(mixed $data, DataObject\Concrete $object = null, array $params = []): ?DataObject\Data\NumericRange
{
    if (isset($data[$this->getName() . '__minimum'], $data[$this->getName() . '__maximum'])) {
        $minimum = $data[$this->getName() . '__minimum'];
        $maximum = $data[$this->getName() . '__maximum'];

        if(is_string($minimum) || is_string($maximum)) {
            $minimum = (float) $minimum;
            $maximum = (float) $maximum;
        }

        $numericRange = new DataObject\Data\NumericRange(
            $minimum,
            $maximum
        );

        if (isset($params['owner'])) {
            $numericRange->_setOwner($params['owner']);
            $numericRange->_setOwnerFieldname($params['fieldname']);
            $numericRange->_setOwnerLanguage($params['language'] ?? null);
        }

        return $numericRange;
    }

    return null;
}
```

@tmannherz can you test if this also fixes your problem. When I tested it, I had no problems while saving and reloading the object.

**Comment by tmannherz** [comment]
@mattamon yes that change fixes the issue on my setup.

**Comment by mattamon** [comment]
> @mattamon yes that change fixes the issue on my setup.

perfect! @Brainshaker95 if you still want to provide a PR, please refer to the solution I suggested :) Thank you in advance!

**Comment by Brainshaker95** [comment]
@mattamon Thanks for your feedback, it is appreciated. My solution would not have been the exact same one as the one suggested (regarding the Exceptions). I would have just cast the incoming data since the cases checked by the if-statements would always be true except for the null case. For this one I thought it would be fine to just use 0 in that case. But you are totally right, this would not have fixed the root cause of this issue.
Anyway :) I am still interested in providing a PR for this.

**Comment by mattamon** [comment]
> @mattamon Thanks for your feedback, it is appreciated. My solution would not have been the exact same one as the one suggested (regarding the Exceptions). I would have just cast the incoming data since the cases checked by the if-statements would always be true except for the null case. For this one I thought it would be fine to just use 0 in that case. But you are totally right, this would not have fixed the root cause of this issue. Anyway :) I am still interested in providing a PR for this.

Ah I see, yes that also would have made a lot of sense. My problem was just that I do not want to open up  the constructor more than it needs to be. Adding another type just to cast it feels like a workaround for me.
The fix I provided above, is also not ideal, because somehow the data is a string in the array. So I guess there would be even a more ideal place to fix the root cause, while retrieving the data from the DB. 

We are always happy with PRs! :) You can also just tag me in the PR so I can have a look if you want to! :)

**Comment by Brainshaker95** [comment]
I only just realized that casting to a float would potentially lead to a loss of precision.  
It's fine while [storing the data](https://github.com/pimcore/pimcore/blob/v11.4.1/models/DataObject/ClassDefinition/Data/NumericRange.php#L207), but retrieving it as a string and then casting it to a float would technically not be correct.  
Do we just ignore that and at least bring the feature back to a working state (when using decimal precision) or do we prefer different approaches?  
I am not sure what would be best here, that's why I'm asking.  
The [Decimal class](https://github.com/pimcore/ecommerce-framework-bundle/blob/v1.2.1/src/Type/Decimal.php) from the ecommerce framework bundle comes to mind, but implementing something like that would open a whole can of worms.

Edit:
After some more investigating I found out that the `decimalPrecision` is implemented in various different ways across the different types of `Data`. Not sure what to make of that yet, just an observation that might be worth sharing.

```
Numeric            -> string
NumericRange       -> decimal(<precision>, <scale>)
QuantityValue      -> bigint(20)
QuantityValueRange -> double
Slider             -> double
```

**Comment by mattamon** [comment]
@Brainshaker95 you are right, casting to float will cause loss of precision. 
I really depends on he PHP initial settings, but for me at least it was fine up until 12 decimal places.
However I do not think that for a NumericRange you will need that much precision.

**Comment by Brainshaker95** [comment]
@mattamon I think you're right, I too have never needed this much precision. I would assume that this precision loss was always present since the strings where just implicitly cast to floats anyway when not using `strict_types` and calling `range` with them for example.  
I have added a PR with basically the same solution as the one you proposed.

**Comment by mattamon** [comment]
@Brainshaker95 did you maybe also check QuantityValueRange as you mentioned it?

**Comment by Brainshaker95** [comment]
@mattamon Yes I did and I couldn't reproduce the issue for that one. I think it works because the underlying field type is `double`.

**Comment by mattamon** [comment]
> [@mattamon](https://github.com/mattamon) Yes I did and I couldn't reproduce the issue for that one. I think it works because the underlying field type is `double`.

Perfect! Thank you for your support!
