### ISSUE TITLE
[Bug]: Pimcore Search return inaccurate results.

### ISSUE THREAD

**Issue by abdelrhmanyosry** [pimcore/pimcore#17737]
### Pimcore version

11

### Steps to reproduce

click on the folder and use the search bar to find an object using its key. 
![Image](https://github.com/user-attachments/assets/935791c9-14d0-4d75-94d5-751dcba15adf)
![Image](https://github.com/user-attachments/assets/22353d76-64d3-4da1-82c9-3afa2e11b68c)
![Image](https://github.com/user-attachments/assets/27b840e9-2a9f-4df0-ab76-ee0750d7d17c)

### Actual Behavior

for some sku keys i got the right objects for others i got the wrong objects 

### Expected Behavior

i should get exactly the  objects with similar SKU keys

**Comment by brusch** [comment]
This actually has to do with the way how the full-text search in boolean mode is implemented. 
When you'd like to use an exact search term, you have to warp your keyword in `"`. 
You case is somehow a bit an edge-case, because the SKU is structured by `-` which is splitted up by the tokenizer of the InnoDB indexer into e.g. `SWLUX-MM21`  -> `SWLUX` and `MM21`. 
Also you have to consider the min token length, which is by default 3, that means that the SKU `CUP-18-RC` is indexed as `CUP`, while `18` and `RC` is too short and is not getting indexed. 

See also: 
https://mariadb.com/kb/en/full-text-index-overview/#in-boolean-mode
https://mariadb.com/kb/en/full-text-index-overview/#:~:text=Partial%20words%20are%20excluded.,stored%20in%20the%20fulltext%20index.

So for your case this means, either using `"` or you use the filters in the headers, which are using `LIKE` instead of `MATCH AGAINST` (full text).

**Comment by abdelrhmanyosry** [comment]
thankyou! @brusch  it work
