### ISSUE TITLE
Add OCR when parsing asset (PDF, images, ...)

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#179]
Currently, asset PDF, Word, XLS, etc. are converted into PDF and after the text is extracted to be put in the database for the full text search admin.
I don't know if there is possibility to make OCR during this process (desactivated by default from system settings because could be ressource hug i imagine).
So for instance, upload scanned document (i thing a PDF which has been signed by a customer, and after scanned and uploaded in Pimcore, text should be easily for OCR as it is machine text and not hand written text...). 

Could be really great for lawyer, contractor, .... documents : )
More and more company are going the way to scan documents and put them in the cloud, so going this direction of OCR add a great value to Pimcore search capabilities.

Best regards.

Yivan added a comment - 18/Jun/15 2:44 PM
By OCR, i mean ROC (optical character recognition)
Bernhard Rusch added a comment - 10/Jul/15 2:58 PM
Are there any good open source cross platform libraries which we can utilize?
  
Yivan added a comment - 13/Jul/15 3:55 PM

I made some research on it. 
Tesseract is the best free option I think. It is included on the native linux repository, and is well maintened by community: 
https://github.com/tesseract-ocr/tesseract 
It has been compiled for Windows too and is compatible Mac too, so cross-plateform. 

It works in command line: 
   tesseract image.jpg outpout.txt [options] 
So it can be integrated in the pimcore workflow (Document -> Image (already exist for document thumbnail) -> Txt (tesseract) -> Parse the txt and save in the search table in database (already exist as txt )). 

You can get more information here: 
Official project page: https://github.com/tesseract-ocr/tesseract 
Detailled information about installation, optimisation, etc. : http://williamjturkel.net/2013/07/06/doing-ocr-using-command-line-tools-in-linux/ 
Possibility to improve OCR quality; http://vbridge.co.uk/2012/11/05/how-we-tuned-tesseract-to-perform-as-well-as-a-commercial-ocr-package/ 

For this last link, it is showed that changing the contrast, or other filter by preprocessing the image can improve the OCR recognition. 
I think it is better to keep Tesseract with native best/recommanded option, but add in the system config the possibility to configure a pimcore thumbnail filter for OCR so user can use native pimcore filter to change image quality to improve OCR (change output quality, contrast, color, etc.). 
Maybe as extra option, check if "textcleaner" program (this is the command line program used in the third link to improve OCR) is installed on the system a check box to activate it or not before OCR. 

All of this will make Pimcore a great tool for OCR as it will compete with professional and expensive OCR document management. 

One very good use too, will be that the user could find directly image containing specific text! So great for a DAM : ) 
Bernhard Rusch added a comment - 14/Jul/15 8:31 AM
Thanks for your feedback. Have you tried tesseract with some of your assets? Can you confirm it's working almost perfectly and acn really compete with commercial solutions?

**Comment by Yivan** [comment]
No I didn't have tried it with many assets, so I cannot confirm it from my experience. I try it just to test with somes documents and i comfirm it works and make OCR, but i cannot compare with other paid solutions. I suggested it too because i made some web search, and this seems to be the only linux open-source software to compete with paid solution. As this is the only one, i think you really can have a go with it (implementing a paying/propriary solution would be a lot more useless for many people).
From my search, as i explained before, it work easily from command line like you work for other binary external package in Pimcore (office, jpeg optimisation, etc.), so it would be consistent with actual implemntation. And many post on the web confirm it is the only best free solution.

Concerning asset typologie for OCR, each user can have different type of document (depending scanning method, config etc.). That is why i suggested to use an image thumbnail filter to offer the possibilty to the user to pre-filter before scan so a can improve contrast, reduce noise/blurring (maybe their will be need to add some filter in the image pipeline). In the system config, user could configure a thumbnail preset in the OCR settings. With this possibility i am confident user can compete with commercial OCR as Tesseract seems to make a wonderfull job.

Hope it helps,

Best regards.

**Comment by brusch** [comment]
Should be done using a plugin: https://github.com/pimcore/pimcore/issues/662#issuecomment-227134395
