### ISSUE TITLE
Filter for Metadata

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#186]

**Comment by jigna121** [comment]
How To Create 3D Floor Plan For My Coming 3D Floor Plan Project?

Dear Sir, 
Thanks For Registration. Your Site Is Very Helpful For Promote Our Idea.   
My Name is Avni . I Have been Animating Since 2010. Our Studio Have Created Normal 3D Architectural Animation project. I Want to Do something new in my next 3D Floor Plan Project. Please Suggest Me best Tutorials. 

http://www.3d-architectural-rendering.com/3D-Floor-Plan.html

**Comment by weisswurstkanone** [comment]
closed in favour of https://github.com/pimcore/pimcore/issues/186
