### ISSUE TITLE
Permission problem for Object Relations and (Multi-)Hrefs

### ISSUE THREAD

**Issue by camico** [pimcore/pimcore#1943]
# Bug Report
I think there is an issue with non-owner relations, normal relations and (multi-)hrefs: On the object page of the object containing the relation, ALL linked objects are listed without considering the current user's permission in the tree path (as set up in User -> Workspaces -> Data Objects).

### Expected behavior 
Objects that are filed within a path without view permission should not be visible.

### Actual behavior
They are visible, although cannot be opened.
When trying to open them with the little arrow button, there is a JS error:

`TypeError: Cannot read property 'o_type' of undefined` in 
```
addTab: function () {

        // icon class
        var iconClass = this.data.general.o_type == "variant" ? "pimcore_icon_variant" : " pimcore_icon_object";
...
```

**Comment by brusch** [comment]
I guess the same happens also when using normal relations (needs to be verified). 
Imho this is the correct behavior, because all relations fields are content in a way, and if a user is able to see  the content of a field, it should be the entire content, and not just a part of it. 
Consider the case when a user sees only half of the relations for a specific field, then he adds another new relation and deletes 2 existing relations and hits the save button. What happens with the relations he couldn't see because of missing permissions? He was expecting to see the entire content and changed it the way he was thinking it is right. I don't think it's a good idea to make somehow a magic behind the scenes which only causes the user to get confused.

**Comment by camico** [comment]
Thank you for your consideration. You're right, it happens for "owner" object relations and multi-hrefs as well.

However, I still think it may not be perfectly expected behavior. (While it is totally possible we are using pimcore in a way it is not really meant to be used...)

My case is, what if sharing the same PIM / data model in a multi-tenancy situation? Content of other customers (maybe even competitors) would be visible for anyone. And the permission management already allows for fine-grained restrictions by path, which as far as I can see at the moment, already covers all cases except this one.

As for your example, I would say all the relations he does not have permission for, must be handled transparently in the background, if at all necessary, and cannot be seen/touched/modified by him. So things he cannot see, should not have potential to confuse him ;)
(While I realize things may get a bit dubious when there is "max. items" set for example...but this could also be communicated with a specific warning)

**Comment by brusch** [comment]
I disagree ... content is content, no matter if the content are relations or not. 
For your use-case you may consider using custom layouts and hide the fields with the relations the user/role shouldn't see at all.
