### ISSUE TITLE
[Translator] Config option for case-insensitive translation keys

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#1980]
In v4 translations where case-insensitive but in v5 we followed Symfony's case sensitive implementation. 
Currently there's no best practice how to migrate hundreds or even thousands of translations with case incompatibilities. 

- Option 1: providing an case-insensitive compatibility-layer
- Option 2: migration script (maybe as part of https://github.com/pimcore/pimcore-cli ?)

**Comment by brusch** [comment]
+ Docs (as part of the migration guides)

**Comment by fashxp** [comment]
docs are already there: https://github.com/pimcore/pimcore/blob/master/doc/Development_Documentation/23_Installation_and_Upgrade/09_Upgrade_Notes/02_V4_to_V5.md#translations-shared--admin

migration script might be challenging since translation keys are often created dynamically ... so you never know which case-variants you might need...

**Comment by brusch** [comment]
- docs: yep, I know - i meant a documentation how to migrate, once we have a solution for that
- migration script: yep, I know. Maybe transforming all keys to lowercase (which are affected) is a proper solution (not 100% safe, but much better than manually migration thousands of keys :)).

**Comment by maff** [comment]
Implemented in #2005
