### ISSUE TITLE
->save() will null password field on object

### ISSUE THREAD

**Issue by TPETb** [pimcore/pimcore#199]
* Load an object that has a password field (e.g. getById)
* Update some fields you want ($object->setMyField1())
* $object->save()

No password-type fields of an object are nullified.

I presume this happens because getter of a password field will always return null (which is good) but then hydrator will still call it to compose sql update query.

Need some mechanism to mark fields that do not need to be updated or only update those fields that where forcefully updated with setter.

**Comment by brusch** [comment]
Sorry, this is not reproducible on our test environments. 

I was using the following script: 
```php
$obj = Object::getById(48);
$obj->setTxt(uniqid());
$obj->save();
```

and the following 2 different configurations of the password field: 
![image](https://cloud.githubusercontent.com/assets/142037/8901462/4f0a8940-3449-11e5-8ae5-be8b02e52f98.png)

![image](https://cloud.githubusercontent.com/assets/142037/8901466/5c3a5eec-3449-11e5-8f69-e5a4d347af4e.png)

In both cases I didn't see any problem. 

Please share your field configuration and a code snippet with u so that we are able to reproduce the problem on our end. 

Thanks!

**Comment by TPETb** [comment]
Will do some additional tests today. Will post results.

**Comment by brusch** [comment]
Thanks!

**Comment by TPETb** [comment]
Guess I need to apologise. When I ran very simple test environment, with anything apart object->save code disabled, the issue didn't appear. 

Looks like I missed something
