### ISSUE TITLE
[Pimcore 4][QuantityValue] currently fixed to 2 decimal places

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#2034]
Should be either configurable or "umlimited" decimal places should be allowed.

**Comment by weisswurstkanone** [comment]
build 4102

**Comment by Yivan** [comment]
@weisswurstkanone @markus-moser 
I made some time ago a pull request to make identical number and quantity value for choosing decimal precision, integer, etc.
It worked ok on Pimcore 4, but as i am not expert of Pimcore 5, i can not provide a pull request for Pimcore 5 now.
Maybe you can start back from my PR for Pimcore 4 and make a Pimcore 5 version.
Here is the PR: https://github.com/pimcore/pimcore/pull/845
It will make coherence between quantity value and number by providing same settings (actually we don't use a lot quantity value because we cannot fix so many settings than number)

**Comment by weisswurstkanone** [comment]
The idea is to streamline it with the numeric data type in 5.1 anyway. But since we needed a quick solution for the precision also in in pimcore 4 I only worked on that part since decimal precision is fixed there to the default of 2. So you couldn't enter numbers like 0.123

Created a new issue
https://github.com/pimcore/pimcore/issues/2035

and mentioned your PR.

Many thanks!
