### ISSUE TITLE
Asset Cleanup Wizard

### ISSUE THREAD

**Issue by ckemptner** [pimcore/pimcore#2125]
Make it possible to clean up assets, which are not used anymore (= have no dependencies) and at the same time delete any empty folders in the assets tab.

-> Located in "Advanced" - "Clean Up" 

-> Like a Wizard, which is showing Asset Grid and Additional Information like 
* Preview image 
* Date when asset was uploaded 
* Date when asset was last used in document or object (empty if never used) 
* De-Select assets which should not be deleted 

-> Show before cleanup how many assets and folders will be deleted 
-> Show after cleanup how many assets and folders were deleted (+ total file size)

**Comment by Cruiser13** [comment]
I like that idea. We wrote a little cron script which does the cleanup for unused old assets once in a while but the admin gui solution sounds nice.

**Comment by Pitu-pl** [comment]
@brusch @weisswurstkanone what do you think about this feature in Core code? 
I can make it in a core code or standalone bundle.
I want to make:
- command to update asset with information about using
- command to remove all unused assets
- add to assets list information: used (document/object ID) / unused
- add to cache option: clear unused assets

**Comment by brusch** [comment]
@Pitu-pl yep, in my opinion this would be a good addition to the core and we're always happy to get PRs ;) 
But first we should discuss some details to have a common understanding of the feature. 

> command to update asset with information about using 
Imho, this information is already there in the `dependencies` table or are you talking about something different? 

> add to assets list information: used (document/object ID) / unused
You mean in the following list: 
![image](https://user-images.githubusercontent.com/142037/40915720-686dc07e-67fd-11e8-8349-e7dd4ccd95aa.png)
I'd only display the total amount of how often an asset is used, it doesn't make sense to list here all documents, assets and objects, because that list can be quite huge. 

> add to cache option: clear unused assets
You mean cleaning unused assets from `var/tmp`? I don't think this makes sense, since all related temporary content is cleaned anyway when deleting an asset.

**Comment by Pitu-pl** [comment]
@brusch 
Thanks for the answer.

1. OK I will list on the list count only or empty if asset is unused
2. About clear unused assets, I mean remove files(from disk). In one click we will remove all assets from server. Maybe this option will in another tab than `cache option`.

**Comment by brusch** [comment]
1. it should be also possible to sort the list by the amount of usages 
2. you mean you'd like to provide the clear functionality also in the admin UI? I wouldn't do so, this process can take quite a long time and should be a background task (command).

**Comment by brusch** [comment]
Resolved by #4222
