### ISSUE TITLE
Add a check to the installer to verify that the rdbms supports fulltext indices on innodb tables

### ISSUE THREAD

**Issue by HaaseIT** [pimcore/pimcore#2255]
# Bug Report
The installer will fail, if fulltext indices are not supported on innodb tables with pimcore 5

### Expected behavior 
Installer checks for proper mysql/mariadb version
  
### Actual behavior
Installer fails if fulltext indices are not supported on innodb tables by rdbms
  
### Steps to reproduce  
Use installer with rdbms that doesn't support fulltext indices with innodb tables

**Comment by bbak** [comment]
InnoDB Fulltext Indices [arrived in MySQL in Version 5.6.4](https://dev.mysql.com/doc/relnotes/mysql/5.6/en/news-5-6-4.html#mysqld-5-6-4-innodb) in Dec. 2011. 
So, maybe it would easier to be more specific in the System Requirements and state "MySQL 5.6 GA or compatible", since the first "general availability" (GA) release was MySQL 5.6.10. I assume this was the intention anyway.

**Comment by HaaseIT** [comment]
Easier for sure, I still think checking this along with the other requierements in the installer would make things easier for people setting pimcore up.

I for an example had to drop the database, then search the project for the config files, delete them because it would not let me do a fresh install without doing that since I had to use a different database server than the one now hardcoded in the config.

**Comment by brusch** [comment]
Updating docs + version check in installer.
