### ISSUE TITLE
[Pimcore 5] Linked object in application logger don't open on click

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#2315]
On Pimcore 5, in the GUI, on the application logger:
if an object is linked to the log (ie `relatedObject`), clicking on the link don't open the object panel.

The ajax url called is `/admin/element/get-subtype?_dc=1512516306248&id=300&type=`, it seems it missed the last parameter which should be `type=object` i think.

![app-log](https://user-images.githubusercontent.com/9025839/33636704-a59c1f5e-da1d-11e7-9d2d-13d9b5b22316.png)

**Comment by maff** [comment]
Thanks for reporting! This regression was introduced in #2153, but only applies when logging the related object as numeric ID (as the `ApplicationLogger` class does). This results in the `relatedobjecttype` column being empty and the UI not being able to resolve what kind of object we're dealing with.

Unfortunately we can't guess the object type when the column is missing, so for records already written there is no other fix than manually updating the `relatedobjecttype` column to set `object`, `document` or `asset` if you know the type you're dealing with.

Fixed in fea78d2.

**Comment by Yivan** [comment]
Great thanks for the fix.
I was thinking only object can be linked (only object are shown here https://pimcore.com/docs/5.0.x/Development_Documentation/Tools_and_Features/Application_Logger.html and no other detail is given about `relatedObject `context parameter). Typo of name induce me in error. It should have been `relatedElement` and in the GUI popin `Related element`. But as you talk of `File object` too on the popin i think `object` si to take on the general meaning (and not Pimcore object).

**Comment by Yivan** [comment]
@maff I should just add that the code i was using was:
```
$logger->error("Cannot update object id {$object->getId()}", [
    'relatedObject' => $object
]);
```
So i already give the full object as `relatedObject ` parameter when i had the problem. Is it intended even if i didn't give the full object and not the numeric ID ? So `relatedObjectType` seems mandatory and should be added to documentation ?

**Comment by maff** [comment]
The `$logger` is an instance of `ApplicationLogger` right? Since #2153 the `ApplicationLogger` itself delegates most handling to the monolog handler, but treats objects a little different than when logging directly into monolog. When logging via `ApplicationLogger` the related object type was lost since #2153 (fixed in the commit mentioned above).

With the fix above the `relatedObjectType` is again correctly resolved in all types of use - you don't need to pass it manually.

**Comment by Yivan** [comment]
Yes yes are right should work with the fix! Thanks again.
