### ISSUE TITLE
Rework view property setting

### ISSUE THREAD

**Issue by SmashingQuasar** [pimcore/pimcore#2322]
Hello,

I found a weird behavior in Pimcore 5.x.

In Pimcore 4.x, the following code should output 'test'.

```php
<?php
    $this->view->object = [
	'name' => $object->getName(),
	'image' => $object->getImage(),
	'link' => []
    ];

    $this->view->object['link'] = ['test'];

    echo $this->view->object['link'][0];

?>
```

In Pimcore 5.x it outputs NULL.

This is because it doesn't recognize properly the context of setting/getting the property, which wasn't the case in Pimcore 4.x.

If you use a transitory variable, then it works, the following will output 'test' in both Pimcore 4.x and Pimcore 5.x.

```php
<?php
    $this->view->object = [
	'name' => $object->getName(),
	'image' => $object->getImage(),
	'link' => []
    ];

    $object = [
        'name' => $object->getName(),
        'image' => $object->getImage(),
        'link' => ['test']
    ];

    $this->view->object = $object;

    echo $this->view->object['link'][0];

?>
```

**Comment by dpfaffenbauer** [comment]
I wouldn't use ```$this->view->object``` in Pimcore 5 anyway, that's not Symfony standard, that's just an addition Pimcore added to make it easier to migrate stuff. I always use it like this:

```
public function widgetAction(Request $request)
    {
        return $this->renderTemplate('CoreShopFrontendBundle:Cart:_widget.html.twig', [
            'cart' => $this->getCart(),
        ]);
    }
```

**Comment by brusch** [comment]
Unfortunately we can't fix that problem since this is an indirect modification of an overloaded property, which has actually no effect on the already existing value in the parameter bag. 

So I'd suggest to use a private variable instead, once all your modifications on the array are done, you can set it it as a parameter, either by using `$this->view->object = $object` or the standard Symfony approach which @dpfaffenbauer suggested above.
