### ISSUE TITLE
clearing pimcore cache is broken since 5.1.1

### ISSUE THREAD

**Issue by cadeyrn** [pimcore/pimcore#2482]
# Bug Report

Clearing the Pimcore cache via administration is broken in Pimcore 5.1.1. It works as expected in Pimcore 5.1.0.

### Steps to reproduce  

1. make changes on your code
2. Settings > Cache > Clear Cache
3. try to verify your changes in non-debug mode on other devices

### Expected behavior 

The cache is cleared, code changes are visible on all devices in non-debug mode.
  
### Actual behavior  

The cache is **not** cleared, code changes are **not** visible on all devices in non-debug mode.

### Workaround

Clearing the cache still works via the command line:
php bin/console cache:clear

**Comment by maff** [comment]
Due to the way the cache directory was restructured in Symfony 3.4, we had to make a couple of adaptions to the cache clearing process. In Pimcore 5.1.1, clearing the cache does so only for the current environment, so if you clear the cache in debug-mode, this only affects the `dev` environment.

https://github.com/pimcore/pimcore/pull/2502 introduces a more granular way to clear the cache - you can now explicitely choose which of the default environments to clear, either all of them or specifically `dev`/`prod`.
