### ISSUE TITLE
Error at merging the security config in the PimcoreCoreExtension file

### ISSUE THREAD

**Issue by davidhoeck** [pimcore/pimcore#2521]
haven't changed anything in the security.yml files. After a composer update I had the error in the PimcoreCoreExtension. I checked all the config files, removed all bundles from the AppKernel. nothing solved the problem.

the CLI output 
```
Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to Pimcore\Tool\ArrayUtils::arrayMergeRecursiveDistinct() must be of the type array, null given, called in /var/www/html/pimcore/lib/Pimcore/Bundle/CoreBundle/DependencyInjection/PimcoreCoreExtension.php on line 483 in /var/www/html/pimcore/lib/Pimcore/Tool/ArrayUtils.php:33
Stack trace:
#0 /var/www/html/pimcore/lib/Pimcore/Bundle/CoreBundle/DependencyInjection/PimcoreCoreExtension.php(483): Pimcore\Tool\ArrayUtils::arrayMergeRecursiveDistinct(Array, NULL)
#1 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php(43): Pimcore\Bundle\CoreBundle\DependencyInjection\PimcoreCoreExtension->prepend(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#2 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/MergeExtensionConfigurationPass.php(39): Symfony\Component\DependencyInjection\Compiler\MergeExtensionCo in /var/www/html/pimcore/lib/Pimcore/Tool/ArrayUtils.php on line 33
                                                                                                         
```

**Comment by dpfaffenbauer** [comment]
have the same issues running unit-tests on CoreShop: https://travis-ci.org/coreshop/CoreShop/jobs/334821342

**Comment by dpfaffenbauer** [comment]
also happens to non coreshop related projects

**Comment by maff** [comment]
Seems to be related to Symfony 3.4.4. Please stick to 3.4.3 until this is sorted out.

**Comment by maff** [comment]
Fixed in build 189. Unfortunately, it's necessary to either set the `symfony/symfony` dependency to 3.4.3 in your `composer.json` or to patch your installation with https://github.com/pimcore/pimcore/commit/7d6c2168bebe2ada7be66c1af9ad1d07719843fe to be able to upgrade.

**Comment by dpfaffenbauer** [comment]
Whats even the point of merging security configs anyway?

**Comment by maff** [comment]
Symfony by default only allows to define the security config in a single file (see e.g. https://github.com/symfony/symfony/issues/25021). This works fine when building a Symfony application from scratch as you have full control over the config but for a platform like Pimcore this makes the security system unusable, because we need to define the admin security config from the core and have additional configs coming from bundles (e.g. from the DAM bundle). That's why we circumvent this limitation with a hack by merging the security config into a single one before it is handled by the Config component.

Not doing so would demand from the user to add its security config to a global config file containing the admin security + copying and maintaining every security config manually from bundles providing some kind of secure area (as the DAM).

**Comment by dpfaffenbauer** [comment]
Alright, sounds like a good point :)
