### ISSUE TITLE
[Versions] Config option to disable the use of hardlinks

### ISSUE THREAD

**Issue by RuudvdvNB** [pimcore/pimcore#2734]
### Problem
At our company we use DirectAdmin as control panel for our servers. In DirectAdmin version 1.351 two new options have been added, one of them is 'backup_hard_link_check=1' and stops the back-up creation when hard links are found for the specific user.

We are currently updating customer websites to Pimcore 5 and noticed that the back-ups of these websites are failing. After some research we noticed a Pimcore improvement #2491. 

Ofcourse we can disable the hardlink check in DirectAdmin, but this is not a preferred solution.

### Preferred solution
The preferred solution for us would be to have a system setting to switch between a symbolic- or hardlink creation for Asset versioning.

**Comment by brusch** [comment]
Unfortunately symbolic links cannot be used instead of hardlinks in this case, this would need many additional logic in Pimcore to avoid the deletion of still required data elsewhere. This is the only point why we used hardlinks here, so that we don't have to care about that :) 

We can discuss about a config option to disable this hardlink functionality but we're definitely not reconstructing the functionality of hardlinks in Pimcore :)

**Comment by RuudvdvNB** [comment]
If the hardlink function can be disabled, we don't have to worry about the failing back-ups and possible security flaws. So please discuss that option 👍

**Comment by RuudvdvNB** [comment]
@brusch is there a chance that the option to disable hardlinks will be implemented?

**Comment by RuudvdvNB** [comment]
@brusch great! But you did close this issue? ;)

**Comment by brusch** [comment]
Oh, I'm so sorry - it's Friday ;-) 
Thanks

**Comment by brusch** [comment]
To disable the use of hardlinks use the following option in your `config.yml`: 

```yaml
pimcore:
    assets:
        versions:
            use_hardlinks: false
```

See also: 
https://github.com/pimcore/pimcore/blob/324b923f1dfc2e085e1e9d13ed4a82ecc7f1ba08/app/config/config.yml#L57
