### ISSUE TITLE
Unable to install Pimcore5 in Windows

### ISSUE THREAD

**Issue by vinitchopra12** [pimcore/pimcore#2754]
I am facing an issue with Pimcore Installation in my Local Window Machine.  I am not getting any error but after clicking on Install Now! it keeps showing the installing.. screen and later redirect to the install screen. 

I have also checked the database but there is no tables are created. The log folder is also empty. 

I am wondering whether is any issue in setting up VirtualHost in Apache. Below is my code in httpd-vhosts.conf.

```
<VirtualHost pimcore.local:80>
    ServerAdmin admin@localhost.com
    DocumentRoot "C:/xampp/htdocs/pimcore/web" 
    ServerName pimcore.local
	ServerAlias www.pimcore.local
    <Directory "C:/xampp/htdocs/pimcore/web">
        AllowOverride All
		Order allow,deny
		Allow from all
    </Directory>
</VirtualHost>

```
Also, when I list the command through bin/console it crash the cmd or getting Segmentation Fault error.

**Comment by sandra-walker** [comment]
yeah since V5 the installation changed a little bit. it seems you are working with xampp. we already had problems with xampp. may should have a look on vagrant. also in the pimcore documentation:

https://pimcore.com/docs/5.x/Development_Documentation/Getting_Started/Homestead_Vagrant_Development_Setup.html

https://www.vagrantup.com/

or if you wanna go for the lazy way, install the pimcore stack with "one-click-install"
https://bitnami.com/stack/pimcore

**Comment by brusch** [comment]
Have you checked if all system requirements are met on the system? 
You can also check dem before performing the actual install. 
Please also check the error log of apache. 
In general Pimcore should run fine on Windows and on XAMPP.

**Comment by brusch** [comment]
closed due to inactivity
