### ISSUE TITLE
New Object Modal - custom text

### ISSUE THREAD

**Issue by dAmihl** [pimcore/pimcore#2772]
Generally my question is: 
Is it possible to add custom text to the New Object Modal window based on the Class?
![image](https://user-images.githubusercontent.com/10024782/38727357-125956ee-3f0d-11e8-80a6-263fb3084dc6.png)

It would be nice to be able to add custom hint-texts to the Base definition of a Pimcore Class to display within this modal.
If there is no method currently (as I mentioned I couldn't find anything related), here's my feature request:

## Feature description 
I want to be able to add custom text to a base definition of a given class to be displayed within the "Create New Object" modal.
This should open up the ability to e.g. directly add naming conventions for users to remember, or add a reminder to users to make sure a similar object does not already exist, etc.
![image](https://user-images.githubusercontent.com/10024782/38727664-f2f2bb28-3f0d-11e8-96bf-27c79a24ee34.png)
The custom text could be displayed in italic below the input field.

**Comment by brusch** [comment]
I'd prefer a solution based on admin translations, to have the possibility to localize it. 

### Example 
The dialog looks for a translation key with a specific schema, eg. `object_add_dialog_custom_text.className`.  If this translations key does exist the text gets displayed, otherwise not. 
To define a custom text, eg. for the class `MyCustomClass` you'd have to define the admin translation key `object_add_dialog_custom_text.MyCustomClass`. 

What do you think?

**Comment by dAmihl** [comment]
Hi brusch! Thanks for picking up my feature request.
Your idea seems a lot cleaner than mine. This would allow us to even add localized custom text to the Create Object dialog. I like it.
