### ISSUE TITLE
FFMPEG are from https://www.johnvansickle.com/ffmpeg/ are unavailable

### ISSUE THREAD

**Issue by yariksheptykin** [pimcore/pimcore#2851]
# Bug Report

Pre-build binaries are not available any longer for FFMpeg on https://www.johnvansickle.com/ffmpeg/. Project maintainer has decided to discontinue the service.
For most popular linux distros there exist system packages. See https://www.ffmpeg.org/download.html
Is there any good reason for not using the system package? Otherwise we could update the documentation page to point to the official download instructions.

**Comment by brusch** [comment]
Yep, there was/is a reason for not using the system packages, ... patents ;) 
Most (commonly used) codecs are not free and therefore not  license compatible with many Linux/GNU distributions, so the packages are compiled without them (eg mp4, ...). 

But since this static builds are not available anymore I've removed the sections out of the docs - thanks for the hint!
