### ISSUE TITLE
Document Restrictions for predefined Document Types

### ISSUE THREAD

**Issue by putzflorian** [pimcore/pimcore#2874]
# Feature Request 

Add the ability to add a restriction by predefined Document Types in Classes for Snippets and Pages

![restrictions](https://user-images.githubusercontent.com/1086343/40608213-140d1670-626b-11e8-8e6a-eaa7c0c40782.png)

**Comment by brusch** [comment]
Unfortunately this isn't possible, since the predefined document type isn't stored on the actual document, so the document itself doesn't know which kind of predefined document it is/was. 
Predefined documents are just a kind of convenience tool that assign certain settings to a document based on the configuration - but there's no permanent relation between the document type and the document.

**Comment by brusch** [comment]
Because of that fact it is also not possible to put a restriction on a field, because there's no such information on the document which the field could check against when a value get's assigned :(
