### ISSUE TITLE
Add install option to skip database 

### ISSUE THREAD

**Issue by mingfang** [pimcore/pimcore#3035]
I'm running Pimcore inside Kubernetes and in my Dockerfile I need an option to install a profile but skip all database access.

Currently there is an install option 
```--no-copy-profile-files                Do not copy any profile files. Just install DB structure```
This option is perfect when Pimcore starts up inside Kubernetes.

However when building the Docker image, I need a new option to compliment this.
I propose this option 
```--only-copy-profile-files                 Just copy any profile files. Do not install DB structure```
This should should do everything except make any database changes.

**Comment by romainp89** [comment]
I also validate this option ;)

**Comment by fashxp** [comment]
added two new options for installer: 
- skip-database-structure
- skip-database-data

see command help for details

**Comment by worp1900** [comment]
@fashxp just a question now about your changes:
I can specify both `--skip-database-X` flags like so:

          PIMCORE_INSTALL_MYSQL_USERNAME=username PIMCORE_INSTALL_MYSQL_PASSWORD=password ./vendor/bin/pimcore-install \
            --admin-username admin
            --admin-password admin \
            --mysql-database pimcore \
            --no-interaction \
            --skip-database-structure \
            --skip-database-data \
            --skip-database-data-dump

Now I'm assuming the setup process won't need a database at all. Still the install process tells me

    [ERROR] The following errors were encountered during installation
    Couldn't establish connection to MySQL: An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory

Is this intentional? I would figure if it setups neither db structure nor db data, why would it require the database connection? Is there some kind of mandatory database connection test? Or is something else performed on the database in addition to creating structure/data?

If so, would a flag like `--skip-database` be sensible?

I am asking all this as I'm running Pimcore on Docker in Swarm/Kubernetes and the automatic build Pipeline doesn't have connection to the production DB during build process.

**Comment by fashxp** [comment]
needs more digging where this exception comes from. 
In your context though I'm wondering why you need to run Pimcore installer at all?

**Comment by worp1900** [comment]
_In your context though I'm wondering why you need to run Pimcore installer at all?_

I haven't picked through the installer, a colleague just mentioned that it does more than just initiating a database. I will take the suggestion and check through the installer though. Thanks for the mention, this could solve my problem the easiest.

**Comment by fashxp** [comment]
as soon as you have database (which should be there) and config files (which should be in git and/or in shared file system) in place, there should be no need for running installer.

**Comment by worp1900** [comment]
Uh I like that answer. I will do some digging.
Thank you sir for answering, you have saved me a good chunk of work quite possibly =)

**Comment by abidmahmoodmughal** [comment]
Hi,
My project is using Pimcore 6.7.1 and it is already live, I have to make some changes in it and when i run the command like below 

D:\Pimcore\pimcore-project\vendor\bin>pimcore-install --ignore-existing-config --admin-username=hamza@xyz.com --admin-password=f1d1d8r1hdd --mysql-host-socket=172.xxx.xxx.xxx --mysql-username=admin --mysql-password=xb@3sJ2R --mysql-database=xyz-database --skip-database-structure=true --skip-database-data=true --skip-database-data-dump=true

When i run this command, instead of retaining old data, it empty whole database, please guide me what settings i will pass if i have to retain old live production database as well while running of the pimcore-install command
