### ISSUE TITLE
CSV export issue with some operators

### ISSUE THREAD

**Issue by psuhane** [pimcore/pimcore#3212]
When exporting CSV using operators 'Operator ObjectField Getter' or 'Operator Any Getter' it is giving only text 'Array' in CSV but it is showing correctly on the objects grid. Please refer following screens

Operators in grid configuration
![op](https://user-images.githubusercontent.com/12061880/44031094-8485e49e-9f20-11e8-946c-c8cdc0084398.png)

Data in grid
![grid](https://user-images.githubusercontent.com/12061880/44031104-8dcb6e48-9f20-11e8-9ef7-2f92ff4e409a.png)

Data in csv
![csv](https://user-images.githubusercontent.com/12061880/44031114-99f41c6a-9f20-11e8-8d84-6825f176ebda.png)

These operator are now very commonly used and this issue should resolved.

**Comment by weisswurstkanone** [comment]
Actually this is the default behavior (i.e. concatenating an array of strings with , as the glue) and is therefore a bit misleading - but still comfortable because you don't an additional operator.
If you want export your stuff wrap it into a concatenator operator.

![image](https://user-images.githubusercontent.com/6142086/46538863-58d83400-c8b5-11e8-863b-6aecf9d49983.png)
