### ISSUE TITLE
[Update] Support Migrations in Pimcore\Composer::prePackageUpdate()  

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#3359]
Sometimes it's necessary to do certain migrations before the sources of Pimcore are updated. 
Example: #3347

**Comment by dpfaffenbauer** [comment]
I don't think it is a good idea to introduce that again. With the current solution it is possible to Upgrade Pimcore 5.4 to 5.5 (or even 6.0, depends on BC breaks) with one deployment. Having `prePackageUpdates` again, introduces the same issue as with Pimcore pre 5.4 updates that migrations could ran into errors cause of that.

Why is it even necessary to have that?

**Comment by brusch** [comment]
see #3347 
That removes support for `mail` transport in swiftmailer, without having the possibility to change the config before the code get's updated, this will cause the update to fail (container cannot be built anymore).

**Comment by dpfaffenbauer** [comment]
Yes, and thats a BC break and needs manual changes. Every BC break needs manual interaction to resolve.

**Comment by brusch** [comment]
Why should using `prePackageUpdates` causing problems? What's the difference to the `postUpdate` migrations?

**Comment by dpfaffenbauer** [comment]
Cause its not possible to do `preUpdates` in a deployment process. there is no `preUpdate` there. And that causes inconsistencies with what Pimcore thinks is the way to update and what others think is the way to update. Having the possibility to do that again, requires a lot DEVS to adapt the deployment strategy again to somehow work with "preUpdates" without messing up anything. This also depends on what `preUpdates` actually do... But having the possibility to have them, will cause issues someday.

In the past, there have been `preUpdates` that HAD to be run before some `postUpdates` otherwise the `postUpdate` would fail. This also happens in a different process, like a container rebuild could happen, which would force most deployment strategies to do 2 deployments for one update. Which is quite a hassle when working on a feature for a longer period.

I mean, how do you deploy Pimcore updates? do you ssh into the server and ran a `composer update` to update Pimcore? Cause thats the only way this would make sense. 

For the specific example with **Swiftmailer**:
This wouldn't work in a deployment strategy anyway. Cause:

You can't version and the deploy the system.php of Pimcore, cause when somebody changes System settings on the STAGE or PROD Server in the Admin UI, and you deploy, you overwrite his settings. Therefore it has to be shared across releases and manual changes are needed as well. so there is a manual action needed. So, either way, this requires manual changes on the server. 

(Of course this also depends on how the deployment process works, but most are quite similar: `SSH`, `git pull`, `composer install`, `symlink shared files`, `run migrations`, `cache:warmup`)

When there is a BC break that needs manual interaction -> FINE. Having a proper CHANGELOG with all necessary steps to Update from Version X to Version Y would do the job. Or maybe also have a BC layer in order to support maybe both versions of that.

**Comment by brusch** [comment]
@dpfaffenbauer I agree
