### ISSUE TITLE
[GDPR Extractor] Consider entity permissions on actions

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#3443]
linked to #3441

pro: 
- user must not see data (data objects, sent mails, assets, etc.) he has no permission on

contra: 
- there might be more personal data stored for a certain person and information to that person might be incomplete

**Comment by markus-moser** [comment]
Quite a philosophical question.

In my opinion the gdpr data extractor needs to ensure that all the data for a customer gets extracted as otherwise the tool is useless. If someone is allowed to use the extractor he needs to be allowed to search everywhere as otherwise it's impossible to do the required job. So either show all the data or show an error message when more permissions are needed but do not provide a tool which would only provide parts of the data.

**Comment by brusch** [comment]
I fully agree with @markus-moser - the data extractor should at least list all the data records, if there are missing permissions for certain actions such as view/open/export or delete an error message should be shown on demand (i.e. when clicking a button in the result list).
