### ISSUE TITLE
[Versions] Object Version Preview & Document Version Comparison doesn't work

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#3504]

**Comment by suhl79** [comment]
Are you sure this bug was fixed. I've just installed version 5.5.4 and the Preview feature doesn't work:
![pimcore bug](https://user-images.githubusercontent.com/45366124/49029305-44f0d600-f172-11e8-8ec3-88cf130ccd78.jpg)

**Comment by brusch** [comment]
@suhl79 are you sure you're on the latest version? In both of our public demos everything is working fine.

**Comment by suhl79** [comment]
@brusch I'm using 5.5.4 I've installed few days ago. It happens when I try to import CSV file to objects and I try to preview the changes. It looks like the DataObject directory is double nested in itself. I mean the requested 
vendor/pimcore/pimcore/bundles/AdminBundle/Resources/views/Admin/DataObject/diffVersions.html.php file is actually localted in vendor/pimcore/pimcore/bundles/AdminBundle/Resources/views/Admin/DataObject/DataObject/diffVersions.html.php so when I copy both files in this directory to one level up the preview works as expected. I don't know if that's the case here. I'm not a professional PHP programmer.

**Comment by rbonfils** [comment]
Same for me.
In DataObjectHelperController.php, at line 1392, the template is called like this : 'PimcoreAdminBundle:Admin/DataObject:diffVersions.html.php', but the template directory is as follows: /AdminBundle/Resources/views/Admin/DataObject/DataObject/diffVersions.html.php

**Comment by rbonfils** [comment]
Reproduced on the demo : InvalidArgumentException: The template "PimcoreAdminBundle:Admin/DataObject:diffVersions.html.php" does not exist.

**Comment by KatrinAckermannEk** [comment]
If Wkhtmltoimage or Imagick are not installed, the path to the template is still incorrect and therefor throws an exception.
Is:
`return $this->render('PimcoreAdminBundle:Admin/Document:diff-versions-unsupported.html.php');`
Should be:
`return $this->render('PimcoreAdminBundle:Admin/Document/Document:diff-versions-unsupported.html.php');`

As seen in master https://github.com/pimcore/pimcore/blob/master/bundles/AdminBundle/Controller/Admin/Document/DocumentController.php:954
