### ISSUE TITLE
Modification timestamps in microseconds

### ISSUE THREAD

**Issue by BlackbitDevs** [pimcore/pimcore#3523]
Currently modification timestamp of data objects are saved as Unix timestamp (seconds since 1970-01-01). When an object gets saved multiple times within 1 second, multiple versions are marked as currently published. 
Moreover second-based timestamp leads to wrong results of \Pimcore\Model\Asset\Dao::__isBasedOnLatestData. 

Concrete example: We have an event handler for "pimcore.asset.postAdd". We want to assign the uploaded asset automatically to an object depending on the uploaded file's name. As uploading images via Drag and Drop or multi file upload runs in parallel there are multiple PHP processes editing the same object. In this case only some images are referenced to the object.

But this can also happen when lots of users access a website script which changes data.

**Comment by BlackbitNeueMedien** [comment]
Thanks for your reply. objects.o_versionCount really is a solution to identify if an object has changed in the meantime. But one problem stays: versionCount is only written to database after complete saving transaction finishes. When multiple processes write the same object, this will not help - even if $object->__isBasedOnLatestData() is called because when process 1 calls $object->save() there is no lock that only this process is allowed to write this object. When after process 1 calls save, process 2 also calls $object->save(), $object->o_versionCount is the same in both processes. So concurrency problems still exist.

**Comment by brusch** [comment]
@BlackbitNeueMedien you're absolutely right, thanks! 
My commit 856b7649911c8f8e571901e883ec47e8c035163c should fix that.
