### ISSUE TITLE
[ecommerce] Payment - implement separate initPayment call

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#3604]
Currently the CheckoutManager and OrderAgent provides a startPayment() (startOrderPayment()) method only. For some payment handlers (wirecard seamless, mpay24) this is not ideal as a unique payment ID is needed already when the payment method selection form needs to be displayed. So it could be needed to cancel and restart the payment for example on each payment method change.

A better approach would be to add a separate call to init a payment. This should create a new payment field collection entry but should not actually start the payment. Starting the payment then should be a second/separate step which can be called later.

**Comment by fashxp** [comment]
to specify: 
- when calling `initPayment` a payment info with state `payment pending` already exists - abort existing payment, or use existing one? 
- should `initPayment` abort existing payments when order finger print has changed? 


Todo OrderAgent: 

`initPayment`: 
- returns current payment info with current order finger print when exists (ev, with state checking) 
- abort existing payment info, when finger print has changed? 
- if no payment info exists, creates new payment info with current order finger print and payment state `INIT`

`startPayment`: 
- same as now with one extension
- if payment info exists (because it was created in `initPayment`), update state to `PAYMENT PENDING`

todo CheckoutManager: 

`startOrderPayment`:
- same as now

`initOrderPayment`:
- just call `initPayment`
- do not update any order state

**Comment by fashxp** [comment]
BC break in terms of changing interfaces
