### ISSUE TITLE
CLI Updater

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#373]
- Pimcore\Console job
- symfony PHP executable locator

**Comment by Pegasuz** [comment]
Nice!

**Comment by brusch** [comment]
`php pimcore/cli/console.php update -h`

**Comment by solverat** [comment]
wuhu! :thumbsup:

**Comment by solverat** [comment]
hey @brusch, first of all thanks for this fast improvement - great stuff!

i'm still searching for a good way to integrate that into my composer / phing deployment. 
the biggest problem i have is that i tried to trigger the update command after a composer update. 

so we define the recent build in the `required` section in `composer.json`:

```
"require": {
      "pimcore/pimcore": "dev-master#2b19fe357f46fd533be7e2d2372c575a7b0cb39b"
}
```

the problem is, after that update the command is obsolete, because pimcore believes it's already up to date: ```$currentRev = Version::$revision```. 

if i don't set the correct version in the `required` section but only trigger the `update -h` command, composer will reset that with the next `composer update`. so, the best solution would be: add a db-version to the system (like other cms systems) and split the update procedure into *"file update"* and *"db / system update"* and just trigger the db updates eg. just all the necessary `postupdates.php` if the *file update* is already up to date.

i know, thats a little bit confusing, but i hope you get my point. what do you think?

btw: beneath all this - i think we need a -f (force) command, so it's possible to force the `ConfirmationQuestion ` while updating via phing / bash script / eg., right?

**Comment by fashxp** [comment]
That won't help since you still have the problem I tried to describe in #366 - a composer update always gets you the last source base, but the update scripts might need a code base inbetween...

So updates need to be done with the updater logic - web or cli.

**Comment by solverat** [comment]
hey @fashxp. you're right, if the updater stays that way it's impossible to combine the composer philosophy with the updater logic. roughly said: at the moment the composer does not make any sense in pimcore. i can't update any dependencies (plugins etc) when using the updater, it would be to dangerous (update via updater, then manually update composer.json build nr., then update composer deps).

**Comment by jelofsson** [comment]
Hi, when deploying to our customer we would like to integrate the Pimcore update together with the deployment process. Therefore we also would like an -f (force) command.
