### ISSUE TITLE
[Object] Relation data types: single delete button instable

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#3733]
When using the non-owner object relation the delete buttons do not really work. If I delete a single item and wait until all ajax requests are completed it's ok. But if I press the delete button for example 5-6 times in a short period of time the Pimcore backend get's blocked and finally crashes with a massive amount of javascript errors.

**Comment by brusch** [comment]
All Many-To-Many * - relational data-types are affected.

**Comment by brusch** [comment]
@weisswurstkanone maybe you have an idea how to fix that? Just tried to fix it now for a while, but didn't find anything :( Thanks!

**Comment by bruenner-elements** [comment]
It seemed that there were other functions called, while `removeObject` made the first AJAX-request. These extjs-function had an negative effect on the extjs-event-cycle, because notify-remove-events were fired multiply times but only when you removed the first entry. 

By passing `async: false` as parameter into the first AJAX-Request the problem is gone with me (at least on chrome) 

Here is the patch: https://github.com/bruenner-elements/pimcore/commit/2c5949178c6ae253c82661405dce74c7c0fe07b8

**Comment by weisswurstkanone** [comment]
thx!

**Comment by markus-moser** [comment]
@brusch we were not able to reproduce it for other data types - could you please show us how it is reproducable if this is still relevant?
