### ISSUE TITLE
Pimcore 5.6.0 Update - Migration 20181126094412 failed when PimcoreEcommerceFrameworkBundle not enabled

### ISSUE THREAD

**Issue by davidhoeck** [pimcore/pimcore#3806]
### Expected behavior 
Successful execution of migration after  the update

### Actual behavior  
 `You have requested a non-existent service "pimcore_ecommerce.factory".` because EcommerceBundle not enabled in the container. If it is enabled, the migration works fine.

**Comment by dpfaffenbauer** [comment]
thats interesting: https://github.com/pimcore/pimcore/blob/master/bundles/CoreBundle/Resources/migrations/Version20181126094412.php#L23

the migration doesn't have anything todo with the ecommerce framework.

**Comment by brusch** [comment]
Very interesting ... I'm even not able to reproduce it ... just tried it twice with the basic demo.

**Comment by ITspirit** [comment]
Now have the same issue on migration. E-Commerce Framework is not installed (but was some times ago - till i've choosen to use coreshop and disabled/uninstall e-commerce framework).
After re-install the migration works (and just afterwards i unistalled e-commerce fw again).

Maybe there remain some pieces still after uninstall of the ecommerce-framework or reside within the VCS (classes/definiton_* for example).

**Comment by brusch** [comment]
@ITspirit Thanks for sharing your findings! 

Actually it is intentional that the ecommerce bundle is not removing the definitions for classes, collections and bricks, because there's the risk of data loss (e.g. maybe you'd like to keep your order objects, ...). 
But you're right, maybe there should be a message displayed and a command that helps with the cleanup.
