### ISSUE TITLE
Navigation: no active class on link (child) target

### ISSUE THREAD

**Issue by michielkouwenhoven** [pimcore/pimcore#381]
I have a document\link in the tree with document\page children.
The link targets the first child page so when you click on it you'll end up on that first page.

The problem seems to be that when the uri of the link is the same as the uri of a child page, this child page receives no active class.

Result:
Link has an active class in navigation but the (child) target page has not.

Expected result:
Active class on both link and its target (child) page.

Pimcore v3.1.1 (Build: 3543)

![screenshot](https://cloud.githubusercontent.com/assets/1712679/12289304/09005c0a-b9db-11e5-81fe-9e88aeea561a.jpg)

**Comment by brusch** [comment]
This is actually not the expected result, because only one page is active and that's the target page, not the source link. However, the source link should have the "active-trail" class, so you can easily style it in the frontend: https://github.com/pimcore/pimcore/blob/master/pimcore/lib/Pimcore/View/Helper/PimcoreNavigation.php#L236

If this isn't flexible enough for your use-case, you can add your own navigation logic using the callback functions or custom partial scripts. Both methods are described in detail here: https://www.pimcore.org/wiki/display/PIMCORE4/Navigation
