### ISSUE TITLE
pimcore editables not working in twig macrofile

### ISSUE THREAD

**Issue by dasraab** [pimcore/pimcore#3833]
```
{% macro main_area(areaName = 'content') %}
{{ pimcore_areablock(areaName, 
{ 
    dontCheckEnabled: true,
    allowed: [
        "intro-slider",
        "intro-image",
        "breadcrumbs",
        "site-title",
        "section",
        "video",
    ],
    "globalParams": {
        "forceEditInView": true
    }
 }) 
}}
{% endmacro %}
```

This doesn´t seem to work but also doesn´t throw any errors... maybe i´ve to import the macro-file with all pimcore_editables but i can´t find it. 

Any help is much appreciated.

**Comment by dpfaffenbauer** [comment]
there is no macro-file with pimcore editables, they are implemented using Twig Helpers

**Comment by dasraab** [comment]
is there a way i can use the editables in a macrofile?

**Comment by LevinFaber** [comment]
Hi, I think this issue has been closed prematurely. If I understand correctly, the gist of his question is, that if you use a pimcore editable in an Twig macro, no output is generated. 

The problem stems of the fact, that Twig context is lost when entering a macro (see: https://twig.symfony.com/doc/2.x/tags/macro.html). Due to this, the check in file [DocumentTagExtension.php](https://github.com/pimcore/pimcore/blob/master/lib/Twig/Extension/DocumentTagExtension.php) line 89 fails, since the the context is used to get the current document, which is then validated to be an instance of PageSnippet. But since we are calling this code from inside a macro, the "document" in the $context array is null, ergo an empty string is returned. 

By passing the correct document context to the Twig Macro as an argument, I can then access the argument of part of the context and get the document. But this obviously isnt a nice or viable solution, just an demonstration I made for myself. 

` 
public function renderTag($context, $name, $inputName, array $options = [])
    {
        $document = !is_null($context['document']) ? $context['document'] : $context['context']['document'];
        $editmode = $context['editmode'];
        if (!($document instanceof PageSnippet)) {
            return '';
        }

        return $this->tagRenderer->render($document, $name, $inputName, $options, $editmode);
    }
`

I see no direct way of fixing this without passing the context as an argument to the macro every time I use it. This is why I am adding to this issue, instead of proposing a solution.

**Comment by dasraab** [comment]
thats exactly the solution i came up with in the end... i'm using it for example to create dropdowns for choosing colors. this way i have one central place to set all my colors... this works pretty well in combination with tailwind and the prefix-argument ("bg-", "text-" order even "hover:text-"). This generates classes like bg-grey-100 oder hover:text-black.

in colors.html.twig
```twig
{% macro color(name, document, prefix = '') %}

  {% set colors = [
    {
      'name': 'Grey 100',
      'class': 'grey-100'
    },
    {
      'name': 'Black',
      'class': 'black'
    },
    {
      'name': 'White',
      'class': 'white'
    },

  ] %}

  {% set colorClasses = [] %}
  {% for color in colors %}

    {% set colorClasses = colorClasses | merge([
      [
        prefix ~ color.class,
        color.name
      ],

    ]) %}
  {% endfor %}


  {% set select =  pimcore_select(name, {
    "store": colorClasses
  }) %}
  {{ select | raw }}
{% endmacro %}
```

and in your template: 
```twig
{% import "colors.html.twig" as macros %}
{{ macros.color('font_color', document, 'text-') }}
```

**Comment by dpfaffenbauer** [comment]
why not use `embed` instead when working with macro might cause issues?

**Comment by dasraab** [comment]
i dont see how i can create that functionality with {{ embed() }}

**Comment by dpfaffenbauer** [comment]
https://twig.symfony.com/doc/3.x/tags/embed.html

not pimcore, twig ;)

**Comment by dasraab** [comment]
aaaahhh... my bad. yeah that looks like an alternative but for now its working like a charm with macros. i've just to remember that i've to give the macro $document as param. besides of that... never change a running system :)
