### ISSUE TITLE
Upgrading to last 5.6.0, advanced many-to-many object relation config is lost

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#3847]
Hello,

We migrated a project from Pimcore 5.0.2 (revision: 147), using `https://pimcore.com/docs/5.x/Development_Documentation/Installation_and_Upgrade/Upgrade_Notes/Within_V5/Update_from_5.x_to_5.4_or_above.html`. After we upgrade it to the latest 5.6.0 (`https://pimcore.com/docs/5.x/Development_Documentation/Installation_and_Upgrade/Updating_Pimcore/index.html#page_Upgrading-from-version-5-4-0-to-a-newer-version`).

In our classes we have some Advanced Many-To-Many Object relation (old multihref object with metadata).
The fied "Allowed class" in the pannel of the class edition is empty now, as well visible fields:

![link](https://user-images.githubusercontent.com/9025839/51326256-ffb09c80-1a6e-11e9-97f5-a3a55f99d45f.png)

Before the upgrade the class allowed was setted. I think this is due to the last 5.6.0 which has made some change at this level and maybe something is missing in the upgrade postfunction...

For now we have to set manually all those type of field for each classes. Datas bdd relation are not lost, just the definition of the class is wrong. So by setting it again manually in the class if we open the objects the relation is always here.

Thanks.

**Comment by brusch** [comment]
Hmmm, I've just tried that, but no problem, all works as it should :| 
Maybe you have some more details on that or a reproducible case?

**Comment by Yivan** [comment]
Thanks for having testing it and reports the result.
So maybe it is our project specific problem. We will keep an eye on it when updating other projects and will investigate more on this to give more details if it reproduces.

**Comment by sebastianMoser** [comment]
Maybe we have the same problem. We migrated from 4.6.3 to 5.4 and updated then to 5.7.0.
All our Data\Link relations (in fact all "in-column"-relations are wrong) in custom objects are wrong:
O:30:"Pimcore\Model\Object\Data\Link" ... instead of DataObject.
We noticed that those strings are mapped to a DataObject\Link object, but the properties are lost (protected, public issue).

`Link {#3242 ▼
  #text: null
  #internalType: null
  #internal: null
  #direct: null
  #linktype: null
  #target: null
  #parameters: null
  #anchor: null
  #title: null
  #accesskey: null
  #rel: null
  #tabindex: null
  #class: null
  #attributes: null
  #_owner: null
  #_fieldname: null
  #_language: null
  +"text": "mehr Info zu Atlantica"
  +"internalType": null
  +"internal": null
  +"direct": "/reisethemen/produkte-marken/atlantica"
  +"linktype": "direct"
  +"target": ""
  +"parameters": ""
  +"anchor": ""
  +"title": ""
  +"accesskey": ""
  +"rel": ""
  +"tabindex": ""
  +"class": ""
  +"attributes": ""
  +"href": null
}`

It is actually not possible to get the data in admin mode or in the frontend. ->getHref() is always null because the protected property is preferred.

@brusch Do you have an fix/migration for this issue?
