### ISSUE TITLE
[ecommerce] extending class name prevent running update index.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#3933]
Hello,

We activated the ecommerce framework.
Creating a "CDPProduct" class on the GUI and extending it using parent php class field with `\CDPBundle\Model\Product` as value.
All works fine.

But calling `php bin/console ecommerce:indexservice:bootstrap --update-index`, we get the following error:
```
Fatal error: Uncaught RuntimeException: The autoloader expected class "CDPBundle\Model\Product\Listing" to be defined in file "/var/www/html/vendor/composer/../../src/CDPBundle/Model/Product/Listing.php". The file was found but the class was not in it, the class name or namespace probably has a typo. in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Debug/DebugClassLoader.php:213
```

It is looking for `CDPBundle\Model\Product\Listing`... a class which doesn't exist for sure.
It should look for `Pimcore\Model\DataObject\CDPProduct\Listing`.
Is it normal ? Do we have to create this listing class manually ? (it isn't mentionned on the documentation it seems).

Thanks.

**Comment by Yivan** [comment]
I should add we tried to rename the extend class as `\CDPBundle\Model\CDPProduct` instead `\CDPBundle\Model\Product`, and this brings this error (after flushing all caches):

```
Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "Listing" from namespace "\Pimcore\Model\DataObject\Product".
```
It shoud look in `\Pimcore\Model\DataObject\CDPProduct`.

**Comment by fashxp** [comment]
does it work to provide the listing class with `--object-list-class` param?

**Comment by Yivan** [comment]
If i provide this param it works. I wasn't aware of this parameter.
I was thinking it will autodetect the class extending product.

Maybe you should add this parameter as hint in the documentation ?
Or improve the code of the command to autodetect by analysing if some class extend the product model.

**Comment by fashxp** [comment]
it cannot autodetect the product class name since you can use whatever class name you want for your product class(es) and Pimcore simply doesn't know what data object classes are index classes. 
that's the reason there is this param, which has a decent default value (set to `Pimcore\Model\DataObject\Product\Listing`  

Your first error message is really strange though - I'm not sure if it is connected with the indexing command at all. 

The param is documented in the help section of the command and in the documentation it says look --help sections for details. 
I added an additional comment and restructured the docs a bit. Hopefully this helps?

**Comment by Yivan** [comment]
@fashxp It's perfect, thanks !
