### ISSUE TITLE
Global setting to disable tree node preview panel for asset tree

### ISSUE THREAD

**Issue by chix** [pimcore/pimcore#403]
Hi, it would be nice to have an system option to disable the tree node preview panel which appears when you hover over an asset tree node (image, pdf, ...). Similar option already exists for the document tree: System settings ->  Documents ->  Generate previews checkbox.

**Comment by cleggypdc** [comment]
:+1:

**Comment by brusch** [comment]
Shouldn't this be an user setting instead of a system setting?

**Comment by chix** [comment]
Well, yes, that makes sense. I'm proposing this, because many clients find the previews confusing or annoying, but for me they are usefull - so an user setting would be even better.

**Comment by solverat** [comment]
:+1:

**Comment by atietje** [comment]
Thumbs up for a user specific setting for switching off the preview pane. 

Even more annoying than the preview pane itself is, that the preview images are generated when the pane opens the first time. That can make the gui quite unresponsive if you upload some 100 PDF files of which some 15-30 are then all converted at the same time. Each one starts a HTTP request which fires up Imagick and gs. Maybe the previews should better be generated directly after upload to speed up the gui afterwards.

**Comment by brusch** [comment]
@atietje the preview thumbnails are already generated when the image gets saved: 
https://github.com/pimcore/pimcore/blob/master/pimcore/models/Asset/Image.php#L63

**Comment by atietje** [comment]
@brusch Yes, stupid me, you're right. They're not created when I add assets programmatically during an import. I should run `php console.php thumbnails:image --system` afterwards.

**Comment by brusch** [comment]
@atietje if you know that your asset is an image you should adapt your import as follows:

    $asset = new Asset\Image();
    $asset->setData(); 
    $asset->set.....
    $asset->save(); 

then the thumbail is created directly at the time it is created.

**Comment by atietje** [comment]
That's what I already do, see my comment. What can I do about PDF files? Their thumbnails are not created.

**Comment by brusch** [comment]
Ah sorry :-) 
For documents they are not generated automatically, because this can take some time depending on the actual document. But you can call the following directly after the import: 
    $asset->getImageThumbnail(Asset\Image\Thumbnail\Config::getPreviewConfig(), 1);

**Comment by atietje** [comment]
@brusch Works, thanks a bunch! Nevertheless, the usersetting for disabling the preview pane would be nice to have :)

**Comment by TPETb** [comment]
Well actually this panel quite an issue for me. There are problems with this feature for sure. And dispite mentioned by @brush, previews auto-generation upon save() doesn't seem to work for me (maybe because I mostly use setStream instead of setData or maybe because I have loads of images that were uploaded back in earlier version of Pimcore or smth else). 

But even presuming that those thumbnails are generated, they are still not accessed as static files directly, instead they are retrieved through getThumbnailAction which means:

1. request is propagated to apache
2. apache propagates request to php-fpm
3. php-fpm initialises pimcore with all the database and redis connections and all other stuff (even with lazy loading and zend cache enabled it is still noticeable)
4. image is read by php and passed to php://output finally
5. and then it actually all propagates back to origin

And now this is all done 30 times for every folder hover event. For every admin. Now imagine how many IOPS we get out of this feature.
So we are bitting crap out of our server just for that panel while actually no one does care about it anyway. 

@brusch, I understand there are more features that require your attention and it would be rude of us to rush you on this one. I'm eager to help but unfortunately I'm not experienced with admin UI changes and ExtJS in particular. If you would give me a small hint which file to look at, I could do a pull request for you with user/system-wide config option to disable the preview panel.

**Comment by TPETb** [comment]
Minor update. The reason why thumbnails are not generated on asset generation in my case:

Instead of passing source image as data/stream/sourcePath into Asset::create(), I use ->setStream() after asset is created. Problem is that Asset is treated as "abstract" Asset instead of Asset\Image and therefore thumbnails are not generated. Passing source image to Asset::create() directly results to new instance created as Asset\Image which now has event listeners assigned to generate admin thumbnails.

**Comment by sattes-faction** [comment]
I'm having similar problems with the hovering. When you have a folder with many files and you start hovering the folders the server load gets so high that it eventually crashes the database.

**Comment by SloganHD** [comment]
:+1:

**Comment by jstsch** [comment]
+1

**Comment by brusch** [comment]
![image](https://cloud.githubusercontent.com/assets/142037/15858979/65fbb3ae-2cc3-11e6-83da-a940c8cc3c28.png)
