### ISSUE TITLE
[new feature] Allow a default value for translation method.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#4106]
Hello,

This is a feature request. I submit it because it can maybe be a nice addition.

A second parameters could be added to `translate` method, to use this value instead the key if translation isn't filled.
This could be particularly help in the Pimcore case, because to have independant translation of object fields for instance, using `myclass.myfield` as key for the translation, we could have:

`$this->translate("myclass.myfield", "Name in english")`

Purpose is to prevent in case non-filling of translation value to display directly the translation key which can be sometimes cryptic ; )
I know this fallback value will be the same for all languages, but at least a default english value will be understandable by people.

Thanks for reading me.

**Comment by brusch** [comment]
The templating helper `Translate` has the same parameter signature as the `trans()` method of the Symfony Translator, which makes perfectly sense, because then you can use the same parameters no matter from where you're using translations. See also https://github.com/pimcore/pimcore/blob/c62924ca5c3d0c482a71097cb0231aff143208d6/lib/Templating/Helper/Translate.php#L66

Additionally changing the signature would mean a major BC break. 
I'd suggest you to just use `Name in english` as the key, then you're good to go 😊
