### ISSUE TITLE
Error reading serialized data in block for StructuredTable under PHP 7.1 after update from < 5.4 to >= 5.4

### ISSUE THREAD

**Issue by woellundwoell** [pimcore/pimcore#4232]
# Bug Report
After updating from pimcore < 5.4 to >= 5.4 previously saved serialized data within a block (Pimcore\Model\DataObject\ClassDefinition\Data\Block)  is no longer read due to an PHP bug: 
https://bugs.php.net/bug.php?id=74586 and the change in in https://github.com/pimcore/pimcore/blob/d2acc6e0bbf363175975fce77af0557b017739cb/models/DataObject/Data/StructuredTable.php#L29 from public to protected. This bug also exists in the current version 7.1.28. In PHP 7.2 the bug was fixed.
Would not it be better to increase the requirements to PHP >= 7.2?

**Comment by brusch** [comment]
I've experienced this PHP bug as well 😟
It is fine as long as you do a fresh install of >= 5.4 on PHP 7.1, the only issue is when running < 5.4 and upgrading to => 5.4 on PHP 7.1. With that in mind I'd rather put an appropriate notice into the upgrade notes instead of increasing the requirements to PHP 7.2.
