### ISSUE TITLE
[DataObject] copy/persistence of FieldCollection field between 2 objects

### ISSUE THREAD

**Issue by FredoVelcro-zz** [pimcore/pimcore#4277]
Hello,

I have a Product object with a FieldCollection field (docsList). 
Each item is a composed field with a title (string) and a PDF document (Asset\Document).
When trying to simply copy fields between 2 objects, the destination product has the FieldCollection with all items BUT the document object is not linked/set :
``` 
// the easy way i would like to do this :
$product2->setDocsList($product1->getDocsList());
```
I am forced to do a tricky thing like : 
```php
$copyDownloadableDocuments = function (Fieldcollection $collection = null) {
                if (!$collection) {
                    return null;
                }

                $docs = new Fieldcollection();
                foreach ($collection as $doc) {
                    /** @var \Pimcore\Model\DataObject\Fieldcollection\Data\DownloadableDocument $doc */
                    $copyDoc = new Fieldcollection\Data\DownloadableDocument();
                    $copyDoc->setDocument($doc->getDocument());
                    $copyDoc->setTitle($doc->getTitle());

                    $docs->add($copyDoc);
                }

                return $docs;
            };

$product2->setDocsList($copyDownloadableDocuments($product1->getDocsList()));
```

What is the right way to easy copy FieldCollection between 2 products ? 
Is it a matter of dirtyMap  (already tried...), lazy loading or something else ?

Thank you for any help / good practice to do this.

Best regards,

Fred

**Comment by kaurov** [comment]
Any news?

**Comment by lukmzig** [comment]
@FredoVelcro-zz @kaurov 
First of all, we are really sorry for the late reply. 
I had a deeper look to the cause of this issue and it is mainly because the FieldCollections are not using the Query table as of now, therefore you cannot query these data directly, as stated also here: https://pimcore.com/docs/platform/Pimcore/Objects/Object_Classes/Data_Types/Fieldcollections/#inheritance

`currently field collection data does not get saved to a query table (so you would not be able to query for inherited data)`

I would say the proposed approach is correct for your use-case.
