### ISSUE TITLE
KeyConfig inconsistent db query 

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#429]
```php
$config = new Classificationstore\KeyConfig();
$keyConfigElement = $config->getByName( 'test' );
```
will return entries with `enabled = 0` while

```php
$list = new Classificationstore\KeyConfig\Listing();
$list->addConditionParam('name = ?', "test")->setLimit(1)->load();
```
returns no disabled elements. is there any reason for that? beside, it's not possible to delete a keyConfig for real, it's just a disabling. how come?

**Comment by weisswurstkanone** [comment]
Hi,
yes that is currently intended. The idea is that we do not actually want to remove key definitions as this could quickly result in an accidental loss of data. So the goal was to just mark them as disabled ("unpublished") so that they don't show up in the list.

We could argue if this makes sense for getByName(). I could imagine something like setUnpublished like in object lists or even a static setter.

Your input is welcome ;-)
