### ISSUE TITLE
[Objects] Add Links

### ISSUE THREAD

**Issue by BlackbitDevs** [pimcore/pimcore#4419]
Assume you have categories and products and want to have your objects hierarchically visualized in the data object tree. Then currently it is only possible for a product to be in one category. It would be nice if we had links as new type (beside objects, folders, variants), so the following hierarchy would be possible:
* category 1
  * product 1
* category 2
  * link to product 1

When you click "link to product 1" you would get to /category 1/product 1.

**Comment by dpfaffenbauer** [comment]
Would love that as well, but guess that is quite a big feature.

**Comment by fashxp** [comment]
I would not integrate that in the primary data object tree (because this will get quite confusing). 
I would more go for an approach like this: https://github.com/elements-at/AlternateObjectTrees ... maybe we can improve that bundle.

**Comment by Yivan** [comment]
Hello, just to give my point of view, integrating AlternateObjetTrees in the core will be a strong new feature for Pimcore. Notably in a PIM project.
I mean in many project we must really very carefully choose the object tree architecture, because this is actually the only ordrer/tree way to see objects. If wrong choice are made after it is difficult to change it.

Having this awesome AlternateObjectTrees would make this decision less important as several other trees could be made for object with totally different structure.

To be honest, I (and none of my developper teams) even wasn't aware that this extension existed... And i found it really usefull.
We are using more and more custom views, perspective to provide a great user experience and having this will be the last step to make a great UI for differents user roles.
It could be seen as a wondefull new feature for Pimcore 6 too ; )

I think it would be a really big plus for Pimcore.
That was the thing i wanted to share.
Have a nice week-end !

**Comment by fashxp** [comment]
This can be implemented via Alternative Element Trees feature, details see https://pimcore.com/docs/platform/Backend_Power_Tools/Alternative_Element_Trees/

**Comment by cancan101** [comment]
> This can be implemented via Alternative Element Trees feature, details see https://pimcore.com/docs/platform/Backend_Power_Tools/Alternative_Element_Trees/

Can Alternative Element Trees be used with items that have "unpublished" changes (i.e. not saved to the DB)? For example if I want to use "Alternative Element Trees" with a field that tracks the workflow place/state and I only publish at the _end_ of the workflow? In this case, we are _saving_ between workflow steps and publishing (saving to DB) only at the end. I would still like to provide my users some UI where they can see all the Objects at a given state in the workflow.

**Comment by fashxp** [comment]
currently, alternative element trees are built based on the last published data.
