### ISSUE TITLE
[BUG]webp thumbnails handling in Pimcore delaying TTFB 

### ISSUE THREAD

**Issue by plexmaniax** [pimcore/pimcore#4557]
Pimcore needs about 5 times longer to provide a contentpage with webp thumbnails, as they with jpeg thumbnails.

Tested on different webserver and local in Docker.
I created a static page with webp content, the TTFB was great. 
I thought Pimcore generates the thumb on every new call, but that isnt`t. 

I created 2 content pages with the same pictures. The first site with jpg for picture icons, the second one with webp for picture icons. 

This is the call on jpg content

![jpeg_wasserfall_gesamt](https://user-images.githubusercontent.com/18365319/59934036-ec08c800-944a-11e9-99dd-0dc1d99d4a1a.png)

This is the call ob webp content

![webp_wasserfall_gesamt](https://user-images.githubusercontent.com/18365319/59934054-faef7a80-944a-11e9-807b-18c7b1859b4f.png)

Both sites has exactly the same content and both of them are using the same originals.

Maybe there are lots of internal checks before pimcore provides webp thumbs, but why this happen? I`m not a devloper but maybe you could find the problem in these lines 

https://github.com/pimcore/pimcore/blob/master/models/Asset/Image/Thumbnail.php#L483

Thanks for support

**Comment by plexmaniax** [comment]
Is it possible to install webp on pimcore demo, I would like to test it again if you would provide it?

**Comment by jremmurd** [comment]
We experienced a similar behaviour.
 
I think the issue is in https://github.com/pimcore/pimcore/blob/master/lib/Image/Adapter/Imagick.php#L978, as a new instance of the adapter class gets initialized in the Processor https://github.com/pimcore/pimcore/blob/master/models/Asset/Image/Thumbnail/Processor.php#L141 for every image the `supportedFormatsCache` does not work that way and the check is performed for every image, which results in a overhead of processing time dependent on the amount of images on the page.   

Maybe it would be better to store the supported formats persistently i.e. in the cache directory?

**Comment by jremmurd** [comment]
@brusch it would be great if we could merge this to Pimcore 5.8 as well.

**Comment by brusch** [comment]
@jremmurd here we go: https://github.com/pimcore/pimcore/releases/tag/v5.8.6
