### ISSUE TITLE
Default values are not saved

### ISSUE THREAD

**Issue by BlackbitNeueMedien** [pimcore/pimcore#4600]
I know that configured default values in field definitions are not saved to database, they are only used to preset a field's value in the GUI
But why is this the case? Also in https://github.com/pimcore/pimcore/pull/3853#issuecomment-473885914 this fact is cited - but what is the reason for this?

By not saving default values to the database a lot of problems arise, e.g. the value does not appear in exports. When you then open the object to check if the value really has not been set, it gets even more confusing because there the default value gets applied.

**Comment by weisswurstkanone** [comment]
- only for create, not on update. otherwise there is no way to null it out anymore.
- if inheritance is enabled and there is no parent value then take the default value.
- if inheritance is disabled, take the default value.

**Comment by BlackbitNeueMedien** [comment]
Resolved by #5594

**Comment by lherbst** [comment]
Hi all,

We are currently having the exact same problem as mentioned in this issue, so we checked whether updating to the Pimcore version where this issue was resolved would help here.

As far as I can see, this would currently not take an optional OptionProvider for Selects into account... or am I missing something?

**Comment by weisswurstkanone** [comment]
True, see https://github.com/pimcore/pimcore/issues/5673
