### ISSUE TITLE
regression: ip restriction for debug mode no longer working

### ISSUE THREAD

**Issue by cadeyrn** [pimcore/pimcore#4722]
### Steps to reproduce

1. go to system settings
2. enable debug mode, but only for one IP address

### Expected behavior

Debug mode is enabled.

### Actual behavior

Debug mode is disabled.

It used to work until Pimcore 6.0.3 (I believe; but in any case it worked in early versions of Pimcore 6) but is no longer working in Pimcore 6.0.4 and 6.0.5. Without IP restriction debug mode is still working.

**Comment by i-telligence-af** [comment]
I'm having the same problem since a few days, although on Pimcore 5.6.6 - is that at all possible?

To be specific, when I enable debug mode the correct IP address is inserted. The Symfony debug bar is never loaded though. When I try calling dump() from within a controller, I get an error saying 
`Attempted to call function "dump" from namespace "AppBundle\Controller".`. Calling dump() from Twig results in the output being printed, but not formatted as it should be.

Setting 
`PIMCORE_ENVIRONMENT=dev` 
does work.

Can this be related, i.e. maybe through a dependency rathen than the Pimcore version itself?

**Comment by brusch** [comment]
@i-telligence-af debug mode only works when in dev environment or when no environment is set, see also #4691

**Comment by i-telligence-af** [comment]
@brusch Strange, I could swear that I've always set Pimcore env to prod via .env and then enabled debug mode through Pimcore admin when I need to debug something on a production server, but I was mistaken! Sorry about that. And thanks for the ultra quick reply!

**Comment by dpfaffenbauer** [comment]
@brusch that is not true for 5.* and 6.0. If you enable debug in Pimcore, you also enable DEV Env and Kernel Debug:

https://github.com/pimcore/pimcore/blob/master/lib/FeatureToggles/Features/DebugMode.php#L93
https://github.com/pimcore/pimcore/blob/5.8/lib/Config.php#L812
https://github.com/pimcore/pimcore/blob/5.8/lib/Bootstrap.php#L286

It's now after you removed the Feature Toggles, and I am not sure if thats good. Debug Mode should enable DEV Env for, well, debugging.

**Comment by brusch** [comment]
@dpfaffenbauer sorry, that's not true, see: 
https://github.com/pimcore/pimcore/blob/5.8/lib/Config.php#L812
You only get there if **NO** environment was set via `PIMCORE_ENVIRONMENT` or `SYMFONY_ENV`. 

So if you have `PIMCORE_ENVIRONMENT=prod` set somewhere as an env var and you enable debug mode, Pimcore doesn't switch to `dev` environment, and therefore you don't get the debug toolbar or the profiler. 

Same here: 
https://github.com/pimcore/pimcore/blob/5.8/lib/Bootstrap.php#L287
`Config::getEnvironment();` returns `prod` if it is set via an env var and so the kernel debug flag isn't set.

**Comment by dpfaffenbauer** [comment]
You are right, yes. Just tested it. Then it only works for installations where I don't explicitly define a environment.
