### ISSUE TITLE
[UI] Link Git Hash to GitHub in About Dialog

### ISSUE THREAD

**Issue by ultramegatom** [pimcore/pimcore#4752]
Its not easy to find the current Pimcore version you are using when on dev-master unstable builds.
It would be really useful to display the latest stable version as well. 

Something like this:
![image](https://user-images.githubusercontent.com/7206334/61706908-97a68000-ad49-11e9-8543-2beeca93a673.png)

**Comment by brusch** [comment]
Unfortunately this isn't as easy as you'd assume, because we don't have this information available. 
But there's a quite easy way to check on which version your dev-master is, just open the corresponding commit (use the hash provided in the info) on GitHub, e.g.

`https://github.com/pimcore/pimcore/commit/c0c30a63accc5ca334debd069c5d46289255c3bf`

If you're behind the latest release, something like that is shown: 
![image](https://user-images.githubusercontent.com/142037/61778916-02b28e00-ae00-11e9-8487-9118620626a3.png)

So in this example know that you're based on `6.0.5`

If you're based on the latest version, only "master" is displayed: 
![image](https://user-images.githubusercontent.com/142037/61779006-355c8680-ae00-11e9-9089-14763fab72b3.png)

**Comment by brusch** [comment]
I've linked the hash to GitHub, so it should be quite easy now :) 

![image](https://user-images.githubusercontent.com/142037/61779254-a603a300-ae00-11e9-9727-838b07052ffc.png)

**Comment by ultramegatom** [comment]
> Unfortunately this isn't as easy as you'd assume, because we don't have this information available.
> But there's a quite easy way to check on which version your dev-master is, just open the corresponding commit (use the hash provided in the info) on GitHub, e.g.
> 
> `https://github.com/pimcore/pimcore/commit/c0c30a63accc5ca334debd069c5d46289255c3bf`
> 
> If you're behind the latest release, something like that is shown:
> ![image](https://user-images.githubusercontent.com/142037/61778916-02b28e00-ae00-11e9-8487-9118620626a3.png)
> 
> So in this example know that you're based on `6.0.5`
> 
> If you're based on the latest version, only "master" is displayed:
> ![image](https://user-images.githubusercontent.com/142037/61779006-355c8680-ae00-11e9-9089-14763fab72b3.png)

this is the way i look it up currently :)
The root problem for this feature request was that customers / project leads keep asking about the current version and i always have to do a lookup. I don't think the github link will solve this.
