### ISSUE TITLE
[Bug] Hires 2x assets are not created on S3

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#4988]
# Bug Report

### Expected behavior

All thumbnail versions of an asset should be available from S3.

### Actual behavior

Only 1x versions are.

### Steps to reproduce

1. [Set up S3](https://pimcore.com/docs/6.x/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Amazon_AWS_Setup/Amazon_AWS_S3_Setup.html)
2. Upload an asset, an image is the easiest choice.
3. Get HTML with the `getHtml()` method.

## Result

A string like this, paths shortened and line breaks added for readability:
```html
<img width=\"300\" height=\"300\" alt=\"\" 
   src=\"https://s3.eu-west-1.[snip]/thumbnail/5924295_a91cc9cb60_o_d.webp\" 
srcset=\"https://s3.eu-west-1.[snip]/thumbnail/5924295_a91cc9cb60_o_d.webp 1x, 
         [snip]/thumbnail/5924295_a91cc9cb60_o_d@2x.webp 2x\" />
```

The URL `https://s3.eu-west-1.[snip]/5924295_a91cc9cb60_o_d.webp` gets uploaded to S3 and works fine, but note the *2x* image, it is still referencing a local thumbnail. Inspecting the S3 bucket reveals no image gets uploaded either.

However, I can get this to work by changing the `true` value to `false` for the *deferred* argument on `getThumbnail()`, here:

https://github.com/pimcore/pimcore/blob/907889296ed2469bd667a5a640caeba9b4d100dd/models/Asset/Image/Thumbnail.php#L486

**Comment by NiklasBr** [comment]
An update, I accidentally got it working by increasing the *High Resolution* value from `0` to `2`. Judging by the description, this should not be necessary, but at least it is a work-around;

> (eg. for Web-to-Print or everywhere where srcset is not possible/sufficient, not necessary for normal web-thumbnails, they automatically get a srcset attribute with 1x and 2x)

**Comment by NiklasBr** [comment]
Another update, turns out the above accidental work-around is not working fully either. The above example works *if and only if* the 1x image had already been saved to S3. If new assets are added after this change then those new assets will instead have the bug on the 1x image.

**Comment by NiklasBr** [comment]
@brusch You wrote the docs, can you help? :)

**Comment by brusch** [comment]
@NiklasBr This is correct behavior. 
As the thumbnails are getting generated on demand, we needs to generate the thumbnail first, before it can be delivered from S3. Otherwise we'd have to generate them all on runtime, which has big impacts on performance. 

So as soon the `@2x` URL was called once, it will change to the S3 address. 
This is actually commented in the code 😉

**Comment by NiklasBr** [comment]
> So as soon the @2x URL was called once, it will change to the S3 address.

This is obviously not what is happening here because the `getHtml()` method will return S3 URL:s for both the 1x and 2x but only actually generate one of them because of the hardcoded *defer* setting. When the client (browser) then requests the asset it will do so using the S3 URL which never actually connects to the Pimcore instance, thereby never

1. Tell me, how are we expected to use the `getHtml()` method to get both the 1x and 2x then?
2. Why was this hardcoded as deferred?
3. Why was it not documented?

**Comment by NiklasBr** [comment]
@brusch Can you please point to the documentation? It is impossible to find 😠

**Comment by brusch** [comment]
For me it works as described, no problems. 

1. works for me
2. because it makes sense -> performance
3. maybe i missed that, nobody is perfect (except for a few exceptions)

**Comment by NiklasBr** [comment]
1. Are you a certificate holder on the [Works On MY Machine Programme](https://blog.codinghorror.com/the-works-on-my-machine-certification-program/)?
2. But this causes a bug with S3 compatibility, please explain how it is supposed to work with S3 storage, because it obviously does not.
3. You *already* claimed that is was indeed documented: *"This is actually commented in the code "*. Are you saying it is not?

**Comment by brusch** [comment]
It's on this page: 
https://pimcore.com/docs/6.x/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Amazon_AWS_Setup/Amazon_AWS_S3_Setup.html

![image](https://user-images.githubusercontent.com/142037/69162183-88afbe80-0aec-11ea-9c51-8229ed3048b6.png)


The event `\Pimcore\Event\FrontendEvents::ASSET_IMAGE_THUMBNAIL` is called for both, the `1x` and the `2x` thumbnail (this has nothing to do with the `getHTML()` method). In the method, there's the check whether the thumbnail file exists already on the filesystem or not. If not, the URL to the thumbnail generation service is returned (see https://github.com/pimcore/pimcore/blob/6ca5c852927c910a993e6da06a1f590c7b516854/bundles/CoreBundle/Controller/PublicServicesController.php#L38), because it needs to be generated first. As soon it is generated the S3 URL is returned (see the `file_exists()` above).

**Comment by brusch** [comment]
Just tried it again with the following code: 

```php
<?php

namespace AppBundle\Controller;

use Pimcore\Model\Asset;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BernieController extends BaseController
{
    /**
     * @Route("/bernie/test")
     * @param Request $request
     */
    public function testAction(Request $request) {

        $asset = Asset::getById(409);
        return new Response($asset->getThumbnail('exampleCover')->getHtml());
    }
}
```

Additionally I'm using exactly the code from here (subscriber): https://pimcore.com/docs/6.x/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Amazon_AWS_Setup/Amazon_AWS_S3_Setup.html

Result, see this screen recording: [19-11-_2019_17-00-54.zip](https://github.com/pimcore/pimcore/files/3864739/19-11-_2019_17-00-54.zip)

Btw. if you ask someone for help, you should at least try to be friendly and (sometimes) also be grateful if someone cares about the issue 😘
