### ISSUE TITLE
Improve Transliteration::toASCII / Measure Benchmarks?

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#5212]
# Feature Request
On URL building, ``\Pimcore\Tool\Transliteration::toASCII()`` is used extensivly. Also, the omnipresent ``File::getValidFilename()`` is utilizing this method.

In our organisation we recognized that building several 100s of URLs can take up to seconds based on ``\Pimcore\Tool\Transliteration::toASCII()``. While we are aware that the encoding process is quite complex and involves many actions, we think that it might be worth taking a second look at the algorithm, as the outcome can be very beneficial for the performance of Pimcore and its applications.

A good approach would be to gather some benchmarks for the algorithm, e.g. how long does it take to build 5.000 URLs, and then tweak the algorithm and compare various test runs.

**Comment by brusch** [comment]
Pimcore itself doesn't utilize `\Pimcore\Tool\Transliteration::toASCII()` for generating URLs in the core - at least since version 5 (added UTF-8 support for URLs). `File::getValidFilename()` is very rarely used in the core, as far as I've seen only where the performance doesn't matter so much (not for frontend functionalities). 

But yes, this function is probably not the fastest, it depends on https://www.drupal.org/project/transliteration where you can also find further details about the background of this library as well as the advantages it has over using `transliterator_transliterate()`. 
In the long run it would definitely make sense to get rid of this library, but currently there are some issues with 

For details on this topic please have a look at #3175

**Comment by brusch** [comment]
Note: it turned out that `transliterator_transliterate()` is the performance bottleneck.

**Comment by brusch** [comment]
I think it's time to get rid of the Drupal lib in v10

**Comment by brusch** [comment]
Done by #8203 #8198
