### ISSUE TITLE
"Impossible to invoke a method ("getData") on a null variable" since 6.3.0

### ISSUE THREAD

**Issue by cadeyrn** [pimcore/pimcore#5262]
# Bug Report

After the update from Pimcore 6.2.3 to 6.3.1 Pimcore no longer shows content on most pages. I get the following error on almost all pages:

`Impossible to invoke a method ("getData") on a null variable`

I updated two websites, the error happens on both websites after the update.

It's caused by this change:

https://github.com/pimcore/pimcore/commit/e87fe9bda245c35a1d602c199d0cb8ea17680375

Revertig this change fixes the issue.

**Comment by brusch** [comment]
@cadeyrn Do you have a code example for that? I'm not able to reproduce this behavior on our testing instances. 

Please remember that `getElement()` always returned null if the element didn't exist on the document, so a check for null is mandatory! 

```php
if($foo = $page->getElement('myElement'))) {
    $foo->getData(); 
}
```

**Comment by brusch** [comment]
Those 2 are fine, because when using `pimcore_*` there's always an object returned. 
```
{% if pimcore_checkbox('headlineIcon' ~ icon.id).isChecked() %}
{% if not pimcore_wysiwyg('areaHeadline').isEmpty() %}
```

But `{% if document.getElement('contentHeadline').getData() %}` is not valid, since `getElement()` can return `null` if the element doesn't exist, but this was already the case before the change made in e87fe9bda245c35a1d602c199d0cb8ea17680375

**Comment by cadeyrn** [comment]
> Those 2 are fine, because when using pimcore_* there's always an object returned.

Thanks, that'a helpful information.

> But {% if document.getElement('contentHeadline').getData() %} is not valid, since getElement() can return null if the element doesn't exist, but this was already the case before the change made in e87fe9b

I cannot confirm this one. I just tested this on one page a few moments ago.

`{% if document.getElement('contentHeadline').getData() %}` didn't trigger the error in Pimcore 6.2.3 but triggers the error in Pimcore 6.3.1. Reverting https://github.com/pimcore/pimcore/commit/e87fe9bda245c35a1d602c199d0cb8ea17680375 fixes the issue in Pimcore 6.3.1, so this change _does_ affect `{% if document.getElement('contentHeadline').getData() %}`.

But `{% if document.getElement('contentHeadline') %}` works in Pimcore 6.3.1 without reverting anything so I know what I have to fix.

Thank you for your help. :)

**Comment by brusch** [comment]
Please have a look at: https://github.com/pimcore/pimcore/blob/36d8a5df50fd9c979d060a8e806e0c327fcca82c/models/Document/PageSnippet.php#L392 

`getElement()` returned null before as well, in case the requested element doesn't exist. 
Do if you do e.g. `{% if document.getElement('contentHeadlinesdfasdfsadfdsgdfgfdg').getData() %}` in your code (requesting a non existent editable) it will fail as well. 

So your code only worked because all the requested editables in the template exist, but it didn't handle the case of non-existing editables.

**Comment by brusch** [comment]
Please also have a look at `getElement($name)` before the change, the `return null` is there as well ;)

**Comment by cadeyrn** [comment]
True, but we only call existing elements in our code so the change caused a compatibility issue for us. 😅 It was probably a wrong use from the beginning on our side but luckily only one file in our projects is affected so it's easier to solve for us than initially thought. 😊
