### ISSUE TITLE
[Ecommerce][IndexService] fillupPreparationQueue can produce deadlocks

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#5499]
Under certain cercumstances the following exception might happen:

```
An exception occurred while executing 'UPDATE ecommerceframework_productindex_store_elastic SET in_preparation_queue = 1 WHERE tenant = ? AND o_id IN (35795,36015,36214,36343,36344,35796,36215,36016)' 
```

This happens when I save an object and the fillupPreparationQueue statements get's executed by the event listener. If the process queue cronjob runs for the same items, deadlocks might occur.

**Comment by fashxp** [comment]
maybe related with https://github.com/pimcore/pimcore/pull/5181/files#diff-a7704b7c43e36df9615ed8506e40f4e1R449

**Comment by jremmurd** [comment]
Not only in the `fillupPreparationQueue` the error might occur, which I have deactivated in my application at all because there would be to many IDs in the `IN()`statement, but also if the preparation or update-index job runs and in parallel you want to reset the preparation/update-index in the store table on application level.

May workaround was to wrap the statements in a transaction an try it again for x-times with a little timeout - the solution is inspired by `AbstractObject::save()`.
https://github.com/pimcore/pimcore/blob/master/models/DataObject/AbstractObject.php#L664

Maybe we should implement this behaviour in the `AbstractBatchProcessingWorker` as well?
