### ISSUE TITLE
[Asset] Thumbnails: Support for embedded clipping mask in JPEG files

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#5505]
Example files: 
[images.zip](https://github.com/pimcore/pimcore/files/4009504/images.zip)

**Comment by brusch** [comment]
Shouldn't be the default behavior, better to use a thumbnail transformation for that e.g. "Apply embedded clipping mask".

**Comment by NiklasBr** [comment]
I would assume it would be applied automatically and by default if metadata is set to be preserved. Because in JPEG files the paths are declared as metadata, while other formats like TIFF they are part of the image data.

**Comment by brusch** [comment]
Yes, you're right, maybe it's really better to just apply them automatically. 
For that we need some kind of lightweight detection for the embedded clipping path. 
Shouldn't be too hard  I guess. 

The clipping path is stored in the image resource block / 8BIM / IPTC. It should be possible to extract the necessary information. See also https://www.imagemagick.org/discourse-server/viewtopic.php?t=25227

**Comment by ssiergl** [comment]
Hmm...not sure if it is a good Idea to clip images by default if clipping path is present. We are clipping images already since a long time and there are some downsides in daily business:

- Imagemagick quite often breaks clipping. Aside that there are some broken imagemagick 6.9 Versions (like used in debian 9) it is pretty often broken in imagemagick 7 as well (E.g. right now the last eight stable releases are broken again)
- This is a pretty high cpu intensive and often a long running task. We have pimcore instances with about 200.000 images...everyday changing 2000. We completely moved out clipping image generation into our enqueue queue system. Usually clipping images (we are mainly working with print production ready jpegs - high resolution) will take between 0.8 till to 26 seconds (exclusivelly 6 3,5GHZ cores reserved for this task). When I imagine that a customer may need to wait several seconds (or even just 2) the  UX is pretty bad
- As mentioned Jpeg clipping path is part of the image metadata.....often people do forget to resize the embedded path as well when they resize the image....hence if you upload such an resized image without resized path the image thumbnail is broken....again bad UX....just something we really often see in user managed MAM systems
- And last to rely always on the first embedded path can be dangerous. We have a lot images from our industrial partners which always have several named embedded paths.


TBH I would either make it configurable or as a configurable thumbnail tranformation


PS: A side note...on imagemagick 7 ALPHACHANNEL_OPAQUE does not exist anymore.....right now pimcore 6.7 thumbnail generation is completely broken for imagemagick 7

**Comment by brusch** [comment]
@ssiergl thanks for your feedback. 
Regarding `ALPHACHANNEL_OPAQUE` can you please create a dedicated ticket for that, or even better a PR? 
Thanks a lot!

**Comment by ssiergl** [comment]
@brusch will do a PR this evening

**Comment by brusch** [comment]
@ssiergl great, looking forward to it! 👍

**Comment by ssiergl** [comment]
@brusch pushed 2 PRs. One for fixing regression and the other to disable clipping behaviour
