### ISSUE TITLE
EPS images | Low Thumbnail Quality

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#5539]
# Feature

## Problem Description
The Imagick ``trim`` function in conjunction with EPS thumbnails results in high quality loss.

## Suggestion
When the thumbnail is generated, a high resolution should be set for EPS files, initially.
Similar as here: https://github.com/pimcore/pimcore/blob/master/lib/Image/Adapter/Imagick.php#L109
This will improve the quality of the thumbnail.

This lines within the ``load()`` method worked for me:
```php
            if (strpos($imagePath, '.eps') == strlen($imagePath)-strlen('.eps')) {
                $i->setResolution(2000, 2000);
            }
```

Is there a more generic solution? Where do the option parameters need to be set? 
Could the options be taken from the metadata?

Unfortunately I cannot upload the test image due to copyright issues.

**Comment by brusch** [comment]
Pimcore automatically calculates the resolution when using scaling transformations, see: 
https://github.com/pimcore/pimcore/blob/9eb6d30944ba94015cf222eea53dfd220f38adec/lib/Image/Adapter/Imagick.php#L454

For `trim` this is unfortunately not possible since the target size of the image cannot be determinated in advance, so in your case you have to rasterize the image first (e.g. by using `scaleByWidth` before you can (pretty) safely run `trim` on the image. 

Using just a very high resolution like in the example above, costs a lot of extra processing power for rasterizing the image and is still not a generic solution for the problem.

**Comment by andreas-gruenwald** [comment]
Yes, that makes sense. Thx a lot!
