### ISSUE TITLE
Remove Cookie Info Bar

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#5711]
Follow up of #5710

**Comment by dpfahlbusch** [comment]
Will there be another implementation of a cookie-bar? like discussed in #5087

**Comment by christopher-siegel** [comment]
Any updates on a replacement for this?

Since the new GDPR Laws and Cookie Policies, it would be best to have a native OPT-IN solution for cookies.

Pimcore already has "**Tag & Snippet Management**", so here's an idea:

The "Tag & Snippet Management" already allows for "Conditions" (when to load / apply the JS/Cookies).

It would be nice to have a Cookie Bar / Opt-in with multiple options (allow all, just marketing, just needed cookies, etc.) and then have the option to use those as a "condition" for the snippet manager.

Something like this:
![cookie-opt-in](https://user-images.githubusercontent.com/2526628/88373515-4421a480-cd98-11ea-8f97-9e5fa1988299.png)


Ideally there should be a twig function to render cetain elements only if a certain level of cookie opt-in was choosen.
Example (Pseudo-Code):

```
{% if pimcore_cookie_level() == "marketing" %}
   // my analytics js and newsletter tracking ...
{% endif %}
```

What are your thoughts on this @brusch ?

**Comment by brusch** [comment]
@christopher-siegel That's a perfect use-case for a bundle in my opinion 👍
