### ISSUE TITLE
Filter stays active while changing classes

### ISSUE THREAD

**Issue by alexbaat** [pimcore/pimcore#5802]
I have records of 3 different classes in the same folder. When I click on the folder, I have a selectbox to select the class.
First I select the class, in this example Product, which has a field with the name 'sku'. Then I filter on a value in the field 'sku' so it only shows me the results and it shows the 'Filter active'  and 'Clear filter' text at the top.
When I then switch class, the 'Filter active' and 'Clear filter' dissappear and it shows me the results of the other class. Strange thing is that in case the other class has the same field name, in this case 'sku', it applies the filter unwanted to this field.
If you switch back to the original class 'Product', it doesn't show the 'Filter active' and 'Clear filter' button but as I can see the filter is still applied. 
So this seems to be a bug.
I have recorded a video. You can find it at the url https://demo.pimcore.h1.nl/videos/screencast-localhost-2020.02.13-16_43_27.webm

**Comment by weisswurstkanone** [comment]
reason is probably here:
https://github.com/pimcore/pimcore/blob/3e9153aa0e6b8089af10f5b7bccd1a37f2776e11/bundles/AdminBundle/Resources/public/js/pimcore/object/folder/search.js#L226

instead of "copying" every time I would do it only if the class doesn't change.

do you want to create a PR for that ?
