### ISSUE TITLE
Redis Sentinel

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#5939]
As the docs state: "Please note that the Redis adapter currently doesn't properly support Redis Cluster setups."

https://pimcore.com/docs/6.x/Development_Documentation/Development_Tools_and_Details/Cache/index.html#page_Recommended-Redis-Configuration

I wonder why Pimcore Cache does not implement Symfony Cache? They would support such features. Is it possible to refactor that in future? There must be a reason for that...

**Comment by brusch** [comment]
The reason is that Senitel doesn't allow to run Lua scripts synchronously, but this is required to keep the cache consistent. 
Maybe something improved there in later versions, but since we still support Symfony 3.4 it's no option yet.

**Comment by brusch** [comment]
See also https://github.com/pimcore/pimcore/blob/83ece3824eb4666d212e5d2dfdbb0f80d979a07f/lib/Cache/Pool/Redis.php#L22

**Comment by dpfaffenbauer** [comment]
Will Symfony 3.4 be removed with Pimcore 7? If so, refactoring could still be viable for it.

**Comment by brusch** [comment]
Yes. 
But first it needs to be proven that Symfony supports synchronous tag invalidation, if that is the case, I'm of course happy to kick the custom code 😉

**Comment by brusch** [comment]
And of course the invalidation should be at least as fast as the current implementation, not that we're running into performance issues.

**Comment by dpfaffenbauer** [comment]
gotcha

**Comment by AlternateIf** [comment]
@brusch 

i wonder if cluster setups are now possible. if so we should update the docs as they are not very consistent

https://docs.pimcore.com/platform/Pimcore/Development_Tools_and_Details/Cache/ specifies
"Please note that the Redis adapter currently doesn't properly support Redis Cluster setups."

and https://docs.pimcore.com/platform/Pimcore/Installation_and_Upgrade/System_Setup_and_Hosting/Performance_Guide/ 
specifies 
"By default, Pimcore uses the Doctrine connection and write to your DB's cache_items tables. You can also utilize [available cache adapters](https://symfony.com/doc/current/components/cache.html#available-cache-adapters) from Symfony, however, Pimcore recommends to use Redis adapter for a performance boost with optional clustering and fail-over support."


Symfony Cache Adapters (e.g. the tagawareadapter https://symfony.com/doc/current/components/cache/adapters/redis_adapter.html) seem to support clustering.

It's an really interesting option as it would allow to use aws serverless elasticache which uses mandatory clustering in order to automatically scale.  i even got the redisTagAwareAdapter running with a valkey serverless clustered instance by patching a very minor change into the Symfony RedisTagawareAdapter. the patch also fixes getting the evicitionpolicy

![Image](https://github.com/user-attachments/assets/38039683-5d95-4c47-9780-4212aa77bfe6)

my tests for adding, removing, getting from the cache seemed fine. even a simple clearTags worked but i can't say anything about concurrent stuff and now wonder what your thoughts on it are

**Comment by dpfaffenbauer** [comment]
We use Redis Sentinel in Production for years now without issues. We never got Redis Cluster to work though.

**Comment by AlternateIf** [comment]
@dpfaffenbauer 

thanks for your reply. i am trying to use the new aws serverless elasticache which - from my understanding - handles all the cluster changes and replicas etc. through a single vpc endpoint by itself. so no need to setup a cluster config on our/dev side. 

"Behind the scenes, a proxy layer (Routing Layer) manages connections, so your application doesn’t need to handle cluster changes. This proxy layer uses a “network load balancer” to distribute requests efficiently, ensuring seamless scaling, node replacements, and software updates without disrupting your application."

This means that there is no need to use \RedisCluster as you can just use the standard \Redis class as aws does all the rerouting and cluster management by itself behind the scenes. I guess for the application side this is no real cluster setup then as aws does all the handling.

**Comment by brusch** [comment]
@AlternateIf Thanks for pointing out this topic and @dpfaffenbauer  thanks for sharing your feedback. 
Just created a PR removing the obsolete info from the docs. #18394
