### ISSUE TITLE
[Ecommerce][FilterService] Category filter is resetting after page reload

### ISSUE THREAD

**Issue by MyZik** [pimcore/pimcore#5996]
# Bug Report

Hello.

We have also the same problem on Pimcore Demo. I will try to explain. If we do search like "red" (for example), we will see all results for this term:

![Bildschirmfoto 2020-03-06 um 14 15 27](https://user-images.githubusercontent.com/12817320/76086805-23a5a900-5fb5-11ea-9602-c819c8ba9aec.png)

If we refresh the page, the category filter is gone, but results still same:

![Bildschirmfoto 2020-03-06 um 14 15 41](https://user-images.githubusercontent.com/12817320/76086880-4e8ffd00-5fb5-11ea-87d4-98f75e4ed6b6.png)

We can try to search results for "mercedes" and filter is still gone:

![Bildschirmfoto 2020-03-06 um 14 16 00](https://user-images.githubusercontent.com/12817320/76086968-7e3f0500-5fb5-11ea-99c0-a2462f0b9ecb.png)

I have tried to clear pimcore cache and it works but only for one time.

**Comment by dvesh3** [comment]
Data loss, when you use object from website config to load relations fields in field collection. 

Current scenario: load **Root Category(ManytoOneRelation)** from **filterCategory** fieldcollection in **FilterDefinition** object.
![image](https://user-images.githubusercontent.com/5137917/77747629-4872c680-701f-11ea-82e2-d541ee1fdce7.png)
![image](https://user-images.githubusercontent.com/5137917/77747645-4e68a780-701f-11ea-96ed-ef8920dae471.png)
![image](https://user-images.githubusercontent.com/5137917/77748160-30e80d80-7020-11ea-9f4b-ca60084c5d31.png)

It needs more investigation to identify the root cause.
