### ISSUE TITLE
[Data objects] Default value generator service for URL Slugs

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/pimcore#6132]
as an addition to https://github.com/pimcore/pimcore/pull/5069/

**Comment by solverat** [comment]
@weisswurstkanone @BlackbitNeueMedien: I just tested this feature and I'm not sure if I'm getting this right (No specific documentation about this).

This will trigger (`getValue` via `DefaultValueGeneratorInterface` service) only if a new object gets generated, right? But at this point, no information about the object is available.

Imagine a customer wants to create a blog entry - the (localized) title is available after an update because it's not possible to add those fields in an object creation state...

I came up with a proposal some years ago (https://github.com/pimcore/pimcore/issues/1048) and I think that's still a thing. The slug field is an "unsuable" field in a business point of view, since a user needs to add a complete path to it (`/en/xxy`).

**Comment by BlackbitNeueMedien** [comment]
I have not retestet it now but as I remember I tried to implement it so that the default values are generated every time an object gets saved if the field is empty. This is done in `getDataForResource()` in all `Pimcore\Model\DataObject\ClassDefinition\Data` subclasses. `getDataForResource()` gets called in https://github.com/pimcore/pimcore/blob/7669a923de884fdeba986cb19e86f1f4c2046b27/models/DataObject/Concrete/Dao.php#L245-L264

For example for the `input` fields: https://github.com/pimcore/pimcore/blob/7669a923de884fdeba986cb19e86f1f4c2046b27/models/DataObject/ClassDefinition/Data/Input.php#L119-L124
The `handleDefaultValue()` then returns the default value if the field is empty.

Sadly `Pimcore\Model\DataObject\ClassDefinition\Data\UrlSlug` does not implement `Pimcore\Model\DataObject\ClassDefinition\Data\ResourcePersistenceAwareInterface` and for this reason above description does not work for this datatype.
Is this on purpose, @weisswurstkanone ?

**Comment by solverat** [comment]
## UrlSlug
This `save()` method does **not** get executed if the field hasn't been marked as dirty - so this field will never gets prefilled by default.

https://github.com/pimcore/pimcore/blob/1f9d0ff385a9d161f42a1b0f58f045eda421a9e0/models/DataObject/ClassDefinition/Data/UrlSlug.php#L243-L251

Also, the method `getDataForResource` is not available within the UrlSlug data type.

## Handle Default Value
This method does not get dispatched in update processes:

https://github.com/pimcore/pimcore/blob/672b674763688b1697ffced1ab5d8e1ae7670584/models/DataObject/Traits/DefaultValueTrait.php#L52-L57

**Comment by weisswurstkanone** [comment]
UrlSlug uses the CustomResourcePersistingInterface (not the ResourcePersistenceAwareInterface) so there is no getDataForResource.

**Comment by BlackbitNeueMedien** [comment]
Hmm, does a default value generator make any sense then for URL slug datatype, @weisswurstkanone ? Because - as @solverat said - originally default value generators had two intentions:
1. Generate IDs like article numbers which do not depend on other fields' contents
2. Generate values based on other fields' values

Imho, with the current implementation URL slugs can only fulfill 1. but not 2.

**Comment by dpfaffenbauer** [comment]
Currently not, but the goal should be to make sense ;) URL Slugs is something a user will never manually input, so it has to be generated somehow.

**Comment by nicklassandell** [comment]
I just stumbled upon this issue while trying to figure it out myself, and in the end I opted for a  calculated data type. The benefit is that it runs on every save, but the downside is that the user can't manually edit the slug, which in my experience, they do want the option to do. A workaround for that would be to have a second input field where they can manually enter a slug, but that isn't very nice. Anyway, just thought I'd leave this here for anyone else who stumbles across the issue.
