### ISSUE TITLE
Rest API doesn't support Master-Documents

### ISSUE THREAD

**Issue by ChristianBre** [pimcore/pimcore#615]
**Why i couldn't test this on demo.pimcore:** 
- can't activate Rest API there

**What i tried:**
- using the Rest API to export documents from my project to another 
looks like this:
www.***.ch/webservice/rest/document/id/2714?apikey=***

**What i expected:** 
- All document-data exported just as they are shown in Frontend

**What happened:**
- Documents with inherited content via masterdocuments dont export any content via Rest API

Not sure if it is a bug...

**Comment by brusch** [comment]
Saving the system-settings is disabled for security reasons. 
So this is actually a wanted behavior, but we can enable the webservices by default on the demo instance :)

**Comment by brusch** [comment]
Demo works as expected: 
https://demo.pimcore.org/webservice/rest/document/id/4 (you have to be logged in to be able to access the URL).

**Comment by ChristianBre** [comment]
In the demo it doesn't work neither.
https://demo.pimcore.org/webservice/rest/document/id/74

**Comment by brusch** [comment]
Can you please be more specific? 
Unfortunately your links do not work anymore. 

https://demo.pimcore.org/webservice/rest/document/id/4 works for me, in "elements" is the entire content, so what's the problem?

**Comment by ChristianBre** [comment]
Im setting document 4 as a masterdocument for a new one. 
Then i try to get the (inherited)contents of the new document via rest and all i receive is a document without content.

**Comment by brusch** [comment]
Ahhhh, now it's clear to me :) 
The REST API returns only contents which are saved directly on the document/object. Inheritance is currently not possible. The expected behavior of the API of course depends on the use-case, so if you'd to synchronize data between 2 pimcore instances, you don't want inherited contents, because they should also inherit on the target system. 

For objects it wouldn't be a big deal to implement an optional flag to specify whether to return inherited values or not, but documents is not possible right now.
Background: the inheritance is done on the fly, see: 
https://github.com/pimcore/pimcore/blob/87bfef793580b0ac41586db9f95056a342c452ee/pimcore/models/Document/PageSnippet.php#L375-L375
