### ISSUE TITLE
Custom reports: workflow improvement

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#617]
In the documentation it is said as exemple for use case of custom reports "Workflow helpers (objects that need to be updated or completed eg. missing data after the ERP import, ...)".

Actulally, for this workflow we need to have an ID column for exemple, and user need to make a search by ID. There is no possibility to directly open the object/document/asset from the list in the custom reports rendering tab.

It would be nice to be able to map directly in the custom report creation tab an object/document/asset to one of the field (wich will contain the ID) so it can be directly openned (double click or context right click menu). So user can directly open it without to manually have to find it.

**Comment by Yivan** [comment]
I was just thinking, what happen if user doesn't have the right to access to the object ? Maybe a check must be done (i think this check is present when we use the functionnality of object seach by ID for instance).

**Comment by weisswurstkanone** [comment]
Actually this is possible since build 3784, permissions are checked on the server side.

Example:

![image](https://cloud.githubusercontent.com/assets/6142086/15599230/f98b027c-23e1-11e6-9de2-28d1c5d6dc47.png)

Configuration:

![image](https://cloud.githubusercontent.com/assets/6142086/15599241/17aa10a4-23e2-11e6-9ef1-880e608e22ab.png)

**Comment by Yivan** [comment]
Ho so good! You read in my mind few days ago : )
Great you can close the task, it is just pefect like this.
Thanks a lot
