### ISSUE TITLE
[Improvement] Better SVG quality rendered by thumbnail config.

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#6258]
Hello,

On projects, more and more svg is used. Sometimes now we provide the abilities to use SVG as images in the asset sections. These asset are used to be displayed in the front website and so used thmbnail config.
We cannot use a dedicated thumbnail config for svg as editor can upload as well svg, png, etc.

Problem is with SVG if a dimension transformers is used on a thumbnail config, SVG is transformed in bitmap and resized... leaving a really bad display quality. We had the case with a thumbnail configured like this, resoluting on a pixelized bitmap image (webp on chrome).

![image](https://user-images.githubusercontent.com/9025839/79784946-55938480-8343-11ea-982e-7b4b70f7b389.png)

I don't know which is the best way to handle this.
Is it imagick problem, or is relative to the pimcore thumbnail pipeline ?
Shoud a checkbox be added "Bypass transforms for SVG" ?
Can some pipelines step be added/inverted (resizing to a x4 size for instance before transform) ?

Thanks.

**Comment by brusch** [comment]
For certain transformations we need to rasterize the SVGs, see also the info text in your screenshot. Contain is one of the transformations that forces rasterization (not possible without). 

The quality of the resulting PNG/JPG should be excellent (see also our demo), so I assume it's a problem with your installation.

**Comment by Yivan** [comment]
Yes sure, I understand as contain is used, it is transformed in bitmap instead vector.

I made some further investigation.
In fact, if a big resolution is use, let's say 800*600, the resulting svg transformed in png is great in quality. So Pimcore pipeline is ok (conversion is done after sizing up the svg).
The problem in our use case is the svg is a picto, so small size. And the png transformation result in blurry things compared to the original svg at the same size which is cristal clear.

I think nothing can be done for this, so yes it could be closed.
Thanks.

**Comment by nicklassandell** [comment]
I am running into the same issue, with the original file being a PNG, so it is not restricted to vector formats. I am using a Scale by Width filter which only applies if the image is larger than the filter, but even if I upload an image smaller than the filter, I still get the blur.

So that means the issue is not with vector graphics or with the scale filters, but something else. I have quality set to 100%, but it still seems to compress the image. It's also worth noting that the PNG has transparent areas, and when using a JPG with a white background I do not experience the blur issue.

So I think this is worth reopening?

My config is as follows:

![Screenshot 2020-07-06 at 15 39 57](https://user-images.githubusercontent.com/1793383/86599686-41087500-bf9f-11ea-9f32-a9c5a38c74d7.png)

Here's an example image that becomes blurry:
![dumbells2](https://user-images.githubusercontent.com/1793383/86599909-96dd1d00-bf9f-11ea-986e-3be04798b7ab.png)

Here's what it looks like after being processed. Notice the extreme smudging especially at the top.
![Screenshot 2020-07-06 at 15 46 31](https://user-images.githubusercontent.com/1793383/86600115-e7547a80-bf9f-11ea-8f0c-025457f92fb6.png)
