### ISSUE TITLE
[Feature-Request] User-Select restrict to roles

### ISSUE THREAD

**Issue by skochTC** [pimcore/pimcore#6322]
# Feature Request
## Feature description
In a customer project, I set up an option provider to select users of a specific role.

I recently discovered the data field "User" and thought it would be nice to be able to select a role there.

**Comment by skoch98** [comment]
I was about to implement this again, because this was still on my personal ToDo list ^^
After a few lines of code it seemed familiar to me 😄 

As we decided that this isn't a core feature, I would say that the issue can be closed? (@brusch)

Or should it be left open in case the community upvotes this?

**Comment by brusch** [comment]
Yep, you're right - can be closed, thanks for the reminder 😊
Voting can continue anyway, even if closed.
