### ISSUE TITLE
[Classification Store] Quantity Value: Default units not preselected after saving the object

### ISSUE THREAD

**Issue by aarongerig** [pimcore/pimcore#6381]
# Bug Report

This issue is a follow up to https://github.com/pimcore/pimcore/issues/6139
If you add a classification store which holds Quantity Values types with a default unit to an object, but leave the actual value of a Quantity Value empty and save the object, the unit is not "preselected" after reloading the object anymore.

### Expected behavior
Default unit is always preselected if the value of the field is empty or no other unit was previously selected.

### Actual behavior
The unit field is empty after saving and reloading the object.

### Steps to reproduce

- Log in to https://demo.pimcore.fun/admin
- Create a dummy classification store with a key type of Quantity Value
- Create a dummy class which includes the previously created Classification Store
- Create a dummy object, add the classification store but leave it empty and save it
- Reload the object

Newly created object with blank quantity value:
![first_open](https://user-images.githubusercontent.com/17384333/81799547-c62c5c00-9511-11ea-9a17-02e540791316.png)

Object after reload:
![after_save](https://user-images.githubusercontent.com/17384333/81799623-e2c89400-9511-11ea-9298-35e7bd302277.png)

**Comment by BlackbitNeueMedien** [comment]
I currently experiencing the same problem also with classification store but for normal quantity value fields inside a class. When you set a default unit this does not get preselected. I kind of understand that because this would lead to setting a unit for a quantity value field which was `null` before (and afterwards would have value `null` and default unit set).

I could imagine that it would be better to apply the default unit when saving in case no unit has been provided. WDYT?

**Comment by hellwy** [comment]
I think this should be solved somehow. Even by taking into account what @BlackbitNeueMedien is saying (make sense), i think PIM should be MAX optimized for saving operators clicks.

**Comment by hellwy** [comment]
probably, as idea, the default unit could be set in moment of writing data into the fields.

**Comment by ctippler** [comment]
Hi,

i currently encountered the same problem and it turned out that it works with the inputQuantityValue datatype but not with the quantityValue data type. 

This is because the inputQuantityValue  sets the default values in the initialize() method and the quantityValue doesn't do that.

I fixed this with 
![image](https://user-images.githubusercontent.com/8791970/156441237-ab2b419a-e54b-4578-9e4d-20d1e7030e4f.png)

I guess it is because of this:
https://github.com/pimcore/pimcore/pull/6191/commits/3e1b626e279df23cbed7c3caf09c2f1464bffdfc 

`
if (isNew) {
                context["applyDefaults"] = true;
            }
`

Maybe other datatypes reuqire this if(isNew) but in case of the quantityValue datatype i guess its better to always set the default measurements. 

@brusch : What do you think?

Regards

**Comment by NiklasBr** [comment]
This is still relevant

**Comment by BlackbitDevs** [comment]
@ckogler-elements could you create a PR with your suggested solution? I think then we will get a feedback...

**Comment by ctippler** [comment]
@aarongerig / @dvesh3  - I guess this issue can be close - https://github.com/pimcore/pimcore/issues/6381 should fix this.

**Comment by aarongerig** [comment]
@ckogler-elements Which PR do you mean? You linked this same issue in your comment.

**Comment by ctippler** [comment]
@aarongerig - Sorry - i ment this one https://github.com/pimcore/pimcore/pull/11845 - brusch cherry picked it to v10.3

**Comment by aarongerig** [comment]
@ckogler-elements Ah, perfect. Tested it on the official demo and it works now. Closing the issue then – thank you!
