### ISSUE TITLE
Ecommerce | Cart | order is lost when more than one items are added within one second

### ISSUE THREAD

**Issue by andreas-gruenwald** [pimcore/pimcore#6464]
# Bug Report
A common use case is to fill the cart with items based on a fast entry mask or a file-based import.

### Actual behavior
When multiple items are added to the cart within one second, then currently the order is not maintained.

The reason is that the default card item order is based on the ``creationDateTimestamp`` attribute,
which currently only saves the time in seconds. 

### Expected behavior
The items have to be listed in exactly the same order as they have been added to the cart.

### Suggested Solution
Our project-specific solution was to add the following line to the 
``CartManager/Cart::updateItem()`` method:

```php
//set sortindex to nanotime to improve order on mass-insertion (fast-entry, imports)
$item->setSortIndex(hrtime(true)); 
``` 
because then the cart items will be sorted by the sort index.

(a) A better solution would probably be to either add an additional field to the database where the ``hrtime()`` is stored and use the field for the default sorting. 

(b) Another option would be to replace the ``creationDateTimestamp`` with the nanotime value. Option (b) is more likely to cause errors in existing projects.

I can provide a PR after discussion.

**Comment by fashxp** [comment]
I still would go for approach (b) since with approach (a) the current addedDateTimestamp wouldn't make any sense and wouldn't have any use anymore. 

In most use cases it should be transparent for updates anyway, because
- set/getAddedDate returns a DateTime object anyway
- adding new items to existing carts (items with old timestamps) will add items with new timestamp format which have a bigger number anyway

The only case I can think of that might cause problems is, if someone uses get/setAddedDateTimestamp directly and expects values to be normal timestamp and cannot handle hrtime.

But since there is a workaround for it, we wait until Pimcore 7 for that change?

**Comment by andreas-gruenwald** [comment]
> The only case I can think of that might cause problems is, if someone uses get/setAddedDateTimestamp directly and expects values to be normal timestamp and cannot handle hrtime.
> 

That's the case in one of my projects, where the timestamp is used in reports. hrtime() is probably hard to interpret when using SQL queries.... :-/

To sum it up: the whole purpose of hrtime() is to keep the order, it doesn't provide any other value than that (neither in the db nor when accessing cart items via the API).
