### ISSUE TITLE
[Bug][Ecommerce] Index table is not updating for inherited objects

### ISSUE THREAD

**Issue by MyZik** [pimcore/pimcore#6469]
Hello. I try to explain the problem. 

If we have the object `Car`, we can update the items and all inherited objects and variants will be updated. Let's try to change the country of parent object `Car`:
![Bildschirmfoto 2020-05-27 um 16 03 38](https://user-images.githubusercontent.com/12817320/83031844-623b8480-a035-11ea-9a19-75bcd1dfa451.png)

Database:
![Bildschirmfoto 2020-05-27 um 16 00 16](https://user-images.githubusercontent.com/12817320/83031985-8a2ae800-a035-11ea-982d-0281f68c4cd2.png)

Change to Russia and show our updates in variants:
![Bildschirmfoto 2020-05-27 um 16 04 38](https://user-images.githubusercontent.com/12817320/83031951-80a18000-a035-11ea-8bfa-1eee065b478a.png)

And we have an update only for a parent object:
![Bildschirmfoto 2020-05-27 um 16 08 52](https://user-images.githubusercontent.com/12817320/83032021-96af4080-a035-11ea-9196-b97b50ba1f42.png)

We can update the index table with console and it will help us, bun only for one time.

**Comment by fashxp** [comment]
what index implementation are you using? `DefaultMysql`? 
it's not working by design, please see https://pimcore.com/docs/6.x/Development_Documentation/E-Commerce_Framework/Index_Service/Product_Index_Configuration/Data_Architecture_and_Indexing_Process.html for more information. 

You need to use a optimized architecture index implementation, e.g. `OptimizedMysql`

**Comment by MyZik** [comment]
@fashxp Yes, I'm using `DefaultMysql`. Thank you a lot for your answer!
