### ISSUE TITLE
strict localized query for objects

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#673]
**recap** 
If you create a new object with some localized fields, it's getting stored in each language _object_localized*_ table no matter if there are localized values or not. 

```php
 $list = new \Pimcore\Model\Object\MyObject\Listing();
 $list->getObjects();
```

This could give me some objects without any usage because the localized fields are empty. I think that's not quite right.

**proposal** _(save object)_
- check if localized fields are available
- check if one of it has localized data
- save it in proper localized table

**proposal II** _(update object)_
- check if localized fields are available
- check if one of it has localized data
- remove object from localized table if not

With that in mind, we would have a performance boost in frontend in many regards because we don't need to place a extra condition and we'll also save time while developing awesome localized stuff.

**Comment by fashxp** [comment]
hmm, I not sure I get your point here.
even if localized fields are empty, it is still an object of type 'MyObject' and therefore should be included in the result list. Maybe the fields are empty on purpose?!

**Comment by brusch** [comment]
I'm also not sure if I understood everything correctly but to summarize: 

1. Class `Foo` has a localized field container with the field `name` 
2. Configured languages are `en`, `ca` and ´fr` 
3. Now your proposal is that if `name` is empty in an object in all languages, we shouldn't save a row in `object_localized_data_*` right? 

That would be pretty inconsistent. 
The object still has the localized field `name` in languages en, ca and fr no matter if they are filled or not, they have to be in the table and `NULL`. Otherwise this would cause major issues when querying the data for lists etc. 
Consider the following condition: 
`o_id IN (SELECT ooo_id FROM object_localized_data_123 where LENGTH(name) < 3 and language IN ('ca','fr'))`

Now, if objects with empty localized fields wouldn't be in this table, you will get unexpected results, because objects with no name wouldn't be part of the list.
