### ISSUE TITLE
Don't invalidate the complete session on logout

### ISSUE THREAD

**Issue by elements-team** [pimcore/pimcore#6747]
# Feature Request
When logging out, [the complete session is invalidated](https://github.com/pimcore/pimcore/blob/master/bundles/AdminBundle/Security/LogoutSuccessHandler.php#L99).

### Expected behavior
Only clear Pimcore-related session values.

#### Suggested Solution
Only use the attribute bags defined [here](https://github.com/pimcore/pimcore/blob/master/bundles/CoreBundle/Resources/config/pimcore/default.yml#L236).

**Comment by elements-team** [comment]
### Use Case
1. User clicks on logout
2. Event is triggered
3. New RedirectResponse is set using `$event->setResponse(new RedirectResponse($url))`
4. `Session::invalidate();` is called.
5. Redirect is triggered, calling the new action, which wants to access values from the session, which is now empty.

**Comment by psuhane** [comment]
This is the critical issue, below are few scenerios from Pimcore Demo - https://demo.pimcore.com

- If user is logged-in as frontend webshop user and try logging-in as pimcore admin user then frontend user session is invalidated. This also happens vice-a-versa scenario.

- I doubt if below code works after the payment completion in Checkout controller, because session is already invalidated. This is not working in my webshop
`/**
     * @Route("/checkout-completed", name="shop-checkout-completed")
     *
     * @param SessionInterface $session
     * @param Factory $ecommerceFactory
     *
     * @return Response
     */
    public function checkoutCompletedAction(SessionInterface $session, Factory $ecommerceFactory)
    {
        $orderId = $session->get('last_order_id');

        $order = OnlineShopOrder::getById($orderId);

        $trackingManager = $ecommerceFactory->getTrackingManager();
        $trackingManager->trackCheckoutComplete($order);

        return $this->render('checkout/checkout_completed.html.twig', [
            'order' => $order,
            'hideBreadcrumbs' => true
        ]);
    }`

- Because of this GA tracking is also being affected.

Can't we take this issue on priority and fix this on next minor release? @brusch @dvesh3 @fashxp

**Comment by brusch** [comment]
This is on the roadmap for v11.

**Comment by mlumia** [comment]
Temporary solution until v11 is to add a logout listener and call `$event->stopPropagation();` if uri path contains admin.

**Comment by dvesh3** [comment]
Fixed by #13825
