### ISSUE TITLE
setlocale() in conflict with Zend_Currency

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#676]
pimcore added the `setlocale(LC_ALL, $localeList);` in the frontend action controller. Since then we have experienced some weird problems with the Zend_Currency. To reproduce this:

- create a document with **german** as language
- check if **bcmath** is installed on your server
- check if locale is installed on your server (`de_DE.utf8`), check this command via ssh: `$ locale -a`)
- open `pimcore/lib/Pimcore/Controller/Action/Frontend.php` and add right after `\Carbon\Carbon::setLocale($locale->getLanguage());`

```
$currency = new \Zend_Currency('de_DE');
echo $currency->toCurrency(22, array('symbol' => 'EURO'));
```
- call the url to reach the document you created before

instead of `22,00` you should see `220,00`.

**Comment by brusch** [comment]
Hmm, I'm not sure if this is something Pimcore has to address. 
The problem is in `Zend_Locale_Format`: 
On line 329 value is `22.0` (string with `.`): 
https://github.com/zendframework/zf1/blob/master/library/Zend/Locale/Format.php#L329 

Then on Line 344 `$value` is passed through `$value = Zend_Locale_Math::normalize($value);` and here the problem happens ... 

This function uses `localeconv()` to get the formatting info for the specified locale. 
In the case of `de_DE` the value for `thousands_sep` is `.`, remember the current `$value` is `22.0` which is processed on line `177` by `$value = str_replace($convert['thousands_sep'], "",(string) $value);` after this function `$value` is `220`. 

In my opinion this is a bug in ZF, isn't it?

**Comment by brusch** [comment]
`setlocale(LC_ALL & ~LC_MONETARY, $localeList);` instead of `setlocale(LC_ALL, $localeList);` would fix if, but I don't think this is the right way how to solve the problem. 

Thanks for your thoughts.

**Comment by solverat** [comment]
i think the problem starts here:
https://github.com/zendframework/zf1/blob/210190dab599e2897220648c9040bce9ff76f21f/library/Zend/Locale/Math.php#L81

i opened a ticket there (https://github.com/zendframework/zf1/issues/706) but i we can't expect a fix within the next few days i think. so what could be a solution? 

maybe a constant which disables the setlocale?

```php
//in constants.php
define("PIMCORE_SETLOCALE", FALSE);

//in Frontend.php
if( !defined("PIMCORE_SETLOCALE") || (defined("PIMCORE_SETLOCALE") && PIMCORE_SETLOCALE === TRUE) {
   setlocale(LC_ALL, $localeList);
}

**Comment by brusch** [comment]
Thanks for opening a ticket at zf1. 
Concerning short term solution: I'll try to find a solution which can be easily removed later.

**Comment by brusch** [comment]
Temporary fix is: `setlocale(LC_ALL & ~LC_MONETARY, $localeList);`
see also: 6d293031d97e14671ed13c2a7355050f3ce58875 

The main intention for calling `setlocale()` at the moment is formatting dates using Carbon, so it shouldn't hurt to exclude `LC_MONETARY` for the moment.

**Comment by solverat** [comment]
Matthew Weier O’Phinney [announced yesterday](https://framework.zend.com/blog/2016-06-28-zf1-eol.html) that ZF1 will reach the End-of-Life with the 28.09.2016. So i think there will be no further ZF1 bugfixing. This is some hot news for Pimcore itself also!

**Comment by brusch** [comment]
Thanks for the update!
