### ISSUE TITLE
No Primary Index on object_relations_KEY tables

### ISSUE THREAD

**Issue by christophluehr** [pimcore/pimcore#6800]
# Bug Report

### Expected behavior

Generated SQL tables object_relations_KEY should have a primary index, in
order to not run into troubles with Percona XtraDB Cluster:

https://www.percona.com/doc/percona-xtradb-cluster/LATEST/features/pxc-strict-mode.html#tables-without-primary-keys

### Actual behavior

Generated SQL tables object_relations_KEY has two indexes, but no primary index.

Is there a reason for these tables not having a primary key/index? As InnoDB states:

> InnoDB is called an index-organized storage engine. An index-organized storage engine uses the B-Tree of the primary key to stores the data, the table rows. That means a primary key is mandatory with InnoDB. If there is no primary key for a table, InnoDB adds a hidden auto-incremented 6 bytes counter to the table and use that hidden counter as the primary key. There are some issues with the InnoDB hidden primary key. You should always define explicit primary keys on your tables. 

https://www.percona.com/blog/2018/07/26/tuning-innodb-primary-keys/

Adding an explicit index would solve Errors like these:

`[Warning] [MY-000000] [WSREP] Percona-XtraDB-Cluster doesn't recommend use of DML command on a table (mydatabase.object_relations_MyObjectClass) without an explicit primary key with pxc_strict_mode = PERMISSIVE`

What do you suggest / how to proceed?

**Comment by weisswurstkanone** [comment]
I think you can find an explanation here:
https://github.com/pimcore/pimcore/issues/5761

**Comment by christophluehr** [comment]
Interesting - still, as far as i understand, a "virtual", internal key/index is added anyway due to the InnoDB engine, and adding an explicit one would not change that behaviour, but optimize Percona XtraDB Cluster support. Am i missing something?

**Comment by tecbird** [comment]
Here are my additional two cents, primary key is relevant for mysql cluster replication. 
Copy a small piece of text from https://federico-razzoli.com/primary-key-in-innodb:

`What happens if there is no primary key? A NOT NULL UNIQUE index will be used instead. But what if there is no such index? In that case, the whole rows to modify are written in the binary log and sent to the slave. To replicate the change, the slave will have to find the rows with a full table scan, which is obviously much slower.`

**Comment by dvesh3** [comment]
duplicate #6960
