### ISSUE TITLE
[Pimcore 10] Symfony Flex Support

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#6816]
Are there any plans to integrate Pimcore into Symfony Flex?

**Comment by msphn** [comment]
You mean a flex recipe? What you expect it to do?

**Comment by dpfaffenbauer** [comment]
1. support flex for bundle installation
2. remove stuff that flex solves (loading bundle/config/pimcore/config.yml, bundle/config/pimcore/routing.yml)
3. remove merging of security config
4. move project structure to symfony 4 suggested structure
5. create a recipe for Pimcore to install correctly

that sort of stuff

**Comment by brusch** [comment]
The only thing we cannot do at the moment is: 
- remove stuff that flex solves (loading bundle/config/pimcore/config.yml, bundle/config/pimcore/routing.yml)

Because this wouldn't be possible without breaking the compatibility of bundles. Our intention is that Bundles that work with 6.8 without deprecation notices should also work with 7.0, but that wouldn't work if we remove that feature - but we can of course deprecate it in 7.0 as soon as Pimcore fully supports Flex.

**Comment by dpfaffenbauer** [comment]
Deprecate it now, remove it with 8.0? So bundle maintainers can prepare for it?

**Comment by dpfaffenbauer** [comment]
well, deprecate it with 7.0 and remove with 8.0

**Comment by brusch** [comment]
Deprecating it now without any replacement doesn't make sense to me, let's wait for 7 when there's a replacement.

**Comment by dpfaffenbauer** [comment]
yep, as I said, I was to unclear :) But seems for on the same page.

**Comment by brusch** [comment]
Done for now: 

✅ support flex for bundle installation
✅ remove merging of security config
✅ move project structure to symfony 4 suggested structure

🟥 create a recipe for Pimcore to install correctly
We keep the skeleton approach for now, as it probably doesn't make sense to install pimcore as a recipe. 

🟥remove stuff that flex solves (loading bundle/config/pimcore/config.yml, bundle/config/pimcore/routing.yml)
See above, we'll keep that for now -> to be removed in Pimcore 11.
