### ISSUE TITLE
Replace Pixlr Image Editor

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#683]
https://creativesdk.adobe.com/ seems to be the only alternative at the moment (HTML5).

**Comment by brusch** [comment]
![image](https://cloud.githubusercontent.com/assets/142037/16256544/1fa26024-3853-11e6-86a8-96ad618d6323.png)

**Comment by Cruiser13** [comment]
@brusch the Pixlr editor is more professional (at least in this version: https://pixlr.com/editor/ ) and has been a selling point for pimcore assets here. What is the reason you're switching to CreativeSDK now?

**Comment by brusch** [comment]
Pixlr is still Flash. More and more browser start to block flash by default: 
http://9to5mac.com/2016/06/14/with-safari-10-on-macos-sierra-adobe-flash-will-be-disabled-by-default-when-browsing-the-web/
...

If you have any other HTML5/WebGL/Canvas alternative, we're happy to discuss :)

**Comment by Cruiser13** [comment]
I know that flash is a problem but since it's in the backend we can force people to use it. The current HTML5 image editors are no real option, most do not even support layers. They are - like the CreativeDSK - more like a toy. They are great to add filters for instagram like stuff but they are nonsense if you're trying to work more professional with a picture in my opinion.
I'd not remove Pixlr until a more professional HTML5 alternative arrives. There are some evolving very nicely but none are quiet as mature as Pixlr.

Please provide an option to use Pixlr instead of CreativeSDK instead of removing it completely.

**Comment by brusch** [comment]
I didn't know that somebody is really seriously using Pixlr with layers ;-).  I thought the image editor is just used to do some very basic cropping and orientation stuff, which is also possible with Creative SDK. 

Maybe Pixlr can continue it's existence in Pimcore as a plugin? 
Any other thoughts on this? Thanks!

**Comment by Cruiser13** [comment]
We do use Photoshop in our agency but some of our customers have MS Paint in the best case.
It's not just about layers but also advanced selections and such features. Removing a license plate from a photo uploaded works nicely with Pixlr for example. The results with Creative SDK are not satisfying.

I don't know if Creative SDK will be useful for anybody while Pixlr was useful (and is still part of our customer documentation for the Pimcore backend). While there is no similar useful replacement, I'd vote for an option to leave Pixlr in the core, maybe offering Creative SDK as optional replacement or replacing the simple Pixlr mode with Creative SDK. The simple edit more of Pixlr had similar options Creative SDK has.

**Comment by brusch** [comment]
Thanks again for your thoughts. Let's see if anybody else has an opinion on that.

**Comment by dpfaffenbauer** [comment]
I also like Pixlr more than the new one. but I only need things like cropping.

Pixlr as a plugin would be a good compromise.
