### ISSUE TITLE
Ecommerce: Incorrect calculation of order sum with voucher (rounding error)

### ISSUE THREAD

**Issue by Shobba** [pimcore/pimcore#6859]
# Bug Report

### Scenario
- I want to order an item with a price of EUR 22,195.95 (+ EUR 200.00€ shipping)
- I enter a 10% voucher code and see that I get a discount of EUR 2,219.60 (2,219.595 rounded up to .60)

### Expected behavior
My final order sum is
22,195.95 + 200.00 - 2,219.60 = EUR 20,176.35

### Actual behavior
The final order sum is EUR 20,176.36. But the credit card security form shows the correct amount of EUR 20,176.35.

### Steps to reproduce
Enter a voucher which produces a discount containing 0.5 Cent.
Because of PHP_ROUND_HALF_UP the discount will be rounded up when displaying it on the page.
When also displaying the sum (now also containing 0.5 cent), which also gets rounded up (PHP_ROUND_HALF_UP), you produced an incorrect calculation.
Because the discount value is a negative value in our calculation, this should get rounded down instead of up.
Internally Pimcore does it correctly because it uses Decimals all the way until the grand total, I guess that's why the correct amount gets transferred to the credit card payment provider.

<img width="1147" alt="Bildschirmfoto 2020-07-30 um 12 41 08" src="https://user-images.githubusercontent.com/2971787/88915793-328f3f80-d265-11ea-9bcd-66b1c6bac43c.png">
<img width="450" alt="Bildschirmfoto 2020-07-30 um 12 42 33" src="https://user-images.githubusercontent.com/2971787/88915791-31f6a900-d265-11ea-9832-8aefdd834a16.png">
<img width="807" alt="Bildschirmfoto 2020-07-30 um 12 42 47" src="https://user-images.githubusercontent.com/2971787/88915782-30c57c00-d265-11ea-9e4f-7d5cfefa9bb2.png">
<img width="621" alt="Bildschirmfoto 2020-07-30 um 12 43 21" src="https://user-images.githubusercontent.com/2971787/88915776-2efbb880-d265-11ea-8051-509ed9e8e892.png">

**Comment by fashxp** [comment]
The thing is, that the currency formatter does some rounding, and so internal sums and display do not match which results in faulty display of sums.

I'm not sure what's the best way to fix that.

Setting decimal_scale to 2 would fix it - with the cost of less precision for possible other internal calculations (not sure how big that cost is): 
```
pimcore_ecommerce_framework:
    decimal_scale: 2
```

Other possible solution would be to round cart discounts to lower precision, as done in https://github.com/pimcore/pimcore/pull/6864
This would fix this obvious case, but somehow this feels more like a fixing symptoms than fixing the cause. 
Because changing decimal precision in display to 1 digit could cause same problems again.
