### ISSUE TITLE
Ghostscript versions >9.50 have problem to get page count

### ISSUE THREAD

**Issue by blankse** [pimcore/pimcore#6911]
# Bug Report

If you have a ghostscript version >9.50 the maintenance script don't create thumbnails
```
 Exception: Unable to get page-count of /var/www/pimcore/web/var/assets/test.pdf in /var/www/pimcore/vendor/pimcore/pimcore/lib/Document/Adapter/Ghostscript.php:148
```

If I test the command I get following error:
```
gs -dNODISPLAY -q -c '(/var/www/pimcore/web/var/assets/test.pdf) (r) file runpdfbegin pdfpagecount = quit'
Error: /invalidfileaccess in --file--
Operand stack:
   (/var/www/pimcore/web/var/assets/test.pdf)   (r)
Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--
Dictionary stack:
   --dict:731/1123(ro)(G)--   --dict:0/20(G)--   --dict:75/200(L)--
Current allocation mode is local
Last OS error: Permission denied
GPL Ghostscript 9.52: Unrecoverable error, exit code 1
```

It seems ghostscript has a SAFER mode on and we need to add a"permit-file-read" param:
https://stackoverflow.com/questions/40156190/ghostscript-error-invalidfileaccess-in-file

**Comment by vg-bgp** [comment]
Hi there

We had the same issue and fixed it by adding the option `--permit-file-read` to the Ghostscript.php.
Our getPageCount() method looks like this:

```
public function getPageCount()
    {
        $folder_path = '/';
        $pages = Console::exec(self::getGhostscriptCli().' -dNODISPLAY -q --permit-file-read='.$folder_path." -c '(".$this->path.") (r) file runpdfbegin pdfpagecount = quit'", null, 120);
        $pages = trim($pages);

        if (!is_numeric($pages)) {
            throw new \Exception('Unable to get page-count of '.$this->path.' folder_path: '.$folder_path);
        }

        return (int) $pages;
    }
```

How did you fix your issue?

**Comment by blankse** [comment]
@vg-bgp I haven't enough time to investigate more. I downgrade Ghostscript to version 9.27

Can you create a PR?

**Comment by dvesh3** [comment]
fixed by #6953

**Comment by mcg-pimcore** [comment]
Hello,

I am having same issue, but on bin/console portal-engine:update:process-index-queue command. 
GS version:-9.53
os: alma 9

This issue is not with every pdf,but for some selected pdf. 

Error stack
11:53:30 ERROR     [pimcore] Symfony\Component\Process\Exception\ProcessFailedException: The command "/bin/nice -n 19 /bin/gs -dNODISPLAY -q --permit-file-read='/public/var/assets/form_fr.pdf' -c '(/public/var/assets/form_fr.pdf) (r) file runpdfbegin pdfpagecount = quit'" failed.

Exit Code: 1(General error)

Output:
================
Error: /invalidfileaccess in --file--
Operand stack:
   (/public/var/assets/form_fr.pdf)   (r)
Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--
Dictionary stack:
   --dict:730/1123(ro)(G)--   --dict:0/20(G)--   --dict:75/200(L)--
Current allocation mode is local
Last OS error: Permission denied


Error Output:
================
GPL Ghostscript 9.54.0: Unrecoverable error, exit code 1
 in /vendor/symfony/process/Process.php:272
Stack trace:
#0 /vendor/pimcore/pimcore/lib/Document/Adapter/Ghostscript.php(139): Symfony\Component\Process\Process->mustRun()
#1 /vendor/pimcore/pimcore/models/Asset/Document.php(64): Pimcore\Document\Adapter\Ghostscript->getPageCount()
#2 /vendor/pimcore/portal-engine/src/Service/Asset/ThumbnailService.php(70): Pimcore\Model\Asset\Document->processPageCount()
#3 /vendor/pimcore/portal-engine/src/Service/SearchIndex/Asset/IndexService.php(389): Pimcore\Bundle\PortalEngineBundle\Service\Asset\ThumbnailService->getThumbnailPath()
#4 /vendor/pimcore/portal-engine/src/Service/SearchIndex/Asset/IndexService.php(236): Pimcore\Bundle\PortalEngineBundle\Service\SearchIndex\Asset\IndexService->getCoreFieldsIndexData()
#5 /vendor/pimcore/portal-engine/src/Service/SearchIndex/Asset/IndexService.php(327): Pimcore\Bundle\PortalEngineBundle\Service\SearchIndex\Asset\IndexService->getIndexData()
#6 /vendor/pimcore/portal-engine/src/Service/SearchIndex/IndexQueueService.php(434): Pimcore\Bundle\PortalEngineBundle\Service\SearchIndex\Asset\IndexService->doUpdateIndexData()
#7 /vendor/pimcore/portal-engine/src/Service/SearchIndex/IndexQueueService.php(391): Pimcore\Bundle\PortalEngineBundle\Service\SearchIndex\IndexQueueService->doUpdateIndexData()
#8 /vendor/pimcore/portal-engine/src/Service/SearchIndex/IndexQueueService.php(189): Pimcore\Bundle\PortalEngineBundle\Service\SearchIndex\IndexQueueService->doHandleIndexData()
#9 /vendor/pimcore/portal-engine/src/Command/Update/ProcessIndexQueueCommand.php(95): Pimcore\Bundle\PortalEngineBundle\Service\SearchIndex\IndexQueueService->handleIndexQueueEntry()
#10 /vendor/webmozarts/console-parallelization/src/Parallelization.php(489): Pimcore\Bundle\PortalEngineBundle\Command\Update\ProcessIndexQueueCommand->runSingleCommand()
#11 /vendor/webmozarts/console-parallelization/src/Parallelization.php(442): Pimcore\Bundle\PortalEngineBundle\Command\Update\ProcessIndexQueueCommand->runTolerantSingleCommand()
#12 /vendor/webmozarts/console-parallelization/src/Parallelization.php(269): Pimcore\Bundle\PortalEngineBundle\Command\Update\ProcessIndexQueueCommand->executeChildProcess()
#13 /vendor/symfony/console/Command/Command.php(298): Pimcore\Bundle\PortalEngineBundle\Command\Update\ProcessIndexQueueCommand->execute()
#14 /vendor/symfony/console/Application.php(1046): Symfony\Component\Console\Command\Command->run()
#15 /vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand()
#16 /vendor/symfony/console/Application.php(299): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand()
#17 /vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun()
#18 /vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()
#19 /bin/console(46): Symfony\Component\Console\Application->run()
#20 {main}

**Comment by blankse** [comment]
> Last OS error: Permission denied

@mcg-pimcore Seems like the file permissions of `/public/var/assets/form_fr.pdf` are wrong. Can you check it?

**Comment by mcg-pimcore** [comment]
@blankse thanks for reply, but I have given recursive 777 permission to public/var folder. So doesn't look like permission problem.

**Comment by blankse** [comment]
@mcg-pimcore When you try this command in the Pimcore root directory you got the error, right?
`/bin/gs -dNODISPLAY -q --permit-file-read='/public/var/assets/form_fr.pdf' -c '(/public/var/assets/form_fr.pdf) (r) file runpdfbegin pdfpagecount = quit'`

Can you test this command?
`/bin/gs -dNODISPLAY -dNOSAFER -q -c '(/public/var/assets/form_fr.pdf) (r) file runpdfbegin pdfpagecount = quit'`

**Comment by MarcProe** [comment]
Ran into the same error, ```-dNOSAFER``` worked for me. Thanks a lot!
