### ISSUE TITLE
Last Login Is Zero

### ISSUE THREAD

**Issue by 9988princegarg** [pimcore/pimcore#7043]
The last login didn't update in the user table if the user login via "Login as this user in different browser".

**Comment by NiklasBr** [comment]
This is an interesting question actually, if I'm pretending to be you, and I log in to your account... When was the last time *you* logged in?

**Comment by brusch** [comment]
I'd say this is actually intentional behavior, that's why we're updating the timestamp here: 
https://github.com/pimcore/pimcore/blob/163f95e61ac97b8d5997932827ba93cc85755b0b/lib/Tool/Authentication.php#L40
and not somewhere else where it would be generic. 
I'll close this issue for now, but feel free to continue the discussion.
