### ISSUE TITLE
Import report needs a scrollview

### ISSUE THREAD

**Issue by Karthi96** [pimcore/pimcore#7124]
# Bug Report

### Expected behaviour
As a user, I should be able to see the complete report and should be able to download it.

### Actual behavior
When we Import a bulk of data into pimcore using CSV import, we could able to search the report for fewer objects. In my case, I imported 800 objects and around 200 have failed but I'm not able to see the complete failed/succeed report.

**Comment by dvesh3** [comment]
@Karthi96 please check your version as scrolling issue was fixed in v6.6.2. please see https://github.com/pimcore/pimcore/pull/6226

and you can also filter the result based on success status:
![image](https://user-images.githubusercontent.com/5137917/93462560-cfc23800-f8e6-11ea-9939-4f7b55f54ae4.png)

**Comment by Karthi96** [comment]
@dvesh3 Thanks, My pimcore version is 6.4.2, and let me try by upgrading the pimcore.

**Comment by Karthi96** [comment]
@dvesh3  Thanks, I have verified this on the latest pimcore version, it's working as expected. Hence closing the ticket.
