### ISSUE TITLE
[DataObject][ObjectBricks] API improvements

### ISSUE THREAD

**Issue by jremmurd** [pimcore/pimcore#7194]
# Improve brick api

If I want to access a field of an object brick, which may exist or not I would have to check if the brick exists on every getter call. It's kinda similar if I want to create or update a brick value. Currently I would have to do something like this:

Maybe a get or create like:

```php
    public function getOrCreateAttributesColors(): ?AttributesColors
    {
        if ($brickContainer = $this->getAttributes()) {
            if (!($brick = $brickContainer->getAttributesColors())) {
                $brick = new AttributesColors($this);
                $brickContainer->setAttributesColors($brick);
            }
        }
        return $brick ?: null;
    }
```

So I could do something like:
```php
$object->getOrCreateAttributesColors()->getGreen();
```
without getting an error `... call to a member function getGreen() on null ...`.

* But what if I call `->save()` on the `$object` after the `->getOrCreate...` call? I would have an empty brick in the object, which would not be intended.
* Maybe add a possibility to getOrCreate the brick just for reading? 

In the long run it would be a good thing to find a standardized way for other data types as well, also see https://github.com/pimcore/pimcore/issues/5129.

**Comment by passioneight** [comment]
Seems like this is long overdue. @dvesh3 any updates?

Additionally, I would love to see methods in the object's class based on the brick fields. I.e., imaging the following class & brick:

1. `User` (class), which contains a field `apiInfo`, referencing the brick in Nr. 2
2. `ExternalApiXY` (object brick), containing a field `remoteId`

Based on this, the generated class should contain something like this:

```php
public function getRemoteIdForExternalApiXY()
{
    $objectBrick = $this->getApiInfo();
    return $objectBrick->getExternalApiXY()?->getRemoteId();
}
```

When it comes to the setter, I'd expect this:

```php
public function setRemoteIdForExternalApiXY(?string $remoteId)
{
    $objectBrick = $this->getApiInfo();
    $brick = $objectBrick->getOrCreateExternalApiXY()->setRemoteId($remoteId);
    $objectBrick->setExternalApiXY($brick);

    return $this;
}
```

> Also, consider localized fields.

This will have the following benefits:
- Improved code readability, since we can just call `$user->setRemoteIdForExteranlApiXY($remoteId);`
- Decreased TTM, since we don't need to override the models to implement every field ourselves (or whatever your preferred solution is in this context)
- Allow mapping data to Symfony forms, even if it's inside bricks (at least in its simplest form, i.e., `TextType`, `ChoiceType`, ...)
- ... and potentially more

**Comment by fashxp** [comment]
Dear community, it's been a while since that issue was updated the last time, so we decided to close it for now. If you're still interested in contributing, feel free to add comments here or contact us before creating a pull request to discuss next steps.

Thanks for your understanding.
