### ISSUE TITLE
Remove PhpEngine Support

### ISSUE THREAD

**Issue by dvesh3** [pimcore/pimcore#7224]
Related to: #7218

**Comment by thgross** [comment]
Does this mean that PHP-templates will no longer work in 7.0.0?

**Comment by brusch** [comment]
Yes, Symfony removed them in v5.

**Comment by thgross** [comment]
I know that Symfony 5 does no longer support PHP templates.

However, there wasn't even a notice that pimcore 7 might only support Symfony 5 until very recently in https://github.com/pimcore/pimcore/issues/7283.
So, when Symfony 4 could still be supported, why not PhpEngine?

As a developer, I understand that sometimes, stuff needs to be cut to maintain the code. But in this case, the warning time is far too short.
Even Symfony supports v4.4 up until late 2023 (!).

**Comment by brusch** [comment]
@thgross Thanks a lot for your feedback! 
It was clear that Pimcore 7 will also drop support for PHP templates as soon as Symfony announced that quite a long time ago for v5. The reason is because we at Pimcore only support features that can be used across all supported Symfony versions (this was also the case for Pimcore 5/6). I'm really sorry if we haven't communicated the topic explicitly enough.
So this task is not really related with  #7283 because this was decided already far earlier. 

But you're not lost. We're absolutely aware of enterprise needs and therefore we're providing LTS support for Pimcore 6 and also an extra bundle that adds PHP template support for Pimcore 7 as part of our enterprise subscription.

**Comment by Cruiser13** [comment]
It'd be great to get some further information about the enterprise PHP Template bundle soon so we could inform our clients of the changes incoming. Rewriting big instances from PHP Templates to Twig would be very expensive.

**Comment by brusch** [comment]
@Cruiser13 we haven't finished all the details yet, but what I can share already as of now is that the PHP templating bundle will be part of our optional LTS package on top of our enterprise subscription. Pricing will be around 2k/mo per instance (€1600,- for the subscription + €400 for the LTS package).
The LTS package will then include multiple options for you, like: 
- Rest Webservices bundle
- PHP templating bundle 
- 6.x LTS support 

Hope that helps you for planning 😊

**Comment by Cruiser13** [comment]
@brusch thank you for the infos!
