### ISSUE TITLE
[Data Objects] Remove `o_` prefixed of system properties and database columns

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#7341]
Add (maybe an optional) compatibility layer to the data objects views (e.g. `object_MyClass`. 

Also consider this BC layer: #12769

**Comment by brusch** [comment]
Done forget to include #7309

**Comment by brusch** [comment]
Postponed.

**Comment by mcop1** [comment]
@fashxp Bc layer would be great, but I think it would need some discussion. Whereas for javascript it wouldn´t be too big of a problem, what about the database? 

I had a look at the bundles and at least for them the database is the bigger problem, because in almost every bundle the properties are used in a direct sql statement or as condition for the listings, e.g. 

https://github.com/pimcore/data-hub/blob/6eda52aae09bd883340fd1f1f5f43b24aae9dec4/src/GraphQL/Resolver/QueryType.php#L287-L308

- Demo
Used as sql condition
- data-hub-simple-rest
Used for filtering/paging, used in WorkspaceResolver as sql condition
- data-importer
Used in sql statement
- data-hub
Used as sql condition, what about GraphQL?
- portal-engine
Used in sql statements
....

Thoughts:
- We can´t use generated columns, because they don´t work with auto_increment columns
- We could use a trigger to fill o_id/id, o_key/key, ... columns with the same values. But that would duplicate the amount of data, especially if we have to create another index for those columns
- We could use a view to select from, instead of selecting directly from objects table. This would give us the possibility to use column aliases and we would be more flexible in the future. But what about performance and what about other tables like assets and documents? 

Solution: 
https://github.com/pimcore/pimcore/issues/13512
