### ISSUE TITLE
Query Table + Fallback languages

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/pimcore#7721]
related to https://github.com/pimcore/pimcore/issues/7573

Currently the object_localized_query* table do not respect the fallback languages.

Discussion point: Should this be changed?

Example: In the system settings define de as fallback language for de_AT.

Modify some data for "de".

Current situation: Data in object_localized_query_de_AT does not change.

**Comment by ascheider** [comment]
@weisswurstkanone Hi Josef,

thanks for the opening this discussion.
From my point of view it is necessary to respect language data in query tables if setLocale method is used.
Maybe it is possible to add additional method to the Listing class like ignoreFallbackValues to select data only from given language.
It is already done ob object level with setGetFallbackValues method, see: https://pimcore.com/docs/pimcore/current/Development_Documentation/Objects/Object_Classes/Data_Types/Localized_Fields.html

**Comment by weisswurstkanone** [comment]
I fear that this is not possible. The data written to a language-specific query table is evaluated on save. There is no way to change anything at run time

**Comment by ascheider** [comment]
@weisswurstkanone yes, but the data in the language-specific table is saved correct. the problem is in the corresponding view, which has wrong data because of fallback. Or do i miss something?
This is the data in the table, if checkbox is not checked:
![image](https://user-images.githubusercontent.com/6016485/108321669-c9e9bf00-71c4-11eb-81f9-17fcdd94a96b.png)
This is the data in the view, if the checkbox is not checked:
![image](https://user-images.githubusercontent.com/6016485/108321777-e84fba80-71c4-11eb-8629-87b9a2af3561.png)
Maybe it is possible to add additional views like object_localized_localizedfieldsview_de_at_noinheritance or something like this, which have no fallback values like described in the PR and then select from this view if setGetFallbackValues on Listing class is provided?

**Comment by brusch** [comment]
System-wide configurable with symfony config, either old behaviour or new with confiding fallback languages.
