### ISSUE TITLE
[BUG] Changes in grid result in 'overwriting' the changes of the latest non-published version

### ISSUE THREAD

**Issue by RuudvdvNB** [pimcore/pimcore#7970]
# Bug Report

### Expected behavior
When you're saving a new unpublished version for a Data Object that has been published already, i expect that grid changes do not overwrite the new unpublished version.

### Actual behavior
Unpublished version changes are overwritten by a new published version when making changes using the grid. 

For our clients we are working with workflows, in the 'doing' places we only save new versions. After a review place the changes are published. But when there is a batch-edit (or import) the changes are done in the latest published version resulting in data loss because the new unpublished version is overwritten.

### Steps to reproduce
1. Create a new object & publish
2. Make new changes (input, image or add object bricks)
3. Now close the product and go to the grid
4. In the grid batch edit or change 1 field for the specific object
5. Open object, new unpublished version changes are overwritten by the published version (changes are lost, object bricks are removed)

### Additional info
This can be reproduced in the newest Pimcore version and in the the online demo.

**Comment by ramundomario** [comment]
I just encountered the same anomaly :confused:

**Comment by fashxp** [comment]
The thing is, that in grid view only published data is shown ... also because filtering is only possible based on data stored in query table, which is the published data.

So changing data in grid view only can change the published data, since newer not published version data is not visible there. And that consequently needs to result in the described behaviour. 
The changes from the unpulished version are still available in the version. 

See also https://github.com/pimcore/pimcore/issues/5136 and https://github.com/pimcore/pimcore/issues/5322

**Comment by fashxp** [comment]
Don't see a possibility to change that, but we are open for suggestions.
Close this for now though...
