### ISSUE TITLE
RFC: Rethink DataObject DB Changes

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#8256]
Pimcore currently makes DB changes directly on save of a DataObject or using the `deployment:classes-rebuild` command (which also generates class-files). This makes it very hard to deploy changes with SQL scripts only and always requires the rebuild command to run. You also don't know sometimes what actually happens and you could end up with data-loss.

What if Pimcore decouples that using Doctrine Schema Builder (as showcased here: https://github.com/pimcore/pimcore/pull/7786). First of all, this would remove complexity of Schema Generation out of the Models into separate classes (which potentially would allow adoptions of other SQL databases) and would also allow to create a diff of the current database state as SQL. Meaning, you could create Migration Files or run the SQL directly in the DB.

Combined with https://github.com/pimcore/pimcore/issues/8255 would be the 🍒  on top :)

**Comment by nandorholozsnyak** [comment]
I'm curious if there is any news on it? Will it be available once ?

**Comment by dpfaffenbauer** [comment]
@nandorholozsnyak since nobody commented on this since I created it almost a year ago, you can be pretty sure nothing changed in these regards.

It still is difficult to deploy Pimcore to things like Kubernetes. It got a lot better with Pimcore X, especially 10.2. But there is still a lot of room for improvement here.

**Comment by nandorholozsnyak** [comment]
Thanks.

We are having a lot of problems with our deployments when class/field collection/object brick changes are happening. We are doing it by hand on the UI, in the Class editor, we are uploading JSON files, but one bad click and the data is gone. 
We saw there are multiple ways to handle these changes, like the JSON exports and the definition_xy.php classes, but I'm curious why the Doctrine Migration based class evolution is not present in the documentation anymore?
We would like to have these small changes in different migration files, because it would make it more easier to version our changes. Isn't that supported anymore?
We are at 6.8.11, we are planning to create these migration php files, but is it supported in the new Pimcore X as well?

**Comment by dpfaffenbauer** [comment]
That was never supported... The way to handle this currently is:

 - GIT Versioning the files `var/classes/*_definition.php` but do not version the `var/classes/DataObject` files
 - On Deployment run `bin/console pimcore:deployment:classes-rebuild`

**Comment by nandorholozsnyak** [comment]
I think it was: https://pimcore.com/docs/pimcore/6.8/Development_Documentation/Development_Tools_and_Details/Migrations.html#page_Non-DB-Changes
We were experimenting with this. 
We have experienced a lot of deployment failures with the mentioned `classes-rebuild` method, any good advice on it?
We are running Pimcore in a docker container, with multiple instances. Is there any locking mechanism that is happening if more than one instance is calling the `classes-rebuild`?

**Comment by dpfaffenbauer** [comment]
No, it never was really supported. In theory you should be able to change the class-definition and either Pimcore generates a migration for all tables or you can do with a command. Similar to how doctrine handles changes.

I never have problems with classes-rebuild. I am currently experimenting with Kubernetes, and there I run a migrate Job to handle that for me. As well as in entrypoint I run it to generate the class files. More instance can run the command without any issue, the first one tu run it does the actual DB changes.

**Comment by dpfaffenbauer** [comment]
@nandorholozsnyak this should be a good starter: https://github.com/pimcore/pimcore/pull/11373

**Comment by nandorholozsnyak** [comment]
"In theory you should be able to change the class-definition and either Pimcore generates a migration for all tables or you can do with a command" - is there any command in the 6.8 build that would let us generate these migrations files that have all the code to build those classes and database schemas? We were searching but were not able to find. 

And on the other hand the biggest problems we are facing is that we are having around almost 14 million records in our orders table (object_query_EF_OSO and object_store_EF_OSO) and it can take a lot of time (few minutes) to apply the new class changes. From the UI it breaks every time and in worse case scenario the instances are starting to die because of a Health Check. Searching in orders are also a nightmare.

**Comment by dpfaffenbauer** [comment]
>  is there any command in the 6.8 build that would let us generate these migrations files that have all the code to build those classes and database schemas? We were searching but were not able to find.

I said in theory, that means it does not exist ;)

**Comment by nandorholozsnyak** [comment]
Thank you. I saw you reopened the PR, hope it gets more attention now. Could be interesting for us as well, but I would be on the side of create incremental migration files to evolve the database.

**Comment by dpfaffenbauer** [comment]
I tried several times but never got reviewed, I am closing it now.

**Comment by brusch** [comment]
Let me quote https://github.com/pimcore/pimcore/pull/14218#issuecomment-1441444250 here
>  I am not sure if it can be finished within a reasonable timespan

We never stated  that this is not relevant or not wanted, but anyway...

**Comment by dpfaffenbauer** [comment]
I will not provide a PR for this anymore. 

With what I feel is going on, there is a clear change in mindset, execution and/or priorities in Pimcore. Being Community not one of them. 

At least there is no clear communication. Everybody can see there are changes, and it doesn't seem for the better of the Community Edition. This is sad and frustrating... Time will tell, you will tell eventually. We don't know anything.

**Comment by brusch** [comment]
I'm sorry to hear about your concerns and uncertainties but I can feel you to a certain extend. We're currently do some housekeeping to maintain focus and clarity, better manage our resources, and clearly communicate to the community what they can expect to see in the product anytime soon.
Additionally we were evaluating different approaches to streamline our development power and internal workflows. That was also the reason for e.g. this https://github.com/pimcore/pimcore/issues/15824#issuecomment-1843606821 .
But it turned out that the current approach with exclusively working in CE repos is the most efficient one, so we stick to that - in a nutshell: nothing will change here. 

Please be assured, the community remains a vital part of our priorities. One of our main upcoming projects is the new UI, which will be available to the CE as well. 

Sorry again for the confusion and I hope you understand that communication is not always easy  😊

**Comment by dpfaffenbauer** [comment]
@brusch 

Glad to hear that. 

Please be aware that most of what you do can be seen in the Community and everybody jumps to conclusions. Especially by frequent Contributors. If you do changes, if you test things, whatever it is, inform us. I am in constant contact with many different partners and developers. Pimcore EE and CE is a constant Topic of where it is and where the future might be. Seeing a repo like pimcore/ee-pimcore is scary without any information. Pimcore Enterprise gives lots of People insecurities about the Future of Pimcore CE anyway.

**It is more important than ever to clearly communicate the importance of Pimcore CE and the Pimcore Community!** 

Not everything has to be Enterprise, not everything has to be CE. There is a fine line. I understand the importance of Enterprise and I am fully behind that. But Community is what made Pimcore partly what it is today. Better over-communicate than under-communicate.

FYI @NiklasBr

**Comment by brusch** [comment]
@dpfaffenbauer Thanks for your feedback! I agree, sometimes I / we just completely underestimate the impact of certain actions I / we do, and I'm really sorry for that.

**Comment by Cruiser13** [comment]
@brusch thanks for the clarifications! We have also been worried a little bit here, seeing a lot of improvement/feature issues being closed while some of the former pimcore developers left the company... good to hear that CE is still important and will get stronger.

**Comment by NiklasBr** [comment]
For me it's very much a matter of trust and communication. When a customer asks of me why their Pimcore system is not adhering to local laws I need to trust that Pimcore will listen to us when I report the problem. It should not require a sworn affidavit by the customer's CTO signed off by a their legal staff in two copies so that it does not get dismissed as unimportant…

I want, generally speaking, to be able to tell my customers that while the Pimcore guys are not working actively this very moment on something they need or require, Pimcore at least listened. But as of the recent communication made clear to me, that is not at all the case. My customer is clearly not important, and neither am I. I suppose that's okay, that's the way it is, I now need to deliver the bad news that it is unclear if Pimcore is working in their best long-term interest or not.

There are many decisions I do not see the logic in in right now. They send odd signals, those include but are not limited to:

- Why did Pimcore chose to spend their limited resources on *three* different User Interfaces: "Apollo", "Enterprise Classic", and "Community Classic" (or whatever we should call them). It also seems like it will make the job of Pimcore harder and cost additional resources because keeping documentation up-to-date with screen shots and examples for all three will be much more work.
- The new versioning system is still a bad idea. I am glad you opened up the relevant repo, it means a little less confusion, but it is still worse than a regular semantic versioning. But I suppose that's not something that will change. It is what it is.
- I stumbled on a comment on Advanced-object-search that the development of that bundle is effectively on hold for some time now into the future. Why are such things not being communicated clearly and openly? Colleagues were mildly put annoyed of the lack of information when I sent that comment link to them.

It's not about CE vs EE, although it is a worry in the back of my mind as well. From my point of view, you communicated that the issues I had reported did not matter, so I protested a bit, noticed that it did not help, and came to the conclusion that contributing to Pimcore is not something I want to do right now.

~As for the PR in the admin-ui-bundle repo, you locked it so that I was unable to answer your comments and questions.~ It was the [bot](https://github.com/pimcore/admin-ui-classic-bundle/pull/324#event-11292353021), sorry for that

**Comment by fashxp** [comment]
Thank you for your message and I can understand you.

On the key part, I wanted to share our perspective too:
We listened, we discussed, we decided on priorities for us in consideration with all the other topics (which are different to yours, fair enough), we invited the community to contribute and after several years of inactivity we are doing some house keeping. 

This is not about not listening, not appreciating contributions or ideas and for sure nothing personal.

Actually, we are just doing, what we communicated in the [contributing guidelines](https://github.com/pimcore/pimcore/blob/11.x/CONTRIBUTING.md#inactive-issue-closing-policy) years ago.

Nevertheless, to all who a celebrating, we wish you nice holidays and a good start into the next year 🎄🎇🎆.

**Comment by NiklasBr** [comment]
I have to comment on this:

> we invited the community to contribute

What you said and what you did were not really in sync.

Maybe this can help you more fully see the context from our point of view. It can maybe be hard when you are deeply entrenched in your own situation. As just a community member with some customers we are consistently kept in the dark regarding what is _actually_ happening. We have to rely on what you say and what you show. You may not see it because you may now know what it is you know that you have not communicated to us.

Take for example problems with the UI. Let me describe it from our perspective why "PR:s welcome" was just a label and not an actual instance of PR:s being welcomed.

I think it was in the middle of the Pimcore 6.x era, plans for Pimcore 10 were taking shape, Pimcore announced that a new admin UI is on the roadmap for Pimcore X.

The result here is that Pimcore was communicating that there was a net negative value putting any major work into fixing the current user interface since an entirely new one was about to be released to replace the old one.

The optimistic/positive signal we received was that this was a good time to request changes and to participate in shaping the new thing according to our customer's technical and legal needs. Needs which in the grand scheme of things are quick easy to fix when building a new interface but hard and resource-consuming to do if done in an older one. And who in their right mind want to spend lots of time and money to fix things which might be made obsolete very soon?

Despite adding the "PR:s welcome" label, actual code contributions were signalled as "not welcome" by the Pimcore organisation us in two ways:
1. Any work we will do will be outdated and possible undone completely due to the next upcoming major release.
2. The place where the new interface code was being developed at were hidden away from us.

Then Pimcore 10 arrives without the new admin UI… That's all right, delays and re-prioritisations happen. But the new UI was still being planned, meaning that in reality PR:s are still useless because we are not allowed to participate in the new UI… Then Pimcore 11 arrives without the new admin UI. Still this is all right, delays and re-prioritisations happen. Today the new "Apollo" UI is still being teased. PR:s are still being signalled as useless because we are still not allowed to participate in providing code the new UI… Who in their right mind want to spend lots of time and money to fix things which is said to be made obsolete very soon?

The "PR:s welcome" label was not truthful from our perspective because we are prevented from actually participating, we are not allowed to actually send PR:s to improve the new UI. In reality all we can do is wait and hope for the best, and ask you to keep the request in consideration. And then we get told that we should have participated better in the process we were not invited into…
