### ISSUE TITLE
RFC: Rethink Serialization Process for Versioning/ReclyeBin 

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/pimcore#8257]
We had a lot of issues with DeepCopy for serialization of Elements for Versioning and/or RecycleBin. What if we completely get rid of that and introduce Symfony Serializer for that? That process is less Memory intense and more clear to understand what is going on.

Symfony Serializer would do the normalization and serialization of the data and also be responsible for de-serialization and de- normalization of the Version/RecyleBin.

**Comment by xlttj** [comment]
I wrote my own serializer / unserializer for transferring objects between Pimcore instances, even between Pimcore 4 and 6. I had do build my own one because other solutions weren't able to cope with recursions, tags assigned to objects, migrated class names and the like. Might that be of any interest?

**Comment by dpfaffenbauer** [comment]
Symfony serializer is possible to handle that.
