### ISSUE TITLE
Assets Versioning issue with different mime types

### ISSUE THREAD

**Issue by Maksonis** [pimcore/pimcore#8316]
When I upload new asset version, which have different mime type as original one, I lose original one.

**Steps to reproduce (on live pimcore demo):**

1. Take asset: http://demo.pimcore.fun/admin/login/deeplink?asset_69_image (it's a jpg)
![image](https://user-images.githubusercontent.com/17277953/109656409-af202e80-7b64-11eb-9ea9-3bab54211468.png)

2. Upload new version: png image
![image](https://user-images.githubusercontent.com/17277953/109656479-bfd0a480-7b64-11eb-9c73-bf0f8e7643ef.png)

3. Everything looks good, but filename of old version is png. When publish old version you get filename as png, but mime type image/jpeg
![image](https://user-images.githubusercontent.com/17277953/109656977-46858180-7b65-11eb-8d9b-e44065dfddd5.png)

This is issue when creating svg version of eps file, and want to revert back eps one

**Comment by dvesh3** [comment]
this is intentional behavior for cases like when you publish a version after rename or moving an asset. please see https://github.com/pimcore/pimcore/blob/10.x/models/Asset.php#L1878

 @brusch "upload new version" should be used to just replace the content. wdyt?
 
 Edit: I got this wrong...so we need to fix mime type(from current state) not the filename.

**Comment by brusch** [comment]
Fixed by #9230
