### ISSUE TITLE
Tool\Admin CSV import of translation does not return correct languages

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#8493]
# Bug Report

In Pimcore 6.8.10, when importing a CSV file such as `translations.csv` below:

```csv
"key";"da";"en";"nb";"sv"
"content.page-description";"";"Page text";"Side tekst";"Sidtext"
```

Using:
```php
Website::importTranslationsFromFile("translations.csv", true);
```

While having those languages set up in the System settings:

![image](https://user-images.githubusercontent.com/279826/111471693-7322c700-8729-11eb-90dd-07475792ac12.png)

...the *Norwegian Bokmål* `nb` string does not get imported because this code does not return any Norwegian data:

https://github.com/pimcore/pimcore/blob/369a9b93bfe23e44fa1e70e87c6e7758f8f108c0/lib/Tool/Admin.php#L42-L84

Using 
```php
\Pimcore\Tool::getValidLanguages();
```
would solve this issue

**Comment by dvesh3** [comment]
@NiklasBr Localization system setting is used for shared translations not admin. please see this section for adding your custom admin language https://pimcore.com/docs/pimcore/current/Development_Documentation/Multi_Language_i18n/Admin_Translations.html#page_Adding-your-own-admin-languages-since-v6-3-6

**Comment by NiklasBr** [comment]
This issue was not about admin languages, but about shared translations
