### ISSUE TITLE
Unable to upload assets (pimcore 6.8.11)

### ISSUE THREAD

**Issue by thgross** [pimcore/pimcore#8539]
# Bug Report

After updating to 6.8.11, I can no longer upload Images to any assets-folder. It looks like pimcore builds a wrong path to the uploaded file, see the screenshot below.

### Expected behavior

It is possible to upload images to an assets folder.

### Actual behavior

pimcore shows an error dialog:

![image](https://user-images.githubusercontent.com/5030864/112028255-46f7b380-8b38-11eb-845d-a2ad30950fc6.png)

### Steps to reproduce

1. install pimcore 6.8.11.
2. drag any image file to the Assets / Home folder.

**Comment by brusch** [comment]
I'm unfortunately not able to reproduce the issue, are you using a local or remote file-system? 
I assume the problem is somewhere here: 
https://github.com/pimcore/pimcore/blob/d272ea3c26e609afb799773427b969ec0cb461bb/lib/Helper/TemporaryFileHelperTrait.php#L50
Maybe you can quickly debug this? 
Thanks for your feedback!

**Comment by brusch** [comment]
@thgross I think I've found the issue you're experiencing, can you please confirm this PR #8546 fixes your issue?
Thanks!

**Comment by thgross** [comment]
@brusch I just patched the file with you PR and can confirm that it does resolve the issue.

Thanks you!

The problem was in fact slashes in the path (i.e. `/srv/www/www.website.de/tmp/filename`), so File::getFileExtension() returned something like `de/tmp/filename`.

**Comment by brusch** [comment]
Great, thanks for your feedback! 
I'll prepare a release asap. 👍
