### ISSUE TITLE
[Assets][Thumbnails] classes are not applied to generated tag then calling getHtml

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#8668]
```
{{ image.image.thumbnail('newsList').html({class: 'mr-3'}) | raw }} 
```
... `mr-3` is not applied to generated `<picture>` tag
see also https://x.pimcore.fun/en/News

**Comment by dvesh3** [comment]
@fashxp please see https://github.com/pimcore/pimcore/issues/8600#issuecomment-810150780

**Comment by dvesh3** [comment]
@fashxp please see https://github.com/pimcore/pimcore/issues/8600#issuecomment-810150780

**Comment by fashxp** [comment]
is that really necessary? is quite a pitfall for updating. 

TODOs if yes: 
- needs to be added to upgrade notes
- demo needs to be fixed.

**Comment by brusch** [comment]
I'd say yes, because where to apply the `class` attribute, on the `<img>` or on the `<picture>` tag? 
Depending on the use-case this can be different and caused confusion in the past (see linked tickets below). So I guess having the attributes separated for `<picture>` and `<img>` tag will prevent unintended behavior in the future. 

See also #4812 #4871 #4918

**Comment by brusch** [comment]
Fixing the demo was already started in pimcore/demo#211

**Comment by brusch** [comment]
Fixed remaining issues in demo in https://github.com/pimcore/demo/commit/791d00fd64b6b656ff9a8fff82e7cb29dfa22150
