### ISSUE TITLE
[Assets] Aspect-Ratio of folder preview images - wanted? 

### ISSUE THREAD

**Issue by fashxp** [pimcore/pimcore#9029]
![image](https://user-images.githubusercontent.com/8792145/117198199-018dfd80-ade9-11eb-8de3-d4be8f100311.png)

**Comment by brusch** [comment]
Actually this was wanted by me, so that you can see the entire contents of an image in folder preview an nothing is cut off. I've heard sometimes that very similar contents are together in one folder, and if we cut off contents it looks like 2 identical images are in there. 
I personally don't mind, it's just a preview.

**Comment by thgross** [comment]
Or we could use a frame transformation for the previews to keep the aspect ratio and don't cut off anything.

**Comment by brusch** [comment]
Would be possible as well, but then you'll loose the tile look & feel 🤔
