### ISSUE TITLE
Remove area bricks from extension management

### ISSUE THREAD

**Issue by brusch** [pimcore/pimcore#910]
- extension panel
- are enabled automatically, no more possibility to disable them
- cleaning up and making leaner

**Comment by solverat** [comment]
the possibility to disable bricks within the extensions.php will be still available? please? :)

**Comment by brusch** [comment]
Is this feature actively used at the moment? 
If so, any concrete use-case? :-)

**Comment by solverat** [comment]
YES! :) In some cases we're using a plugin which provides some different bricks, like a "google map" item or a "gallery" item. Not every customer needs every single brick, so we disable them (otherwise we need to style and integrate them properly). because the plugin itself comes as a bundle it's easy for us to maintain it. 

PS: Ok, we could add the disabled elements into a config file, so no armageddon with that task. :)
