### ISSUE TITLE
Objects: Content of WYSIWYG is not saved in certain circumstances

### ISSUE THREAD

**Issue by markus-moser** [pimcore/pimcore#924]
Reproducible in the Pimcore demo:

- open object with WYSIWYG field
- type in a text into the WYSIWYG
- save object
- remove complete text
- reload object
=> text is still in WYSIWYG

**Comment by brusch** [comment]
This is due the way how CKEditors `checkDirty()` method works (http://docs.ckeditor.com/#!/api/CKEDITOR.editor-method-checkDirty). 

So it isn't really a problem of deleting content, the problem happens if the content gets changed then the object gets saved and afterwards the content of the wysiwyg changes back to the initial value. In this case `checkDirty()` returns false, since the content is again the value it was initially. 

I've now implemented **once dirty, always dirty** in Pimcore's `isDirty()` method, so this cannot happen anymore.

**Comment by markus-moser** [comment]
thank you very much!
