### ISSUE TITLE
Set Markers & Hotspots on custom Thumbnails

### ISSUE THREAD

**Issue by solverat** [pimcore/pimcore#939]
Instead of using a fixed ImageSize (1000x800) in the HotSpotMarkerEditor, the real image should be loaded. Otherwise it's impossible to place markers/hotspots on a custom cropped image.

![bildschirmfoto 2016-10-13 um 15 56 41](https://cloud.githubusercontent.com/assets/700119/19351843/a815519c-915d-11e6-94f6-28d53e8d23cf.png)

The actual image size will be served in `/pimcore/static6/js/pimcore/document/tags/image.js`,
so it could be passed through the `pimcore.helpers.openImageCropper()` method.

**Comment by brusch** [comment]
Well, ... that depends on the point of view. 
We decided to make the definition of markers and hotspots independent from the thumbnail because of the following reasons: 
- different thumbnail formats for different device types / media queries
- editmode thumbnail must not be the thumbnail used for the output-channel

**Comment by solverat** [comment]
Good point. But how could a user achieve a correct marker placement, if different thumbnail formats / media queries or a different editmode thumbnail has been set? The position relies on the ratio of the backend-image (1000x800), so you're provided reasons won't work anyway - right? Or do i miss something?

**Comment by brusch** [comment]
It works, but you have to calculate the relative positions (percentages) according to your transformations - it's just math ;-)
