### ISSUE TITLE
Object property name (field)  gets 2x plus sign     ++     (+Name+)

### ISSUE THREAD

**Issue by ismetsener** [pimcore/pimcore#9477]
I created a object  "Address" 
after I created several fields like  name, address1, address2, postcalcode, city, country  etc

when I  add  a new Address, I  see :   +Name+
why I see these two plus signs

this happened also with other object I created  (Product -> LuxuryBags)
i created 2 fields, name and description, when I add a new Product
the name label looks like:  +Name+

why I see these two  + signs

when I try to add a new product , I see the mesage:
"+object_add_dialog_custom_text.LuxuryBag+"

regards,
Ismet

**Comment by ismetsener** [comment]
Strange, problem solved when I  Unchecked "Debug Admin-Translations (wrapped in +)" 
in system settings

**Comment by fashxp** [comment]
Docs [here](https://pimcore.com/docs/pimcore/current/Development_Documentation/Multi_Language_i18n/Admin_Translations.html) explain the feature. 

> Strings which are subject to special translations, but have not been translated yet, are displayed with a "+" in front and after the string, if Pimcore is in DEBUG mode.

Improved the wording a bit, since DEBUG mode is not exactly right there, see also [this commit](https://github.com/pimcore/pimcore/commit/c8262612cf3fc454005e2fa29309bd437df00e9e). 

In addition, this feature seems to not work properly, see also #9482
