### ISSUE TITLE
[Bug]:  Circular reference error when sending emails using Symfony Messenger

### ISSUE THREAD

**Issue by rubanooo** [pimcore/pimcore#9824]
### Expected behavior

When using a messenger transport the given object should be serializable with the default symfony serializer to whatever transport you have defined. In my case this is the `symfony/doctrine-messenger`

### Actual behavior

Because Symfony tries to serialize the `\Pimcore\Mail` class and this class contains the property `$document` of type `\Pimcore\Model\Document\Email` it fails to serialize the class because the document has a `$dao` property which has `$model` property which is the same as the `$document` property as before.

### Steps to reproduce

Use the Symfony serializer to serialize a `\Pimcore\Mail` object OR Setup the Symfony messenger to send `Symfony\Component\Mailer\Messenger\SendEmailMessage` class over a transport that needs to serialize the class.

See documentation on how to do this here: https://symfony.com/doc/current/mailer.html#sending-messages-async

**Comment by brusch** [comment]
Thanks a lot for reporting the issue. For our setups this issue is quite an edge-case and doesn't impact the stability or experience of the platform itself. Since it is quite time intensive for setting up a test scenario, we're not gonna work on that anytime soon.
Since you have already a running test-scenario we kindly ask you to debug and fix the issue and provide us a pull request.
Thanks for your understanding.

**Comment by dvesh3** [comment]
Fixed by #9838
