### ISSUE TITLE
[Bug]: On demo xliff export don't work

### ISSUE THREAD

**Issue by Yivan** [pimcore/pimcore#9852]
### Expected behavior

Xliff export should work.

### Actual behavior

A 500 error is responded.

### Steps to reproduce

On the demo, set export like this:

![image](https://user-images.githubusercontent.com/9025839/126796914-df84b6e0-c13c-4ba5-aecf-f96ed58a1160.png)

- On the online demo there will be this error:

![image](https://user-images.githubusercontent.com/9025839/126796991-d28d653e-d84a-4ba1-bc77-c08fdaa5d21a.png)

and response is empty:

![image](https://user-images.githubusercontent.com/9025839/126797049-7dcc20bf-65ce-4f7e-94da-9b07443a0a6d.png)

- On an installed demo with display of php error:

![image](https://user-images.githubusercontent.com/9025839/126797145-fcc88209-b70d-402e-8eb8-d3278c3d0f67.png)

Thanks for looking into it.

**Comment by dvesh3** [comment]
This happens due to `editmode = true` flag is passed to editable renderer from here, https://github.com/pimcore/pimcore/blob/2f18a0f26380c56b609d937b40d2050c8d1a3e1a/lib/Document/Editable/EditableUsageResolver.php#L57 and block editable generates generates the block indices for editmode JS handling https://github.com/pimcore/pimcore/blob/2f18a0f26380c56b609d937b40d2050c8d1a3e1a/models/Document/Editable/Block.php#L124

**Comment by dvesh3** [comment]
Fixed by #9886

**Comment by Yivan** [comment]
Great, thank you!
